In [2]:
import pandas as pd

In [39]:
df=pd.read_csv('boat_noise_earphones_raw.csv')

In [40]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 602 entries, 0 to 601
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   brand               602 non-null    str
 1   product_name        602 non-null    str
 2   handle              602 non-null    str
 3   product_url         602 non-null    str
 4   category            602 non-null    str
 5   product_type        602 non-null    str
 6   collection_source   602 non-null    str
 7   vendor              602 non-null    str
 8   sale_price_min_inr  602 non-null    float64
 9   sale_price_max_inr  602 non-null    float64
 10  mrp_inr             602 non-null    float64
 11  discount_percent    602 non-null    float64
 12  num_variants        602 non-null    int64
 13  colors              602 non-null    str
 14  skus                599 non-null    str
 15  in_stock_variants   602 non-null    int64
 16  tags_raw            602 non-null    str
 17  features_raw        602 non-null    str
 18  specs_raw_json      169 non-null    str
 19  description_raw     496 non-null    str
 20  image_url           600 non-null    str
 21  created_at          599 non-null    str
 22  updated_at          599 non-null    str
 23  published_at        599 non-null    str
 24  product_id          602 non-null    int64
dtypes: float64(4), int64(3), str(18)
memory usage: 117.7 KB

In [41]:
df.head(1)

,brand,product_name,handle,product_url,category,product_type,collection_source,vendor,sale_price_min_inr,sale_price_max_inr,...,in_stock_variants,tags_raw,features_raw,specs_raw_json,description_raw,image_url,created_at,updated_at,published_at,product_id
0,Noise,Airwave Max 3 Wireless Headphone,noise-airwave-max-three-wireless-headphone,https://www.gonoise.com/products/noise-airwave...,Headphones,Wireless Headphones,all-headphones,Noise,1999.0,1999.0,...,1,3 | _ct-product-type-audio-device_ | _sms-ct-N...,3 | _ct-product-type-audio-device_ | _sms-ct-N...,NaN,Buy Noise 3 Wireless Headphone that comes with...,https://cdn.shopify.com/s/files/1/0997/6284/fi...,2023-11-08T14:51:03+05:30,2026-09-23T22:08:21+05:30,2023-11-27T10:02:12+05:30,6943329058903

In [42]:
raw_copy=df.copy()

In [44]:
df['vendor'].value_counts()

vendor
boAtlifestylein    395
Noise              191
Gonoise             13
boAt Lifestyle       3
Name: count, dtype: int64

In [34]:
df['brand'].value_counts()

brand
boAt     398
Noise    204
Name: count, dtype: int64

In [45]:
df[df['brand']=='Noise']['category'].value_counts()

category
True Wireless Earbuds    150
Neckband                  33
Headphones                18
Wired Earphones            3
Name: count, dtype: int64

In [46]:
df[df['brand']=='boAt']['category'].value_counts()

category
True Wireless Earbuds    210
Neckband                  83
Headphones                65
Wired Earphones           40
Name: count, dtype: int64

In [36]:
df.columns

Index(['brand', 'product_name', 'handle', 'category', 'product_type',
       'sale_price_min_inr', 'sale_price_max_inr', 'mrp_inr',
       'discount_percent', 'num_variants', 'colors', 'skus',
       'in_stock_variants', 'tags_raw', 'features_raw', 'specs_raw_json',
       'description_raw', 'product_id'],
      dtype='str')

In [43]:
raw_copy.columns

Index(['brand', 'product_name', 'handle', 'product_url', 'category',
       'product_type', 'collection_source', 'vendor', 'sale_price_min_inr',
       'sale_price_max_inr', 'mrp_inr', 'discount_percent', 'num_variants',
       'colors', 'skus', 'in_stock_variants', 'tags_raw', 'features_raw',
       'specs_raw_json', 'description_raw', 'image_url', 'created_at',
       'updated_at', 'published_at', 'product_id'],
      dtype='str')

In [47]:
drop_cols = [
    "product_url",
    "collection_source",
    "image_url"
]

df = df.drop(columns=drop_cols)

In [48]:
df.columns

Index(['brand', 'product_name', 'handle', 'category', 'product_type', 'vendor',
       'sale_price_min_inr', 'sale_price_max_inr', 'mrp_inr',
       'discount_percent', 'num_variants', 'colors', 'skus',
       'in_stock_variants', 'tags_raw', 'features_raw', 'specs_raw_json',
       'description_raw', 'created_at', 'updated_at', 'published_at',
       'product_id'],
      dtype='str')

In [49]:
df['brand'].value_counts()

brand
boAt     398
Noise    204
Name: count, dtype: int64

In [50]:
df['product_name'].value_counts()

product_name
Noise Airwave Pro Neckband Earphones - ABHI Marketplace                                                             2
Airwave Max 3 Wireless Headphone                                                                                    1
Airwave Max 3 Wireless Headphone - ABHI Marketplace                                                                 1
Airwave Max 3 Wireless Headphone - Deal                                                                             1
Airwave Max 4 Wireless Headphone                                                                                    1
                                                                                                                   ..
boAt Nirvanaa DUO | Stylish Hawk-Inspired Design Wired Earphones with 10mm Dynamic Dual Driver, Super Extra Bass    1
boAt Nirvanaa Uno | Wired Earphone with Mic, 8mm Drivers, Superior Coated Cable, 3.5mm Angled Jack, Secure Fit      1
Noise Chord 100 Type-C Wired Earphone                                                                               1
Noise Chord 200 Type-C Wired Earphone                                                                               1
Noise Chord 200 Wired Earphone                                                                                      1
Name: count, Length: 601, dtype: int64

In [51]:
df['handle'].value_counts()

handle
noise-airwave-max-three-wireless-headphone           1
airwave-max-3-wireless-headphone-abhi-marketplace    1
airwave-max-3-wireless-headphone-deal                1
noise-4-wireless-headphone                           1
airwave-max-4-wireless-headphone-abhi-marketplace    1
                                                    ..
nirvanaa-duo                                         1
nirvana-uno                                          1
noise-chord-100-type-c-wired-earphone                1
noise-chord-200-type-c-wired-earphone                1
noise-chord-200-wired-earphone                       1
Name: count, Length: 602, dtype: int64

In [52]:
df['category'].value_counts()

category
True Wireless Earbuds    360
Neckband                 116
Headphones                83
Wired Earphones           43
Name: count, dtype: int64

In [53]:
df['product_type'].value_counts()

product_type
TWS                    204
Wireless Earbuds       144
Rockerz In-Ear          78
Rockerz                 63
Bassheads               44
Wireless Earphones      33
Wireless Headphones     24
BH-onear                 8
Wired Earphones          3
VAS                      1
Name: count, dtype: int64

In [54]:
df['vendor'].value_counts()

vendor
boAtlifestylein    395
Noise              191
Gonoise             13
boAt Lifestyle       3
Name: count, dtype: int64

In [55]:
df.drop(columns='vendor',inplace=True)

In [58]:
df['sale_price_max_inr'].value_counts()
df['sale_price_max_inr'].isna().sum()

np.int64(0)

In [57]:
df['sale_price_min_inr'].value_counts()

sale_price_min_inr
999.0     65
1499.0    58
1099.0    47
1599.0    37
1299.0    33
          ..
5990.0     1
4599.0     1
5399.0     1
3599.0     1
419.0      1
Name: count, Length: 81, dtype: int64

In [59]:
df.columns

Index(['brand', 'product_name', 'handle', 'category', 'product_type',
       'sale_price_min_inr', 'sale_price_max_inr', 'mrp_inr',
       'discount_percent', 'num_variants', 'colors', 'skus',
       'in_stock_variants', 'tags_raw', 'features_raw', 'specs_raw_json',
       'description_raw', 'created_at', 'updated_at', 'published_at',
       'product_id'],
      dtype='str')

In [69]:
df['created_at'].value_counts().sort_index()

created_at
2019-01-02T15:43:19+05:30    1
2019-03-09T20:03:12+05:30    1
2019-03-11T10:50:17+05:30    1
2019-03-11T10:56:34+05:30    1
2019-03-11T10:59:09+05:30    1
                            ..
2026-08-12T13:06:28+05:30    1
2026-08-18T17:54:02+05:30    1
2026-08-20T00:27:03+05:30    1
2026-08-27T17:25:05+05:30    1
2026-09-04T12:32:04+05:30    1
Name: count, Length: 599, dtype: int64

In [72]:
df[df['brand']=='boAt']['created_at'].sort_values()

598    2019-01-02T15:43:19+05:30
455    2019-03-09T20:03:12+05:30
207    2019-03-11T10:50:17+05:30
567    2019-03-11T10:56:34+05:30
568    2019-03-11T10:59:09+05:30
                 ...
508    2026-08-09T23:24:51+05:30
326    2026-08-12T13:06:28+05:30
558    2026-08-18T17:54:02+05:30
510    2026-08-27T17:25:05+05:30
226    2026-09-04T12:32:04+05:30
Name: created_at, Length: 398, dtype: str

In [75]:
df[df['brand']=='Noise']['created_at'].sort_values()

62     2020-11-25T12:53:30+05:30
48     2020-11-30T09:51:51+05:30
46     2020-11-30T10:18:51+05:30
39     2021-04-08T19:02:10+05:30
66     2021-05-11T15:36:29+05:30
                 ...
59     2026-08-10T17:44:07+05:30
7      2026-08-20T00:27:03+05:30
599                          NaN
600                          NaN
601                          NaN
Name: created_at, Length: 204, dtype: str

In [76]:
df.columns

Index(['brand', 'product_name', 'handle', 'category', 'product_type',
       'sale_price_min_inr', 'sale_price_max_inr', 'mrp_inr',
       'discount_percent', 'num_variants', 'colors', 'skus',
       'in_stock_variants', 'tags_raw', 'features_raw', 'specs_raw_json',
       'description_raw', 'created_at', 'updated_at', 'published_at',
       'product_id'],
      dtype='str')

In [83]:
df['handle']

0             noise-airwave-max-three-wireless-headphone
1      airwave-max-3-wireless-headphone-abhi-marketplace
2                  airwave-max-3-wireless-headphone-deal
3                             noise-4-wireless-headphone
4      airwave-max-4-wireless-headphone-abhi-marketplace
                             ...
597                                         nirvanaa-duo
598                                          nirvana-uno
599                noise-chord-100-type-c-wired-earphone
600                noise-chord-200-type-c-wired-earphone
601                       noise-chord-200-wired-earphone
Name: handle, Length: 602, dtype: str

In [82]:
pd.set_option("display.max_colwidth", None)

In [86]:
for i in range(600):
    print(df["handle"].iloc[i])

noise-airwave-max-three-wireless-headphone
airwave-max-3-wireless-headphone-abhi-marketplace
airwave-max-3-wireless-headphone-deal
noise-4-wireless-headphone
airwave-max-4-wireless-headphone-abhi-marketplace
airwave-max-4-wireless-headphone-unidays-exclusive
airwave-max-4-wireless-headphone-copy
noise-airwave-max-2-wireless-headphone
noise-airwave-max-5-headphone-abhi-marketplace
noise-airwave-max-5-headphone-unidays
noise-airwave-max-6-headphone-abhi-marketplace
noise-airwave-max-xr-wireless-headphone
noise-airwave-max-xr-wireless-headphone-abhi-marketplace
noise-clutch-hp-p01-gaming-headphone
noise-powr-wireless-headphone
noise-two-wireless-headphone
noise-two-wireless-headphone-copy
noise-kableone-wireless-headphone-exclusive
noise-bravo-bt-neckband-earphones-with-mic
noise-crest-bluetooth-wireless-neckband-earphones
noise-airwave-crest-bluetooth-wireless-neckband-earphones-abhi-marketplace
noise-airwave-neckband-earphones
noise-airwave-neckband-earphones-abhi-marketplace
noise-airwave-neckband-earphones-telegram-exclusive
noise-airwave-pro-neckband-earphones
noise-airwave-pro-neckband-earphones-abhi-marketplace-1
noise-airwave-pro-neckband-earphones-abhi-marketplace
noise-blaze-bluetooth-wireless-neckband-earphones-with-mic-os
noise-bravo-neckband-earphones-with-mic-partner-deal-store
noise-bravo-neckband-earphones-with-mic-partner-exclusive
noise-buds-neo-truly-wireless-earbuds
noise-buds-neo-truly-wireless-earbuds-black
noise-buds-neo-truly-wireless-earbuds-green
noise-buds-neo-truly-wireless-earbuds-grey
noise-buds-neo-truly-wireless-earbuds-wine
noise-buds-vs501-truly-wireless-bluetooth-earbuds
noise-buds-vs501-truly-wireless-bluetooth-earbuds-forest-green
noise-buds-vs501-truly-wireless-bluetooth-earbuds-pebble-black
noise-combat-bt-wireless-gaming-neckband-earphones-with-mic
noise-flair-touch-bt-wireless-neckband
noise-flair-xl-bt-wireless-neckband
noise-nerve-bt-neckband-earphones-with-mic
noise-nerve-neckband-earphones-with-mic-partner-deal-store
noise-nerve-pro-bt-neckband-earphones-with-mic
noise-sense-bt-neckband-earphones-with-mic
noise-tune-active-pro-bt-neckband-earphones
noise-tune-elite-sport-bt-neckband-earphones-with-mic
noise-tune-lite-bluetooth-wireless-neckband-earphones-with-mic-os
noise-tune-sport-2-bt-neckband-earphones-with-mic
noise-xtreme-neckband-earphones-with-mic
test-order-api
noise-buds-combat-z-wireless-earbuds-ondc-partner-exclusive
buds-n1-truly-wireless-earbuds
buds-uno-truly-wireless-earbuds
noise-buds-vs102-elite-truly-wireless-earbuds-copy
noise-buds-x-anc-truly-wireless-earbuds
buds-x-anc-truly-wireless-earbuds-abhi-marketplace
noise-alt-buds-s-truly-wireless-bluetooth-earbuds-chosen-orange
noise-alt-buds-s-truly-wireless-bluetooth-earbuds
noise-alt-buds-s-truly-wireless-bluetooth-earbuds-super-saver
noise-alt-buds-truly-wireless-bluetooth-earbuds
noise-alt-clip
noise-air-buds-truly-wireless-earbuds
noise-air-buds-2-truly-wireless-earbuds
noise-air-buds-3-truly-wireless-earbuds
noise-air-buds-6-truly-wireless-earbuds
noise-air-buds-mini-truly-wireless-earbuds
noise-air-buds-mini-2-truly-wireless-earbuds
noise-air-buds-nano-truly-wireless-earbuds
noise-air-buds-pro-2-active-noise-cancellation
noise-air-buds-pro-3-earbuds
noise-air-buds-pro-4-earbuds
noise-air-buds-pro-4-earbuds-abhi-marketplace
noise-air-buds-pro-6-earbuds
noise-air-buds-pro-se-earbuds
noise-air-buds-plus-truly-wireless-earbuds
noise-air-clips-2-ows-open-ear-headphone
noise-air-clips-ows-open-ear-headphone
noise-air-clips-ows-open-ear-headphone-abhi-marketplace
noise-air-clips-pro-ows-open-ear-headphone
noise-air-clips-pro-ows-open-ear-headphone-abhi-marketplace
noise-air-clips-pro-ows-open-ear-headphone-deal
noise-airwave-max-5-headphone
noise-airwave-max-5-headphone-limited-edition-deal
noise-airwave-max-6-headphone
noise-alt-buds-open-truly-wireless-bluetooth-earbuds
noise-aura-buds-truly-wireless-earbuds
noise-aura-buds-truly-wireless-earbuds-ondc-partner-exclusive
noise-beads-truly-wireless-earbuds
noise-buds-ace-truly-wireless-earbuds
noise-buds-aero-truly-wireless-earbuds
noise-buds-apex-truly-wireless-bluetooth-earbuds
noise-buds-apex-truly-wireless-bluetooth-earbuds-blue-tokai
noise-buds-apex-truly-wireless-bluetooth-earbuds-cloud-grey
noise-buds-combat-truly-wireless-earbuds
noise-buds-combat-x-truly-wireless-earbuds
noise-buds-combat-z-wireless-earbuds
noise-buds-connect-2-truly-wireless-earbuds
noise-buds-connect-3-truly-wireless-earbuds
noise-buds-connect-truly-wireless-earbuds
noise-buds-e1-truly-wireless-earbuds
noise-buds-evoke-truly-wireless-earbuds
noise-buds-evoke-truly-wireless-earbuds-abhi-marketplace
noise-buds-explore-truly-wireless-earbuds
noise-buds-f1-truly-wireless-bluetooth-earbuds
noise-buds-f1-truly-wireless-bluetooth-earbuds-abhi-marketplace
noise-buds-mvp102-truly-wireless-earbuds
noise-buds-marine-truly-wireless-bluetooth-earbuds
noise-buds-marine-truly-wireless-bluetooth-earbuds-abhi-marketplace
noise-buds-mini-truly-wireless-earbuds
noise-buds-mini-truly-wireless-earbuds-abhi-marketplace
noise-buds-n1-pro-truly-wireless-earbuds
noise-buds-n1-pro-truly-wireless-earbuds-abhi-marketplace
noise-buds-n1-pro-truly-wireless-earbuds-copy
noise-buds-n1-pro-truly-wireless-earbuds-black
noise-buds-n1-pro-truly-wireless-earbuds-super-saver
noise-buds-n1-pro-truly-wireless-earbuds-unidays
noise-buds-n1-truly-wireless-earbuds
noise-buds-n1-truly-wireless-earbuds-abhi-marketplace
noise-buds-n1-truly-wireless-earbuds-calm-beige
noise-buds-n1-truly-wireless-earbuds-black
noise-buds-n1-truly-wireless-earbuds-forest-green-1
noise-buds-n1-truly-wireless-earbuds-healthifyme-exclusive
noise-buds-n1-truly-wireless-earbuds-ice-blue
noise-buds-n2-pro-truly-wireless-bluetooth-earbuds
noise-buds-n2-pro-truly-wireless-bluetooth-earbuds-abhi-marketplace
noise-buds-nero-truly-wireless-earbuds
noise-buds-play-truly-wireless-earbuds
noise-buds-play-truly-wireless-earbuds-abhi-marketplace
noise-buds-r1-truly-wireless-earbuds
noise-buds-trance-2-wireless-earbuds
noise-buds-trance-2-wireless-earbuds-copy
noise-buds-trance-wireless-earbuds
noise-buds-trance-wireless-earbuds-abhi-marketplace
noise-buds-trance-wireless-earbuds-copy
noise-buds-trance-wireless-earbuds-ondc-partner-exclusive
noise-buds-trooper-truly-wireless-earbuds
noise-buds-uno-truly-wireless-earbuds
noise-buds-vs102-elite-truly-wireless-earbuds
noise-buds-vs102-neo-truly-wireless-earbuds
noise-buds-vs102-neo-truly-wireless-earbuds-abhi-marketplace
noise-buds-vs102-neo-truly-wireless-earbuds-ondc-partner-exclusive
noise-buds-vs102-pro-truly-wireless-earbuds
noise-buds-vs102-pro-truly-wireless-earbuds-black
noise-buds-vs102-pro-truly-wireless-earbuds-blue-tokai
noise-buds-vs102-truly-wireless-bt-earbuds
noise-buds-vs102-truly-wireless-earbuds-abhi-marketplace
vs-102-truly-wireless-earbuds-deal
noise-buds-vs102-truly-wireless-earbuds-copy
noise-buds-vs102-truly-wireless-earbuds-pearl-white
noise-buds-vs102-truly-wireless-earbuds-ondc-partner-exclusive
noise-buds-vs102-plus
noise-buds-vs102-truly-wireless-earbuds-blue-tokai
noise-buds-vs103-pro-truly-wireless-earbuds
noise-buds-vs103-truly-wireless-bt-earbuds
noise-buds-vs104-max-truly-wireless-earbuds
noise-buds-vs104-max-truly-wireless-earbuds-ondc-partner-exclusive
noise-buds-vs104-pro-truly-wireless-earbuds
noise-buds-vs104-truly-wireless-bt-earbuds
noise-buds-vs106-truly-wireless-earbuds
noise-buds-vs106-truly-wireless-earbuds-ondc-partner-exclusive
noise-buds-vs201-truly-wireless-bt-earbuds
noise-buds-vs202-truly-wireless-bt-earbuds
noise-buds-vs204-truly-wireless-earbuds
noise-buds-vs303-truly-wireless-bt-earbuds
buds-vs304
noise-buds-vs401-truly-wireless-earbuds-ondc-partner-exclusive
noise-buds-vs401-truly-wireless-earbuds
noise-buds-vs402-truly-wireless-earbuds
noise-buds-vs402-truly-wireless-earbuds-neon-white
noise-buds-vs402-truly-wireless-earbuds-ondc-partner-exclusive
noise-buds-vs404-truly-wireless-earbuds
noise-buds-vs404-truly-wireless-earbuds-ondc-partner-exclusive
noise-buds-vs601-truly-wireless-bluetooth-earbuds
noise-buds-vs601-truly-wireless-bluetooth-earbuds-abhi-marketplace
noise-buds-vector-truly-wireless-earbuds
noise-buds-vector-truly-wireless-earbuds-abhi-marketplace
noise-buds-venus-truly-wireless-earbuds
noise-buds-venus-truly-wireless-earbuds-ondc-partner-exclusive
noise-buds-verve-2-truly-wireless-earbuds
noise-buds-verve-truly-wireless-earbuds
buds-x-prime-truly-wireless-earbuds
noise-buds-x-prime-truly-wireless-earbuds-ondc-partner-exclusive
noise-buds-x-ultra-truly-wireless-bluetooth-earbuds
noise-buds-x2-truly-wireless-bluetooth-earbuds
noise-buds-x2-truly-wireless-bluetooth-earbuds-copy
noise-buds-xero-truly-wireless-earbuds
noise-go-buds-truly-wireless-earbuds
noise-master-buds-2-truly-wireless-bluetooth-earbuds
noise-master-buds-2-truly-wireless-bluetooth-earbuds-abhi-marketplace
noise-master-buds-2-truly-wireless-bluetooth-earbuds-ref
noise-master-buds-max-wireless-headphone
noise-master-buds-max-wireless-headphone-abhi-marketplace
noise-master-buds-max-wireless-headphone-ref
noise-master-buds-truly-wireless-earbuds
noise-master-buds-truly-wireless-earbuds-special-edition
noise-pop-buds-truly-wireless-earbuds
noise-pure-pods-2-open-ear-headphones
noise-pure-pods-open-ear-headphones
noise-pure-pods-open-ear-headphones-abhi-marketplace
noise-view-buds-truly-wireless-earbuds
bassheads-900-c-pro
bassheads-900-pro-wired-headphone
bassheads-901-pro
bassheads-910
boat-nirvana-eutopia-dhruv-kapoor-edition
rockerz-450
bassheads-152
bassheads-900
bassheads-950v2
im-1000d
boat-immortal-1300
immortal-200
https-www-boat-lifestyle-com-products-boat-immortal-300-gaming-headphone
immortal-400
immortal-700
nirvana-751-anc-headphone
nirvana-eutopia-headphone
nirvana-1007-anc
nirvana-717-anc
boat-rockerz-370-pro-wireless-headphones-with-40-hours-playback-voice-assistant-boat-signature-sound-beast™️-mode
rockerz-370
rockerz-390-v2
rockerz-400-pro-earphone
rockerz-400
rockerz-410
boat-rockerz-421-gen-2
rockerz-425-wireless-bluetooth-headphone
rockerz-430-headphone
rockerz-450-batman-edition
450-black-panther
450-captain-america
rockerz-450-dc-edition-wireless-headphone
rockerz-450-iron-man-bluetooth-headphone
rockerz-450-pro
rockerz-450-superman-edition
rockerz-450-wonder-woman-dc-edition
rockerz-450r-wireless-bluetooth-headphone
boat-rockerz-460-wireless-headphone-naruto-series
boat-rockerz-460-wireless-headphone
rockerz-480-wireless-headphone
rockerz-510
boat-rockerz-512-anc
rockerz-518
boat-rockerz-550-sunburn-edition
rockerz-550
rockerz-551-anc-pro-wireless-headphone
rockerz-551-anc-noise-cancelling-headphone
rockerz-558-sunburn-edition-wireless-headphone
rockerz-558-wireless-headphone
rockerz-560
rockerz-600-kkr-edition
rockerz-600
rockerz-610
rockerz-650-pro
boat-rockerz-650-sunburn-edition
rockerz-650-wireless-headphone
rockerz-660
boat-rockerz-plus-440
boat-rockerz-plus-450-anc
rockerz-plus-550-anc
boat-rockerz-plus-550
boat-rockerz-prime-415
rockerz-trendz-wireless-headphones
rockid-rush-kids-bluetooth-headphone
boat-sailor-play
rockerz-215
rockerz-255-arc-wireless-bluetooth-neckband
rockerz-255r
rockerz-265-v2
rockerz-330-anc-noise-cancelling-earphones
rockerz-333-anc-wireless-neckband-with-noise-cancelling-feature
boat-100-wireless
boat-102-wireless
boat-103-wireless
nirvana-525-anc-earphone
rockerz-103-pro-in-ear-wireless-earphones
rockerz-103-v2-pro-bluetooth-earbuds
rockerz-109-wireless-earphone
rockerz-110
rockerz-111-neckband
rockerz-112-wireless-neckband
boat-rockerz-113-wireless-neckband-with-beast™-mode
rockerz-150-pro-bluetooth-neckband
rockerz-185-pro-wireless-neckband
rockerz-185
rockerz-195v2-pro-wireless-earphone
rockerz-195
boat-rockerz-200
rockerz-202-neckband
boat-rockerz-203-wireless-neckband
boat-rockerz-205-pro
rockerz-210-anc-headphone
rockerz-235-pro
rockerz-235-v2
rockerz-235v2-made-in-india
boat-rockerz-238-pro-wireless-bluetooth-neckband-with-up-to-20-hours-playback-beast-mode-enx-technology
rockerz-238
rockerz-245-pro-wireless-earphones
rockerz-245-v2-pro-bluetooth-earphone
rockerz-245-v2
rockerz-255-anc-earphone
rockerz-255-kkr
rockerz-255-max-large-playback-neckband
boat-rockerz-255-neo
rockerz-255-pro
boat-rockerz-255-pro-plus
rockerz-255-touch-long-playback-earphone
rockerz-255-z-plus-neckband
rockerz-255
rockerz-255f
rockerz-258-pro
boat-rockerz-258-pro
rockerz-260
boat-rockerz-260-bluetooth-earphones
rockerz-261-pro
rockerz-261
rockerz-275-v2
boat-rockerz-301-anc
boat-rockerz-330-pro
rockerz-330
rockerz-333-pro
rockerz-333
rockerz-333-wireless-earphone
rockerz-335
rockerz-338-wireless-earphone
boat-rockerz-351-anc
boat-rockerz-355-wireless-neckband
boat-rockerz-371
rockerz-375
boat-wireless-rockerz-378
rockerz-385-v2
rockerz-411-wireless-headphones
boat-rockerz-412-wireless-headphones
boat-rockerz-413-wireless-headphones
boat-rockerz-421-wireless-headphones
rockerz-80-pro-wireless-bluetooth-neckband
boat-rockerz-apex-wireless-neckband
rockerz-bliss-wireless-neckband
rockerz-bold-wireless-neckband
rockerz-enticer-wireless-earphone
boat-rockerz-prime-205
rockerz-prime-255z-wireless-neckband
boat-rockerz-strive
boat-rockerz-summit-wireless-earphone-with-30h-playback
rockerz-trinity-gen-2-wireless-neckband
boat-rockerz-trinity-grande-wireless-neckband-with-150-hours-playback-ai-enx™-tech-dual-eqs-beast™-mode-copy
rockerz-trinity-wireless-neckband
boat-rockerz-zen-anc-wireless-neckband-earphones
airdopes-131-dc-edition-earbuds-online
airdopes-138-dc-edition-wireless-earbuds
airdopes-601-anc
bassheads-162-v2
bassheads-55
bassheads-90c
nirvana-eutopia-2-anc
boat-nirvana-ivy-dhruv-kapoor-edition
do-not-deletetest-ad-131-cover
airdopes-100-wireless-earbuds
airdopes-101-made-in-india
airdopes-101v2-wireless-earbuds
boat-airdopes-111
airdopes-111v2-wireless-earbuds
boat-airdopes-113-wireless-gaming-earbuds
airdopes-115-wireless-bluetooth-earbuds
boat-airdopes-118-earbuds-with-13mm-drivers-beast™-mode-for-gamers-enx™-technology
airdopes-120-wireless-earbuds
boat-airdopes-121-pro-earbuds-with-easy-touch-control
airdopes-121-pro-plus-earbuds
airdopes-121-v2
airdopes-121v2-plus-earbuds
airdopes-125-wireless-earbuds
airdopes-131-batman-dc-edition
131-captain-america
airdopes-131-elite-anc-earbuds
airdopes-131-gen-2-true-wireless-earbuds
airdopes-131-kkr-edition
boat-airdopes-131-pro-true-wireless-earbuds
airdopes-131-pro-buds
airdopes-131-rcb-edition
airdopes-131-superman-edition
airdopes-131-wonder-woman-dc-edition
airdopes-131
boat-airdopes-138-gen-2
airdopes-138-pro-bluetooth-earbuds
boat-airdopes-138-wireless-earbuds-1
airdopes-141-anc-earbuds
airdopes-141-elite-anc-wireless-earbuds
airdopes-141-gen2-wireless-earbuds
airdopes-141-neo-wireless-earbuds
airdopes-141-pro-buds
boat-airdopes-141-pro-earbuds
airdopes-141
boat-airdopes-141-gen-2-wireless-earbuds-with-48-hours-playback-beast™-mode-dual-eqs-enx™-tech-copy
boat-airdopes-148
airdopes-155-long-playback-earbuds
boat-airdopes-161-metallic
airdopes-161-anc-elite-earbuds
airdopes-161-anc-wireless-earbuds
airdopes-161-deadpool-edition
airdopes-161-pro-buds
airdopes-161-pro-wireless-bluetooth-earbuds
airdopes-161-thor-edition
airdopes-161
boat-airdopes-163-wireless-earbuds
boat-airdopes-170-wireless-earbuds
airdopes-171
airdopes-172-wireless-earbuds
airdopes-173
boat-airdopes-175
airdopes-181-pro-wireless-earbuds
airdopes-181-pro-bluetooth-earbuds
boat-airdopes-181
boat-airdopes-183-wireless-bluetooth-earbuds
airdopes-190-wireless-earbuds
boat-airdopes-191-anc-wireless-earbuds-with-anc-up-to-32db-quad-mics-enx™-tech-bluetooth-v5-3
boat-airdopes-191g-true-wireless-gaming-earbuds
boat-airdopes-192
airdopes-200-plus-large-playback-earbuds
airdopes-201
airdopes-207-wireless-earbuds
boat-airdopes-212-wireless-earbuds
airdopes-213-wireless-earbuds
airdopes-219-wireless-earbuds
airdopes-280-anc-wireless-earbuds
airdopes-281-pro
airdopes-281
boat-airdopes-283-true-wireless-earbuds
airdopes-300-large-playback-earbuds
airdopes-301
airdopes-311-pro-wireless-earbuds
boat-airdopes-311v2
airdopes-313-wireless-earbuds
airdopes-381-mki-wireless-earbuds
boat-airdopes-381-sunburn-edition
airdopes-381
boat-airdopes-383-sunburn-edition
airdopes-383
airdopes-391
airdopes-393-anc-bluetooth-earbuds
airdopes-402
boat-airdopes-408-wireless-earbuds
boat-airdopes-411-anc-netflix-stream-edition
airdopes-411-anc
boat-airdopes-413-anc
airdopes-418-anc-noise-cancelling-earbuds-with-10mm-drivers-asaptm-charge-technology-up-to-25db-anc-enx-technology-17-5-hours-playback
airdopes-431
boat-airdopes-433-truly-wireless-earbuds
airdopes-441-kkr-edition
airdopes-441-pro-dc-edition
airdopes-441-pro
boat-airdopes-441-sunburn-edition
airdopes-441
airdopes-441-made-in-india
airdopes-443
airdopes-451v2
airdopes-452
airdopes-458
airdopes-461
airdopes-491
airdopes-500-anc
airdopes-501-anc
airdopes-511-v2
airdopes-621
airdopes-641
boat-airdopes-71-gen-2
airdopes-71-long-playback-earbuds
airdopes-711
airdopes-800-hi-def
boat-airdopes-800-wireless-earbuds-with-dolby-audio-asap™-charge-iwp™-tech
airdopes-91-prime-long-playback-earbuds
airdopes-91-long-playback-earbuds
airdopes-ace-gen-2-true-wireless-earbuds
airdopes-ace
airdopes-alpha-deadpool-edition
boat-airdopes-alpha-gen-2-true-wireless-earbuds
airdopes-alpha-true-wireless-earbuds
airdopes-atom-81-pro-long-playback-earbuds
airdopes-atom-81-long-playback-earbuds
boat-airdopes-atom-83-earbuds
airdopes-beat-wireless-earbuds
airdopes-bliss-wireless-anc-earbuds
airdopes-crude-wireless-earbuds
airdopes-drift-wireless-earbuds
airdopes-flex-454-noise-cancelling-earbud
airdopes-fuel-premium-wireless-earbuds
airdopes-genesis-large-playback-earbuds
airdopes-hype-long-playback-earbuds
airdopes-joy-v2
airdopes-joy-wireless-earbuds
airdopes-kick-long-playback-earbuds
airdopes-loop
airdopes-max-wireless-earbuds
boat-airdopes-plus-214
boat-airdopes-plus-222
boat-airdopes-plus-223
boat-airdopes-plus-224
boat-airdopes-plus-311-wireless-earbuds
airdopes-plus-318-bluetooth-wireless-earbuds
boat-airdopes-plus-421-anc
airdopes-prime-412-wireless-earbuds
boat-airdopes-prime-413
airdopes-prime-511-wireless-earbuds
boat-airdopes-prime-512
airdopes-prime-513-anc-wireless-earbuds
airdopes-prime-700-anc-wireless-earbuds
airdopes-prime-701-anc-wireless-earbuds
boat-airdopes-prime-800d
boat-airdopes-prime-supreme
boat-airdopes-primo-with-45-hours-playback
boat-airdopes-proclip-ss-edition
airdopes-proclip
boat-airdopes-progear
boat-airdopes-pulse-wireless-earbuds
airdopes-sonik-long-playback-earbuds
boat-airdopes-stride
airdopes-supreme-long-playback-earbuds
airdopes-ultra-plus-large-playback-earbuds
airdopes-ultra-pro-long-playback-earbuds
airdopes-unity-anc-bluetooth-earbuds
airdopes-zing-long-playback-earbuds
test-page-boat-crest-ai
immortal-100-gaming-earbuds
immortal-101-true-wireless-gaming-earbuds
immortal-111-gaming-earbuds
boat-immortal-121-bluetooth-gaming-earbuds
immortal-125-gaming-earbuds
immortal-128-gaming-earbuds
boat-immortal-131-wireless-gaming-earbuds
airdopes-immortal-141-gaming-earbuds
immortal-150-gaming-earbuds
immortal-158-gaming-earbuds
immortal-161-gaming-earbuds
immortal-170-gaming-earbuds
immortal-171-wireless-gaming-earbuds
immortal-181-gaming-earbuds
immortal-201-gaming-earbuds
immortal-airspeed-pro-gaming-earbuds
immortal-katana-blade-gaming-earbuds
immortal-katana-2-0-blade-gaming-earbuds
nirvana-crown-tws-earbuds
nirvana-crystl-wireless-earbuds
nirvana-ion-anc-special-edition-earbuds
boat-nirvana-ion-anc-limited-edition-wireless-earbuds-with-active-noise-cancellation-enx™-technology-120-hours-playback-beast™-mode
nirvana-ion-anc-pro-earbuds
nirvana-ion-anc-earbuds
nirvana-ion-bluetooth-wireless-earbuds
nirvana-iris-anc-earbuds
nirvana-ivy-pro-wireless-earbuds
nirvana-ivy-wireless-earbuds
boat-nirvana-lucid
nirvana-nebula-anc-earbuds
boat-nirvana-space-wireless-earbuds-with-anc
nirvana-x-wireless-earbuds
boat-nirvana-zenith-pro-ss-edition
nirvana-zenith-pro-wireless-earphones
nirvana-zenith-anc-earbuds
boat-rockerz-650-dc-edition-earbuds
boat-crest-ai
bassheads-100-make-in-india
bassheads-100
bassheads-100-c-wired-earphone
bassheads-102
bassheads-103
bassheads-110
bassheads-122

In [91]:
df[df['handle'].str.contains('airwave-max-4-wireless-headphone')]

   brand                                          product_name                                              handle    category         product_type  sale_price_min_inr  sale_price_max_inr  mrp_inr  discount_percent  num_variants                                     colors                                                                            skus  in_stock_variants                                                                                             tags_raw                                                                                         features_raw specs_raw_json                                                                                      description_raw                 created_at                 updated_at               published_at     product_id
4  Noise   Airwave Max 4 Wireless Headphone - ABHI Marketplace   airwave-max-4-wireless-headphone-abhi-marketplace  Headphones  Wireless Headphones              2499.0              2499.0   5999.0              58.3             3  Carbon Black | Calm Beige | Tropical Teal                          AUD-HDPHN-4-BLK | AUD-HDPHN-4-BEIGE | AUD-HDPHN-4-TEAL                  2  4headphone | _ct-product-type-audio-device_ | _sms-ct-Airwave Max 4 Wireless Headphone | _title-...  4headphone | _ct-product-type-audio-device_ | _sms-ct-Airwave Max 4 Wireless Headphone | _title-...            NaN  Experience exceptional audio performance with the Noise Airwave Max 4 Wireless Headphones – engi...  2026-07-29T12:50:01+05:30  2026-09-23T22:08:21+05:30  2026-07-29T12:54:00+05:30  7715132342359
5  Noise  Airwave Max 4 Wireless Headphone - Unidays Exclusive  airwave-max-4-wireless-headphone-unidays-exclusive  Headphones  Wireless Headphones              2599.0              2599.0   5999.0              56.7             3  Carbon Black | Calm Beige | Tropical Teal  AUD-HDPHN-4-BLK-UNIDAYS | AUD-HDPHN-4-BEIGE-UNIDAYS | AUD-HDPHN-4-TEAL-UNIDAYS                  3  4headphone | _ct-product-type-audio-device_ | _sms-ct-Airwave Max 4 Wireless Headphone | _title-...  4headphone | _ct-product-type-audio-device_ | _sms-ct-Airwave Max 4 Wireless Headphone | _title-...            NaN  Buy Airwave Max 4 Wireless Headphone that comes with dual device pairing, up to 70 hours of play...  2026-01-07T13:02:27+05:30  2026-09-23T22:08:21+05:30  2026-01-09T12:55:40+05:30  7556337172567
6  Noise                Airwave Max 4 Wireless Headphone- Deal               airwave-max-4-wireless-headphone-copy  Headphones  Wireless Headphones              1599.0              1599.0   5999.0              73.3             3  Carbon Black | Calm Beige | Tropical Teal                          AUD-HDPHN-4-BLK | AUD-HDPHN-4-BEIGE | AUD-HDPHN-4-TEAL                  2  4headphone | _ct-product-type-audio-device_ | _sms-ct-Airwave Max 4 Wireless Headphone | _title-...  4headphone | _ct-product-type-audio-device_ | _sms-ct-Airwave Max 4 Wireless Headphone | _title-...            NaN  Buy Airwave Max 4 Wireless Headphone that comes with dual device pairing, up to 70 hours of play...  2025-11-05T13:10:47+05:30  2026-09-23T22:08:21+05:30  2025-11-05T13:22:13+05:30  7508291977303

In [90]:
pd.set_option("display.max_columns", None)
pd.set_option("display.width", 2000)
pd.set_option("display.max_colwidth", 100)

In [92]:
df[
    df["product_name"].str.contains(
        "Airwave Max 4",
        case=False,
        na=False
    )
][[
    "product_name",
    "handle",
    "sale_price_min_inr",
    "sale_price_max_inr",
    "mrp_inr",
    "num_variants",
    "colors",
    "skus"
]].to_string(index=False)

'                                        product_name                                             handle  sale_price_min_inr  sale_price_max_inr  mrp_inr  num_variants                                    colors                                                                           skus\n                    Airwave Max 4 Wireless Headphone                         noise-4-wireless-headphone              1999.0              1999.0   5999.0             3 Carbon Black | Calm Beige | Tropical Teal                         AUD-HDPHN-4-BLK | AUD-HDPHN-4-BEIGE | AUD-HDPHN-4-TEAL\n Airwave Max 4 Wireless Headphone - ABHI Marketplace  airwave-max-4-wireless-headphone-abhi-marketplace              2499.0              2499.0   5999.0             3 Carbon Black | Calm Beige | Tropical Teal                         AUD-HDPHN-4-BLK | AUD-HDPHN-4-BEIGE | AUD-HDPHN-4-TEAL\nAirwave Max 4 Wireless Headphone - Unidays Exclusive airwave-max-4-wireless-headphone-unidays-exclusive              2599.0              2599.0   5999.0             3 Carbon Black | Calm Beige | Tropical Teal AUD-HDPHN-4-BLK-UNIDAYS | AUD-HDPHN-4-BEIGE-UNIDAYS | AUD-HDPHN-4-TEAL-UNIDAYS\n              Airwave Max 4 Wireless Headphone- Deal              airwave-max-4-wireless-headphone-copy              1599.0              1599.0   5999.0             3 Carbon Black | Calm Beige | Tropical Teal                         AUD-HDPHN-4-BLK | AUD-HDPHN-4-BEIGE | AUD-HDPHN-4-TEAL'

In [93]:
df["base_product"] = (
    df["handle"]
    .str.replace(
        r"-(abhi-marketplace|unidays-exclusive|deal|copy)$",
        "",
        regex=True
    )
)

In [97]:
df['base_product'].value_counts()

base_product
airwave-max-4-wireless-headphone              3
noise-air-clips-pro-ows-open-ear-headphone    3
noise-buds-n1-pro-truly-wireless-earbuds      3
noise-buds-trance-wireless-earbuds            3
airwave-max-3-wireless-headphone              2
                                             ..
nirvanaa-duo                                  1
nirvana-uno                                   1
noise-chord-100-type-c-wired-earphone         1
noise-chord-200-type-c-wired-earphone         1
noise-chord-200-wired-earphone                1
Name: count, Length: 568, dtype: int64

In [105]:
df[df["base_product"].duplicated(keep=False)][["brand", "product_name", "handle", "base_product", "mrp_inr", "skus"]].sort_values("base_product")

     brand                                            product_name                                                handle                              base_product  mrp_inr                                                                                                 skus
1    Noise     Airwave Max 3 Wireless Headphone - ABHI Marketplace     airwave-max-3-wireless-headphone-abhi-marketplace          airwave-max-3-wireless-headphone   5499.0                                                 AUD-HDPHN-3-BLK | AUD-HDPHN-3-BRWN | AUD-HDPHN-3-BLU
2    Noise                 Airwave Max 3 Wireless Headphone - Deal                 airwave-max-3-wireless-headphone-deal          airwave-max-3-wireless-headphone   5499.0                                                 AUD-HDPHN-3-BLK | AUD-HDPHN-3-BRWN | AUD-HDPHN-3-BLU
4    Noise     Airwave Max 4 Wireless Headphone - ABHI Marketplace     airwave-max-4-wireless-headphone-abhi-marketplace          airwave-max-4-wireless-headphone   5999.0                                               AUD-HDPHN-4-BLK | AUD-HDPHN-4-BEIGE | AUD-HDPHN-4-TEAL
5    Noise    Airwave Max 4 Wireless Headphone - Unidays Exclusive    airwave-max-4-wireless-headphone-unidays-exclusive          airwave-max-4-wireless-headphone   5999.0                       AUD-HDPHN-4-BLK-UNIDAYS | AUD-HDPHN-4-BEIGE-UNIDAYS | AUD-HDPHN-4-TEAL-UNIDAYS
6    Noise                  Airwave Max 4 Wireless Headphone- Deal                 airwave-max-4-wireless-headphone-copy          airwave-max-4-wireless-headphone   5999.0                                               AUD-HDPHN-4-BLK | AUD-HDPHN-4-BEIGE | AUD-HDPHN-4-TEAL
..     ...                                                     ...                                                   ...                                       ...      ...                                                                                                  ...
191  Noise                Noise Master Buds Max Wireless Headphone              noise-master-buds-max-wireless-headphone  noise-master-buds-max-wireless-headphone  11999.0  AUD-HDPHN-MASTERBUDS-MAX-BLACK | AUD-HDPHN-MASTERBUDS-MAX-SILVER | AUD-HDPHN-MASTERBUDS-MAX-TITA...
199  Noise  Noise Pure Pods Open Ear Headphones - ABHI Marketplace  noise-pure-pods-open-ear-headphones-abhi-marketplace       noise-pure-pods-open-ear-headphones   6999.0                                                    AUD-HDPHN-PUREPODS-BLK | AUD-HDPHN-PUREPODS-BEIGE
198  Noise                     Noise Pure Pods Open Ear Headphones                   noise-pure-pods-open-ear-headphones       noise-pure-pods-open-ear-headphones   6999.0                                                    AUD-HDPHN-PUREPODS-BLK | AUD-HDPHN-PUREPODS-BEIGE
15   Noise                            Noise TWO Wireless Headphone                          noise-two-wireless-headphone              noise-two-wireless-headphone   4999.0                                            AUD-HDPHN-TWO-BLK | AUD-HDPHN-TWO-BLU | AUD-HDPHN-TWO-WHT
16   Noise                     Noise TWO Wireless Headphone - Deal                     noise-two-wireless-headphone-copy              noise-two-wireless-headphone   4999.0                                            AUD-HDPHN-TWO-BLK | AUD-HDPHN-TWO-BLU | AUD-HDPHN-TWO-WHT

[64 rows x 6 columns]

In [104]:
df.columns

Index(['brand', 'product_name', 'handle', 'category', 'product_type', 'sale_price_min_inr', 'sale_price_max_inr', 'mrp_inr', 'discount_percent', 'num_variants', 'colors', 'skus', 'in_stock_variants', 'tags_raw', 'features_raw', 'specs_raw_json', 'description_raw', 'created_at', 'updated_at', 'published_at', 'product_id', 'base_product'], dtype='str')

In [109]:
df[df['base_product']==df['handle']].shape

(558, 22)

In [110]:
df["listing_type"] = "normal"

df.loc[df["handle"].str.contains("abhi-marketplace", na=False), "listing_type"] = "abhi"
df.loc[df["handle"].str.contains("unidays-exclusive", na=False), "listing_type"] = "unidays"
df.loc[df["handle"].str.contains("deal|copy", na=False), "listing_type"] = "deal"

In [111]:
priority = {
    "normal": 0,
    "deal": 1,
    "abhi": 2,
    "unidays": 3
}

df["listing_priority"] = df["listing_type"].map(priority)

In [112]:
df_clean = (
    df.sort_values(["base_product", "listing_priority"])
      .drop_duplicates("base_product", keep="first")
      .copy()
)

In [113]:
print("Before:", len(df))
print("After :", len(df_clean))

Before: 602
After : 568

In [114]:
df_clean["listing_type"].value_counts()

listing_type
normal    555
deal       10
abhi        3
Name: count, dtype: int64

In [119]:
df_clean = df_clean.drop(
    columns=["listing_type", "listing_priority","handle"]
)

In [120]:
df_clean["base_product"].duplicated().sum()

np.int64(0)

In [127]:
for i in range(601):
    print(df_clean.head(i)['product_name'])

Series([], Name: product_name, dtype: str)
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
360                                                                           boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
360                                                                           boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech
362                                                          boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
360                                                                           boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech
362                                                          boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers
364                                                                           boAt Airdopes 115 | Earbuds with 13mm drivers, BEAST™ Mode for Gamers, ENx™ Technology
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
360                                                                           boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech
362                                                          boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers
364                                                                           boAt Airdopes 115 | Earbuds with 13mm drivers, BEAST™ Mode for Gamers, ENx™ Technology
366                                                                boAt Airdopes 120 | Wireless Earbuds with 40 Hours Playback, BEAST™ Mode, ASAP™ Charge, IWP™ Tech
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
360                                                                           boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech
362                                                          boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers
364                                                                           boAt Airdopes 115 | Earbuds with 13mm drivers, BEAST™ Mode for Gamers, ENx™ Technology
366                                                                boAt Airdopes 120 | Wireless Earbuds with 40 Hours Playback, BEAST™ Mode, ASAP™ Charge, IWP™ Tech
368                                                  boAt Airdopes 121 Pro Plus | Wireless Earbuds with 100 Hours Playback, 4 Mics with ENx™ Technology, BEAST™ Mode
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
360                                                                           boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech
362                                                          boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers
364                                                                           boAt Airdopes 115 | Earbuds with 13mm drivers, BEAST™ Mode for Gamers, ENx™ Technology
366                                                                boAt Airdopes 120 | Wireless Earbuds with 40 Hours Playback, BEAST™ Mode, ASAP™ Charge, IWP™ Tech
368                                                  boAt Airdopes 121 Pro Plus | Wireless Earbuds with 100 Hours Playback, 4 Mics with ENx™ Technology, BEAST™ Mode
369                                       boAt Airdopes 121 v2 | In-Ear Earbuds v2 with 8mm driver, LED Case Battery Indicator, 380mAh Pocket Friendly Charging Case
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
360                                                                           boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech
362                                                          boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers
364                                                                           boAt Airdopes 115 | Earbuds with 13mm drivers, BEAST™ Mode for Gamers, ENx™ Technology
366                                                                boAt Airdopes 120 | Wireless Earbuds with 40 Hours Playback, BEAST™ Mode, ASAP™ Charge, IWP™ Tech
368                                                  boAt Airdopes 121 Pro Plus | Wireless Earbuds with 100 Hours Playback, 4 Mics with ENx™ Technology, BEAST™ Mode
369                                       boAt Airdopes 121 v2 | In-Ear Earbuds v2 with 8mm driver, LED Case Battery Indicator, 380mAh Pocket Friendly Charging Case
370                                                boAt Airdopes 121v2 Plus | Wireless Earbuds with 50 Hours Playback, BEAST™ Mode, ENx™ Technology, IPX4 Resistance
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
360                                                                           boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech
362                                                          boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers
364                                                                           boAt Airdopes 115 | Earbuds with 13mm drivers, BEAST™ Mode for Gamers, ENx™ Technology
366                                                                boAt Airdopes 120 | Wireless Earbuds with 40 Hours Playback, BEAST™ Mode, ASAP™ Charge, IWP™ Tech
368                                                  boAt Airdopes 121 Pro Plus | Wireless Earbuds with 100 Hours Playback, 4 Mics with ENx™ Technology, BEAST™ Mode
369                                       boAt Airdopes 121 v2 | In-Ear Earbuds v2 with 8mm driver, LED Case Battery Indicator, 380mAh Pocket Friendly Charging Case
370                                                boAt Airdopes 121v2 Plus | Wireless Earbuds with 50 Hours Playback, BEAST™ Mode, ENx™ Technology, IPX4 Resistance
371                                                        boAt Airdopes 125 | Wireless Earbuds with 50 Hours Playback, BEAST™ Mode, Bluetooth v5.3, ENx™ Technology
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
360                                                                           boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech
362                                                          boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers
364                                                                           boAt Airdopes 115 | Earbuds with 13mm drivers, BEAST™ Mode for Gamers, ENx™ Technology
366                                                                boAt Airdopes 120 | Wireless Earbuds with 40 Hours Playback, BEAST™ Mode, ASAP™ Charge, IWP™ Tech
368                                                  boAt Airdopes 121 Pro Plus | Wireless Earbuds with 100 Hours Playback, 4 Mics with ENx™ Technology, BEAST™ Mode
369                                       boAt Airdopes 121 v2 | In-Ear Earbuds v2 with 8mm driver, LED Case Battery Indicator, 380mAh Pocket Friendly Charging Case
370                                                boAt Airdopes 121v2 Plus | Wireless Earbuds with 50 Hours Playback, BEAST™ Mode, ENx™ Technology, IPX4 Resistance
371                                                        boAt Airdopes 125 | Wireless Earbuds with 50 Hours Playback, BEAST™ Mode, Bluetooth v5.3, ENx™ Technology
382                                             boAt Airdopes 131 | Wireless Earbuds with upto 60 Hours Playback, 13mm Drivers, IWP Technology, 650mAh Charging Case
Name: product_name, dtype: str
373    boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
230                   boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
231                 boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
358                                                           boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology
359                                          boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant
360                                                                           boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech
362                                                          boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers
364                                                                           boAt Airdopes 115 | Earbuds with 13mm drivers, BEAST™ Mode for Gamers, ENx™ Technology
366                                                                boAt Airdopes 120 | Wireless Earbuds with 40 Hours Playback, BEAST™ Mode, ASAP™ Charge, IWP™ Tech
368                                                  boAt Airdopes 121 Pro Plus | Wireless Earbuds with 100 Hours Playback, 4 Mics with ENx™ Technology, BEAST™ Mode
369                                       boAt Airdopes 121 v2 | In-Ear Earbuds v2 with 8mm driver, LED Case Battery Indicator, 380mAh Pocket Friendly Charging Case
370                                                boAt Airdopes 121v2 Plus | Wireless Earbuds with 50 Hours Playback, BEAST™ Mode, ENx™ Technology, IPX4 Resistance
371                                                        boAt Airdopes 125 | Wireless Earbuds with 50 Hours Playback, BEAST™ Mode, Bluetooth v5.3, ENx™ Technology

In [125]:
pd.set_option("display.max_colwidth", None)

In [138]:
import re

df_clean["edition_type"] = (
    df_clean["product_name"]
    .str.extract(
        r"(?i)(Marvel Edition|DC Edition|RCB Edition|KKR Edition)"
    )[0]
)

In [139]:
df_clean[["product_name", "edition_type"]].dropna().to_string(index=False)

'                                                                                                                                                 product_name   edition_type\nboAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press Marvel Edition\n               boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity Marvel Edition\n             boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity Marvel Edition\n                              boAt Airdopes 131 Batman DC Edition | Wireless Earbuds with 13 mm Drivers, Bluetooth v5.0, 650mAh pocket friendly Charging Case     DC Edition\n                                                                           Airdopes 131 DC Edition | 13 mm Drivers, Type-C Carry Case, 12 hours Nonstop Music     DC Edition\n                                                                                                                                boAt Airdopes 131 KKR Edition    KKR Edition\n                                           boAt Airdopes 131 RCB Edition | Wireless Earbuds with 13mm drivers, 12 Hours Playback, IWP Feature, Bluetooth V5.0    RCB Edition\n       boAt Airdopes 131 | Wireless Earbuds Superman DC Edition Earbuds with 13 mm Drivers, Upto 12 hours Nonstop Music, 650mAh Pocket Friendly Charging Case     DC Edition\n                                boAt Airdopes 131 | Wireless Earbuds Wonder Woman DC Edition Earbuds With 13 mm Drivers, 650mAh Pocket Friendly Charging Case     DC Edition\n                                                                           Airdopes 138 DC Edition | 13 mm Drivers, Type-C Carry Case, 12 Hours Nonstop Music     DC Edition\n                           boAt Airdopes 441 KKR Edition | Wireless Earbuds with 6mm Drivers & boAt Signature Sound, 20 Hours Playback, IPX7 Water Resistance    KKR Edition\n                                        boAt Bassheads 100 RCB Edition | Limited Edition RCB Design Wired Earphones, 10mm Dynamic Drivers, In-line Microphone    RCB Edition\n                                                                                                                               boAt Bassheads 152 KKR Edition    KKR Edition\n                                                                                                                               boAt Bassheads 172 KKR Edition    KKR Edition\n                                     boAt Rockerz 650 DC Edition | Bluetooth Headphone with 40mm Dynamic Drivers, 60HRS Playback, ASAP™ Charge, Dual EQ Modes     DC Edition\n                                   boAt Rockerz 255 KKR Edition | Equipped with 10mm Drivers, Limited Edition KKR Design, 6H Nonstop Playback, 110mAh Battery    KKR Edition\n                                  boAt Rockerz 450 Batman DC Edition | Bluetooth Wireless Headphone with 40 mm Drivers HD Immersive Audio, Power Up For 15HRS     DC Edition\n                              boAt Rockerz 450 DC Edition | Wireless Bluetooth Headphone with 40mm Dynamic Drivers, Upto 15 Hours Playback, Adaptive Headband     DC Edition\n                     boAt Rockerz 450 Superman DC Edition | Wireless Bluetooth Headphone with 40mm Dynamic Drivers, Upto 15 Hours Playback, Adaptive Headband     DC Edition\n                 boAt Rockerz 450 Wonder Woman DC Edition | Wireless Bluetooth Headphone with 40mm Dynamic Drivers, Upto 15 Hours Playback, Adaptive Headband     DC Edition\n                                             boAt Rockerz 600 KKR Edition | Wireless Headphone with Bluetooth v4.1, 8H Playback, 40mm drivers, 300mAh battery    KKR Edition'

In [140]:
df_clean["edition_type"].value_counts(dropna=False)

edition_type
NaN               547
DC Edition         10
KKR Edition         6
Marvel Edition      3
RCB Edition         2
Name: count, dtype: int64

In [141]:
df_clean["edition_type"] = df_clean["edition_type"].fillna("Standard")

In [144]:

df_clean["model_series"] = (
    df_clean["product_name"]
    .str.extract(
        r"(?i)\b(Airdopes|Rockerz|Bassheads)\s*([A-Za-z0-9]+(?:\s*v\d+)?)"
    )
    .apply(lambda x: x[0] + " " + x[1] if x.notna().all() else None, axis=1)
)

In [147]:
df_clean.drop(columns='model_series',inplace=True)

In [149]:
boat_mask = df_clean["brand"].str.lower().eq("boat")

df_clean.loc[boat_mask, "model_series"] = (
    df_clean.loc[boat_mask, "product_name"]
    .str.split("|")
    .str[0]
    .str.strip()
    .str.replace(r"(?i)^boAt\s+", "", regex=True)
)

In [155]:
df_clean['model_series'].value_counts(dropna=False)

model_series
NaN                      170
Airdopes 131               3
Bassheads 225              3
Airdopes 411 ANC           2
Airdopes 441               2
                        ...
Rockerz Trendz             1
Rockerz Trinity Gen 2      1
Rockerz Trinity            1
Rockid Rush                1
Crest AI (Test)            1
Name: count, Length: 391, dtype: int64

In [152]:
df_clean[df_clean['brand']=='boAt'].shape

(398, 23)

In [156]:
df_clean['brand'].value_counts()

brand
boAt     398
Noise    170
Name: count, dtype: int64

In [157]:
noise_mask = df_clean["brand"].str.lower().eq("noise")

df_clean.loc[noise_mask, "model_series"] = (
    df_clean.loc[noise_mask, "product_name"]
    .str.replace(r"(?i)^Noise\s+", "", regex=True)
    .str.replace(
        r"(?i)\s*-\s*(Truly Wireless Earbuds|Wireless Earbuds|Wireless Headphone|"
        r"Wireless Headphones|Wired Earphone|Wired Earphones|"
        r"Neckband Earphones|Neckband|Wireless Neckband)$",
        "",
        regex=True
    )
    .str.replace(
        r"(?i)\s+(Truly Wireless Earbuds|Truly Wireless Bluetooth Earbuds|"
        r"Wireless Earbuds|Wireless Headphone|Wireless Headphones|"
        r"Bluetooth Wireless Neckband Earphones|Wireless Neckband|"
        r"Neckband Earphones|Wired Earphone|Wired Earphones|"
        r"Gaming Headphone)$",
        "",
        regex=True
    )
    .str.strip()
)

In [170]:
for i in range(len(df_clean)):
    print(df_clean.iloc[i]["model_series"])

Airdopes 131 Captain America Marvel Edition
Rockerz 450 Black Panther Marvel Edition
Rockerz 450 Captain America Marvel Edition
Airdopes 100
Airdopes 101
Airdopes 101v2
Airdopes 111v2
Airdopes 115
Airdopes 120
Airdopes 121 Pro Plus
Airdopes 121 v2
Airdopes 121v2 Plus
Airdopes 125
Airdopes 131
Airdopes 131 Batman DC Edition
Airdopes 131 DC Edition
Airdopes 131 Elite ANC
Airdopes 131 Gen 2
Airdopes 131 KKR Edition
Airdopes 131 Pro Buds
Airdopes 131 RCB Edition
Airdopes 131
Airdopes 131
Airdopes 138 DC Edition
Airdopes 138 PRO
Airdopes 141
Airdopes 141 ANC
Airdopes 141 Elite ANC
Airdopes 141 Gen 2
Airdopes 141 Neo
Airdopes 141 Pro Buds
Airdopes 155
Airdopes 161
Airdopes 161 ANC Elite
Airdopes 161 ANC
Airdopes 161 Deadpool Edition
Airdopes 161 Pro Buds
Airdopes 161 Pro
Airdopes 161 Thor Edition
Airdopes 171
Airdopes 172
Airdopes 173
Airdopes 181 Pro
Airdopes 181 Pro SS Edition
Airdopes 190
Airdopes 200 Plus
Airdopes 201
Airdopes 207
Airdopes 213
Airdopes 219
Airdopes 280 ANC
Airdopes 281
Airdopes 281 Pro
Airdopes 300
Airdopes 301
Airdopes 311 PRO
Airdopes 313
Airdopes 381
Airdopes 381 MKI
Airdopes 383
Airdopes 391
Airdopes 393 ANC
Airdopes 402
Airdopes 411 ANC
Airdopes 418 ANC
Airdopes 431
Airdopes 441
Airdopes 441 KKR Edition
Airdopes 441
Airdopes 441 Pro
Airdopes 441 Pro Special Batman Edition
Airdopes 443
Airdopes 451v2
Airdopes 452
Airdopes 458
Airdopes 461
Airdopes 491
Airdopes 500 ANC
Airdopes 501 ANC
Airdopes 511 V2
Airdopes 601 ANC
Airdopes 621
Airdopes 641
Airdopes 71
Airdopes 711
Airdopes 800 HiDef
Airdopes 91
Airdopes 91 Prime
Airdopes Ace
Airdopes Ace Gen 2
Airdopes Alpha Deadpool Edition
Airdopes Alpha
Airdopes Atom 81
Airdopes Atom 81 Pro
Airdopes Beat
Airdopes Bliss ANC
Airdopes Crude
Airdopes Drift
Airdopes Flex 454 ANC
Airdopes Fuel
Airdopes Genesis
Airdopes Hype
Immortal 141
Airdopes Joy V2
Airdopes Joy
Airdopes Kick
Airdopes Loop
Airdopes Max
Airdopes Plus 318
Airdopes Prime 412
Airdopes Prime 511
Airdopes Prime 513 ANC
Airdopes Prime 700 ANC
Airdopes Prime 701 ANC
Airdopes ProClip
Airdopes Sonik
Airdopes Supreme
Airdopes Ultra Plus
Airdopes Ultra Pro
Airdopes Unity ANC
Airdopes Zing
Airwave Max 3 Wireless Headphone - Deal
Airwave Max 4 Wireless Headphone- Deal
Bassheads 100
Bassheads 100C
Bassheads 100
Bassheads 100 RCB Edition
Bassheads 102
Bassheads 103
Bassheads 104
Bassheads 105
Bassheads 110
Bassheads 122
Bassheads 122 ANC
Bassheads 132
Bassheads 152
Bassheads 152 KKR Edition
Bassheads 162
Bassheads 162v2
Bassheads 172
Bassheads 172 KKR Edition
Bassheads 182
Bassheads 192 - Make in India
Bassheads 202 - Make in India
Bassheads 211
Bassheads 213L
Bassheads 220
Bassheads 225
Bassheads 225
Bassheads 225
Bassheads 228
Bassheads 242
Bassheads 55
Bassheads 900
Bassheads 900 C Pro
Bassheads 900 Pro
Bassheads 901 Pro
Bassheads 90C
Bassheads 910
Bassheads 95
Bassheads 950v2
100 Wireless
102 Wireless
103 Wireless
Airdopes 111
Airdopes 113
Airdopes 118 Wrogn Edition
Airdopes 121 PRO
Airdopes 131 PRO
Airdopes 138 Gen 2
Airdopes 138
Airdopes 148 Gen 2
Airdopes 141 Pro
Airdopes 148
Airdopes 161 (Metallic)
Airdopes 163
Airdopes 170
Airdopes 175
Airdopes 181
Airdopes 183
Airdopes 191 ANC
Airdopes 191G
Airdopes 192
Airdopes 212
Airdopes 283
Airdopes 311v2
Airdopes 381 Sunburn Edition
Airdopes 383 Sunburn Edition
Airdopes 408
Airdopes 411 ANC
Airdopes 413 ANC
Airdopes 433
Airdopes 441 Sunburn Edition
Airdopes 71 Gen 2
Airdopes 800
Airdopes Alpha Gen 2
Airdopes Atom 83
Airdopes Plus 214
Airdopes Plus 222
Airdopes Plus 223
Airdopes Plus 224
Airdopes Plus 311
Airdopes Plus 421 ANC
Airdopes Prime 413
Airdopes Prime 512
Airdopes Prime 800D
Airdopes Prime Supreme
Airdopes Primo
Airdopes ProClip SS Edition
Airdopes ProGear
Airdopes Pulse
Airdopes Stride
Bassheads 152 Sunburn Edition
Bassheads 172 Sunburn Edition
Bassheads 180
Bassheads 200
Bassheads 210
BassHeads 212L
Bassheads 220 MKI
Bassheads 300C
BassHeads 85
Standalone Crest AI Pack
Immortal 121
Immortal 1300
Immortal 131
Nirvana Eutopia - Dhruv Kapoor Edition
Nirvana Ion ANC Limited Edition
Nirvana Ivy - Dhruv Kapoor Edition
Nirvana Lucid
Nirvana Space
Nirvana Zenith Pro SS Edition
Rockerz 113
Rockerz 200
Rockerz 203
Rockerz 205 Pro
Rockerz 238 Pro
Rockerz 255 Neo
Rockerz 255 Pro+
Rockerz 258 Pro+
Rockerz 260
Rockerz 301 ANC
Rockerz 330 Pro
Rockerz 351 ANC
Rockerz 355
Rockerz 370 Pro
Rockerz 371
Rockerz 412
Rockerz 413
Rockerz 421 Gen 2
Rockerz 421
Rockerz 460
Rockerz 460 Naruto Edition
Rockerz 512 ANC
Rockerz 550 Sunburn Edition
Rockerz 650 DC Edition
Rockerz 650 Sunburn Edition
Rockerz Apex
Rockerz Plus 440
Rockerz Plus 450 ANC
Rockerz Plus 550
Rockerz Prime 205
Rockerz Prime 415
Rockerz Strive
Rockerz Summit
Rockerz Trinity Grande
Rockerz Zen ANC
Sailor Play
Rockerz 378
Buds N1 Truly Wireless Earbuds- Deal
Buds Uno Truly Wireless Earbuds - Deal
Buds VS304
Buds X ANC Truly Wireless Earbuds - ABHI Marketplace
Buds X Prime
[Do not delete]Airdopes 163 Cover
Immortal 300
Immortal 1000D
Immortal 100
Immortal 101
Immortal 111
Immortal 125
Immortal 128
Immortal 150
Immortal 158
Immortal 161
Immortal 170
Immortal 171
Immortal 181
Immortal 200
Immortal 201
Immortal 400
Immortal 700
Immortal Airspeed Pro
Immortal katana Blade 2.0
Immortal Katana Blade
Nirvanaa 1007ANC
Nirvana 525ANC
Nirvanaa 717 ANC
Nirvana 751 ANC
Nirvana CE-1Nirvana CE-1
Nirvana Crown
Nirvana Crystl
Nirvana Eutopia 2 ANC
Nirvana Eutopia
Nirvana Ion ANC
Nirvana Ion ANC Pro
Nirvana ION ANC Limited Edition
Nirvana Ion
Nirvana Iris
Nirvana Ivy Pro
Nirvana Ivy
Nirvana Nebula
Nirvanaa Uno
Nirvana X TWS
Nirvana Zenith
Nirvana Zenith Pro
Nirvanaa DUO
Airwave Max 4
Air Buds 2
Air Buds 3
Air Buds 6
Air Buds Mini 2
Air Buds Mini
Air Buds Nano
Air Buds+
Air Buds Pro 2 ANC Earbud
Air Buds Pro 3 Earbuds
Air Buds Pro 4 Earbuds
Air Buds Pro 6 Earbuds
Air Buds Pro SE Earbuds
Air Buds
Air Clips 2 OWS Open Ear Headphone
Air Clips OWS Open Ear Headphone
Air Clips Pro OWS Open Ear Headphone
Airwave Crest Bluetooth Wireless Neckband Earphones - ABHI Marketplace
Airwave Max 2
Airwave Max 5 Headphone
Airwave Max 5 Headphone - Limited Edition - Deal
Airwave Max 5 Headphone - Unidays
Airwave Max 6 Headphone
Airwave Max 3
Airwave Max XR
Airwave
Airwave Neckband Earphones - Telegram Exclusive
Airwave Pro
Airwave Pro Neckband Earphones - ABHI Marketplace
Alt Buds Open
ALT Buds (S)
ALT Buds (S) - Chosen Orange
ALT Buds (S) Truly Wireless Bluetooth Earbuds - Super Saver
ALT Buds
ALT Clip OWS Earclips
Aura Buds
Aura Buds in-Ear Truly Wireless Earbuds with 60H of Playtime, Quad Mic with ENC, Dual Device Pairing, Instacharge (10 min = 150 min), 12mm Polymer Composite Driver, BT v5.3
Beads
Blaze Bluetooth Wireless Neckband Earphones with Mic- OS
Bravo Neckband
Bravo Neckband Earphones with Mic - Partner Deal Store
Bravo Neckband Earphones with Mic - Partner Exclusive
Buds Ace
Buds Aero
Buds Apex
Buds Apex Truly Wireless Bluetooth Earbuds - Blue Tokai
Buds Apex Truly Wireless Bluetooth Earbuds - Cloud Grey
Buds Combat
Buds Combat X
Buds Combat Z
Buds Combat Z In-Ear Truly Wireless Gaming Earbuds with 35ms Low Latency, 50H of Playtime, Instacharge (10 min = 120 min), 10mm Driver,BT v5.3
Buds Connect 2
Buds Connect 3
Buds Connect
Buds E1
Buds Evoke
Buds Explore
Buds F1
Buds Marine
Buds Mini
Buds MVP102
Buds N1 Pro
Buds N1 Pro Truly Wireless Earbuds - Chrome Black
Buds N1 Pro Truly Wireless Earbuds - Super Saver
Buds N1 Pro Truly Wireless Earbuds - Unidays
Buds N1
Buds N1 Truly Wireless Earbuds - Carbon Black
Buds N1 Truly Wireless Earbuds - Calm Beige
Buds N1 Truly Wireless Earbuds - Forest Green
Buds N1 Truly Wireless Earbuds - Healthifyme Exclusive
Buds N1 Truly Wireless Earbuds - Ice Blue
Buds N2 Pro
Buds NEO
Buds NEO Truly Wireless Earbuds - Black
Buds NEO Truly Wireless Earbuds - Green
Buds NEO Truly Wireless Earbuds - Grey
Buds NEO Truly Wireless Earbuds - Wine
Buds Nero
Buds Play
Buds R1
Buds Trance 2
Buds Trance
Buds Trance with 45 Hrs Playtime, Low Latency (up to 40ms), HyperSync, and IPX5 Bluetooth Headset
Buds Trooper
Buds Uno
Buds Vector
Buds Venus
Buds Venus Truly Wireless in-Ear Earbuds with ANC (Up to 30dB), 40H Playtime, Quad Mic with ENC, Instacharge (10 min = 120 min), Low Latency(up to 45ms), 10mm Driver
Buds Verve 2
Buds Verve
Buds VS102 Elite
Buds VS102 Neo
Buds VS102 Neo with 40 Hrs Playtime, Environmental Noise Cancellation, Quad Mic Bluetooth Headset
Buds VS102+
Buds VS102 Pro
Buds VS102 Pro Truly Wireless Earbuds - Black
Buds VS102 Pro Truly Wireless Earbuds - Blue Tokai
Buds VS102
Buds VS102 Truly Wireless Earbuds - Jet Black
Buds VS102+ Truly Wireless Earbuds - Blue Tokai
Buds VS102 with 50 Hrs Playtime, 11mm Driver, IPX5 and Unique Flybird Design Bluetooth Headset
Buds VS102 Truly Wireless Earbuds - Pearl White
Buds VS103 Pro
Buds VS103
Buds VS104 Max
Buds VS104 Max Truly Wireless In-Ear Earbuds with ANC(Up to 25dB),Up to 45H Playtime, Quad Mic with ENC, Instacharge (10 min = 180 min), 13mm Driver, BT v5.3
Buds VS104 Pro
Buds VS104
Buds VS106
Buds VS106 Truly Wireless In-Ear Earbuds with 50H Playtime, Quad Mic with ENC, Instacharge (10 min = 200 min),Ultra-Low Latency(up to 40ms), 10mm Driver, and BT v5.3
Buds VS201
Buds VS202
Buds VS204
Buds VS303
Buds VS401
Buds VS401 In-Ear Truly Wireless Earbuds with 50H of Playtime, Low Latency (up to 50ms), Quad Mic with ENC, Instacharge (10 min = 200 min), 10mm Driver, BT v5.3
Buds VS402
Buds VS402 Truly Wireless Earbuds  - Neon White
Buds VS402 in-Ear Truly Wireless Earbuds with 50H of Playtime, Low Latency, Quad Mic with ENC, Instacharge (10 min = 120 min), 10mm Driver, BT v5.3, Breathing LED Lights
Buds VS404
Buds VS404 with 50 Hours Playtime, ENC with Quad Mic, 3 EQ modes Bluetooth Headset
Buds VS501
Buds VS501 Truly Wireless Bluetooth Earbuds - Forest Green
Buds VS501 Truly Wireless Bluetooth Earbuds - Pebble Black
Buds VS601
Buds X ANC
Buds X Prime in-Ear Truly Wireless Earbuds with 120H of Playtime, Quad Mic with ENC, Instacharge (10 min = 200 min),Premium Dual Tone Finish, 11mm Driver, BT v5.3
Buds X Ultra
Buds X2
Buds Xero
Chord 100 Type-C
Chord 200 Type-C
Chord 200
Clutch HP-P01
Combat Wireless Gaming Neckband Earphones with Mic
Airwave Crest
Flair Touch
Flair XL
Go Buds
X KableOne Headphones
Master Buds 2
Master Buds 2 Truly Wireless Bluetooth Earbuds - REF
Master Buds Max
Master Buds Max Wireless Headphone - REF
Master Buds
Master Buds Truly Wireless Earbuds - Special Edition
Nerve Neckband Earphones with Mic
Nerve Neckband Earphones with Mic - Partner Deal Store
Nerve Pro Neckband Earphones with Mic
Pop Buds
Powr
Pure Pods 2 Open Ear Headphones
Pure Pods Open Ear Headphones
Sense Neckband Earphones with Mic
Tune Active Pro
Tune Elite Sport Neckband Earphones with Mic
Tune LITE Bluetooth Wireless Neckband Earphones with Mic- OS
Tune Sport 2 Neckband Earphones with Mic
TWO
View Buds
Xtreme
Rockerz 103 Pro
Rockerz 103 V2 Pro
Rockerz 109
Rockerz 110
Rockerz 111
Rockerz 112
Rockerz 150 Pro
Rockerz 185
Rockerz 185 Pro
Rockerz 195
Rockerz 195 V2 Pro
Rockerz 202
Rockerz 210 ANC
Rockerz 215
Rockerz 235 Pro
Rockerz 235 V2
Rockerz 235 v2
Rockerz 238
Rockerz 245 Pro
Rockerz 245 V2
Rockerz 245 V2 Pro
Rockerz 255
Rockerz 255 ANC
Rockerz 255 ARC
Rockerz 255 KKR Edition
Rockerz 255 Max
Rockerz 255 Pro
Rockerz 255 Touch
Rockerz 255 Z plus
Rockerz 255F
Rockerz 255R
Rockerz 258 Pro
Rockerz 260 v1
Rockerz 261
Rockerz 261 Pro
Rockerz 265 V2
Rockerz 275 V2
Rockerz 330
Rockerz 330 ANC
Rockerz 333
Rockerz 333 ANC
Rockerz 333 Pro
Rockerz 333
Rockerz 335
Rockerz 338
Rockerz 370
Rockerz 375
Rockerz 385 V2
Rockerz 390 V2
Rockerz 400
Rockerz 400 Pro
Rockerz 410
Rockerz 411
Rockerz 425
Rockerz 430
Rockerz 450
Rockerz 450 Batman DC Edition
Rockerz 450 DC Edition
Rockerz 450 Iron Man
Rockerz 450 Pro
Rockerz 450 Superman DC Edition
Rockerz 450 Wonder Woman DC Edition
Rockerz 450R
Rockerz 480
Rockerz 510
Rockerz 518
Rockerz 550
Rockerz 551ANC
Rockerz 551 ANC Pro
Rockerz 558 Sunburn Edition
Rockerz 558
Rockerz 560
Rockerz 600
Rockerz 600 KKR Edition
Rockerz 610
Rockerz 650 Pro
Rockerz 650
Rockerz 660
Rockerz 80 Pro
Rockerz Bliss
Rockerz Bold
Rockerz Enticer
Rockerz Plus 550 ANC
Rockerz Prime 255Z
Rockerz Trendz
Rockerz Trinity Gen 2
Rockerz Trinity
Rockid Rush
Test Order -API
Crest AI (Test)
Buds VS102 Truly Wireless Earbuds - Deal

In [171]:
import re

noise_mask = df_clean["brand"].str.lower().eq("noise")

df_clean.loc[noise_mask, "model_series"] = (
    df_clean.loc[noise_mask, "product_name"]

   
    .str.replace(
        r"(?i)^Noise\s+",
        "",
        regex=True
    )

    .str.replace(
        r"(?i)\s*-\s*(ABHI Marketplace|Unidays|Deal|Copy|"
        r"Partner Deal Store|Partner Exclusive|Special Edition|"
        r"Super Saver|REF|Telegram Exclusive|Healthifyme Exclusive|"
        r"Chrome Black|Calm Beige|Forest Green|Ice Blue|"
        r"Carbon Black|Jet Black|Pearl White|Neon White|"
        r"Blue Tokai|Chosen Orange|Black|Green|Grey|Wine)\s*$",
        "",
        regex=True
    )

  
    .str.replace(
        r"(?i)\s+(Truly Wireless.*|"
        r"Wireless.*|"
        r"In-Ear.*|"
        r"Open Ear.*|"
        r"Bluetooth.*|"
        r"Wired.*|"
        r"Gaming.*|"
        r"with Mic.*|"
        r"with ANC.*|"
        r"with \d+.*)$",
        "",
        regex=True
    )

    .str.strip()
)

In [172]:
print(
    df_clean.loc[
        noise_mask,
        ["product_name", "model_series"]
    ].to_string(index=False)
)

                                                                                                                                                                      product_name                              model_series
                                                                                                                                           Airwave Max 3 Wireless Headphone - Deal                             Airwave Max 3
                                                                                                                                            Airwave Max 4 Wireless Headphone- Deal                             Airwave Max 4
                                                                                                                                              Buds N1 Truly Wireless Earbuds- Deal                                   Buds N1
                                                                                                                                            Buds Uno Truly Wireless Earbuds - Deal                                  Buds Uno
                                                                                                                                           Noise Buds VS304 Truly Wireless Earbuds                                Buds VS304
                                                                                                                              Buds X ANC Truly Wireless Earbuds - ABHI Marketplace                                Buds X ANC
                                                                                                                                         Noise Buds X Prime Truly Wireless Earbuds                              Buds X Prime
                                                                                                                                                  Airwave Max 4 Wireless Headphone                             Airwave Max 4
                                                                                                                                         Noise Air Buds 2 - Truly Wireless Earbuds                              Air Buds 2 -
                                                                                                                                         Noise Air Buds 3 - Truly Wireless Earbuds                              Air Buds 3 -
                                                                                                                                         Noise Air Buds 6 - Truly Wireless Earbuds                              Air Buds 6 -
                                                                                                                                    Noise Air Buds Mini 2 - Truly Wireless Earbuds                         Air Buds Mini 2 -
                                                                                                                                      Noise Air Buds Mini - Truly Wireless Earbuds                           Air Buds Mini -
                                                                                                                                      Noise Air Buds Nano - Truly Wireless Earbuds                           Air Buds Nano -
                                                                                                                                            Noise Air Buds+ Truly Wireless Earbuds                                 Air Buds+
                                                                                                                                                   Noise Air Buds Pro 2 ANC Earbud                 Air Buds Pro 2 ANC Earbud
                                                                                                                                                      Noise Air Buds Pro 3 Earbuds                    Air Buds Pro 3 Earbuds
                                                                                                                                                      Noise Air Buds Pro 4 Earbuds                    Air Buds Pro 4 Earbuds
                                                                                                                                                      Noise Air Buds Pro 6 Earbuds                    Air Buds Pro 6 Earbuds
                                                                                                                                                     Noise Air Buds Pro SE Earbuds                   Air Buds Pro SE Earbuds
                                                                                                                                           Noise Air Buds - Truly Wireless Earbuds                                Air Buds -
                                                                                                                                          Noise Air Clips 2 OWS Open Ear Headphone                           Air Clips 2 OWS
                                                                                                                                            Noise Air Clips OWS Open Ear Headphone                             Air Clips OWS
                                                                                                                                        Noise Air Clips Pro OWS Open Ear Headphone                         Air Clips Pro OWS
                                                                                                      Noise Airwave Crest Bluetooth Wireless Neckband Earphones - ABHI Marketplace                             Airwave Crest
                                                                                                                                            Noise Airwave Max 2 Wireless Headphone                             Airwave Max 2
                                                                                                                                                     Noise Airwave Max 5 Headphone                   Airwave Max 5 Headphone
                                                                                                                            Noise Airwave Max 5 Headphone - Limited Edition - Deal Airwave Max 5 Headphone - Limited Edition
                                                                                                                                           Noise Airwave Max 5 Headphone - Unidays                   Airwave Max 5 Headphone
                                                                                                                                                     Noise Airwave Max 6 Headphone                   Airwave Max 6 Headphone
                                                                                                                                                  Airwave Max 3 Wireless Headphone                             Airwave Max 3
                                                                                                                                           Noise Airwave Max XR Wireless Headphone                            Airwave Max XR
                                                                                                                                                  Noise Airwave Neckband Earphones                Airwave Neckband Earphones
                                                                                                                             Noise Airwave Neckband Earphones - Telegram Exclusive                Airwave Neckband Earphones
                                                                                                                                              Noise Airwave Pro Neckband Earphones            Airwave Pro Neckband Earphones
                                                                                                                           Noise Airwave Pro Neckband Earphones - ABHI Marketplace            Airwave Pro Neckband Earphones
                                                                                                                              Noise Alt Buds Open Truly Wireless Bluetooth Earbuds                             Alt Buds Open
                                                                                                                               Noise ALT Buds (S) Truly Wireless Bluetooth Earbuds                              ALT Buds (S)
                                                                                                                                                Noise ALT Buds (S) - Chosen Orange                              ALT Buds (S)
                                                                                                                 Noise ALT Buds (S) Truly Wireless Bluetooth Earbuds - Super Saver                              ALT Buds (S)
                                                                                                                                   Noise ALT Buds Truly Wireless Bluetooth Earbuds                                  ALT Buds
                                                                                                                                                       Noise ALT Clip OWS Earclips                     ALT Clip OWS Earclips
                                                                                                                                            Noise Aura Buds Truly Wireless Earbuds                                 Aura Buds
Noise Aura Buds in-Ear Truly Wireless Earbuds with 60H of Playtime, Quad Mic with ENC, Dual Device Pairing, Instacharge (10 min = 150 min), 12mm Polymer Composite Driver, BT v5.3                                 Aura Buds
                                                                                                                                                Noise Beads Truly Wireless Earbuds                                     Beads
                                                                                                                    Noise Blaze Bluetooth Wireless Neckband Earphones with Mic- OS                                     Blaze
                                                                                                                                                                    Bravo Neckband                            Bravo Neckband
                                                                                                                      Noise Bravo Neckband Earphones with Mic - Partner Deal Store                  Bravo Neckband Earphones
                                                                                                                       Noise Bravo Neckband Earphones with Mic - Partner Exclusive                  Bravo Neckband Earphones
                                                                                                                                             Noise Buds Ace Truly Wireless Earbuds                                  Buds Ace
                                                                                                                                            Noise Buds Aero Truly Wireless Earbuds                                 Buds Aero
                                                                                                                                  Noise Buds Apex Truly Wireless Bluetooth Earbuds                                 Buds Apex
                                                                                                                     Noise Buds Apex Truly Wireless Bluetooth Earbuds - Blue Tokai                                 Buds Apex
                                                                                                                     Noise Buds Apex Truly Wireless Bluetooth Earbuds - Cloud Grey                                 Buds Apex
                                                                                                                                                Noise Buds Combat Wireless Earbuds                               Buds Combat
                                                                                                                                        Noise Buds Combat X Truly Wireless Earbuds                             Buds Combat X
                                                                                                                                              Noise Buds Combat Z Wireless Earbuds                             Buds Combat Z
                                    Buds Combat Z In-Ear Truly Wireless Gaming Earbuds with 35ms Low Latency, 50H of Playtime, Instacharge (10 min = 120 min), 10mm Driver,BT v5.3                             Buds Combat Z
                                                                                                                                       Noise Buds Connect 2 Truly Wireless Earbuds                            Buds Connect 2
                                                                                                                                       Noise Buds Connect 3 Truly Wireless Earbuds                            Buds Connect 3
                                                                                                                                         Noise Buds Connect Truly Wireless Earbuds                              Buds Connect
                                                                                                                                              Noise Buds E1 Truly Wireless Earbuds                                   Buds E1
                                                                                                                                           Noise Buds Evoke Truly Wireless Earbuds                                Buds Evoke
                                                                                                                                         Noise Buds Explore Truly Wireless Earbuds                              Buds Explore
                                                                                                                                    Noise Buds F1 Truly Wireless Bluetooth Earbuds                                   Buds F1
                                                                                                                                Noise Buds Marine Truly Wireless Bluetooth Earbuds                               Buds Marine
                                                                                                                                            Noise Buds Mini Truly Wireless Earbuds                                 Buds Mini
                                                                                                                                          Noise Buds MVP102 Truly Wireless Earbuds                               Buds MVP102
                                                                                                                                          Noise Buds N1 Pro Truly Wireless Earbuds                               Buds N1 Pro
                                                                                                                           Noise Buds N1 Pro Truly Wireless Earbuds - Chrome Black                               Buds N1 Pro
                                                                                                                            Noise Buds N1 Pro Truly Wireless Earbuds - Super Saver                               Buds N1 Pro
                                                                                                                                Noise Buds N1 Pro Truly Wireless Earbuds - Unidays                               Buds N1 Pro
                                                                                                                                              Noise Buds N1 Truly Wireless Earbuds                                   Buds N1
                                                                                                                               Noise Buds N1 Truly Wireless Earbuds - Carbon Black                                   Buds N1
                                                                                                                                 Noise Buds N1 Truly Wireless Earbuds - Calm Beige                                   Buds N1
                                                                                                                               Noise Buds N1 Truly Wireless Earbuds - Forest Green                                   Buds N1
                                                                                                                      Noise Buds N1 Truly Wireless Earbuds - Healthifyme Exclusive                                   Buds N1
                                                                                                                                   Noise Buds N1 Truly Wireless Earbuds - Ice Blue                                   Buds N1
                                                                                                                                Noise Buds N2 Pro Truly Wireless Bluetooth Earbuds                               Buds N2 Pro
                                                                                                                                             Noise Buds NEO Truly Wireless Earbuds                                  Buds NEO
                                                                                                                                     Noise Buds NEO Truly Wireless Earbuds - Black                                  Buds NEO
                                                                                                                                     Noise Buds NEO Truly Wireless Earbuds - Green                                  Buds NEO
                                                                                                                                      Noise Buds NEO Truly Wireless Earbuds - Grey                                  Buds NEO
                                                                                                                                      Noise Buds NEO Truly Wireless Earbuds - Wine                                  Buds NEO
                                                                                                                                            Noise Buds Nero Truly Wireless Earbuds                                 Buds Nero
                                                                                                                                            Noise Buds Play Truly Wireless Earbuds                                 Buds Play
                                                                                                                                              Noise Buds R1 Truly Wireless Earbuds                                   Buds R1
                                                                                                                                              Noise Buds Trance 2 Wireless Earbuds                             Buds Trance 2
                                                                                                                                                Noise Buds Trance Wireless Earbuds                               Buds Trance

In [173]:
df_clean["model_series"] = (
    df_clean["model_series"]
    .str.replace(r"\s*-\s*$", "", regex=True)
    .str.strip()
)

In [174]:
df_clean["model_series"] = (
    df_clean["model_series"]
    .str.replace(
        r"(?i)\s+(?:earbuds?|headphones?|neckband earphones?|wired earphones?)$",
        "",
        regex=True
    )
    .str.strip()
)

In [175]:
print(
    df_clean.loc[
        df_clean["brand"].str.lower().eq("noise"),
        ["product_name", "model_series"]
    ].to_string(index=False)
)

                                                                                                                                                                      product_name                              model_series
                                                                                                                                           Airwave Max 3 Wireless Headphone - Deal                             Airwave Max 3
                                                                                                                                            Airwave Max 4 Wireless Headphone- Deal                             Airwave Max 4
                                                                                                                                              Buds N1 Truly Wireless Earbuds- Deal                                   Buds N1
                                                                                                                                            Buds Uno Truly Wireless Earbuds - Deal                                  Buds Uno
                                                                                                                                           Noise Buds VS304 Truly Wireless Earbuds                                Buds VS304
                                                                                                                              Buds X ANC Truly Wireless Earbuds - ABHI Marketplace                                Buds X ANC
                                                                                                                                         Noise Buds X Prime Truly Wireless Earbuds                              Buds X Prime
                                                                                                                                                  Airwave Max 4 Wireless Headphone                             Airwave Max 4
                                                                                                                                         Noise Air Buds 2 - Truly Wireless Earbuds                                Air Buds 2
                                                                                                                                         Noise Air Buds 3 - Truly Wireless Earbuds                                Air Buds 3
                                                                                                                                         Noise Air Buds 6 - Truly Wireless Earbuds                                Air Buds 6
                                                                                                                                    Noise Air Buds Mini 2 - Truly Wireless Earbuds                           Air Buds Mini 2
                                                                                                                                      Noise Air Buds Mini - Truly Wireless Earbuds                             Air Buds Mini
                                                                                                                                      Noise Air Buds Nano - Truly Wireless Earbuds                             Air Buds Nano
                                                                                                                                            Noise Air Buds+ Truly Wireless Earbuds                                 Air Buds+
                                                                                                                                                   Noise Air Buds Pro 2 ANC Earbud                        Air Buds Pro 2 ANC
                                                                                                                                                      Noise Air Buds Pro 3 Earbuds                            Air Buds Pro 3
                                                                                                                                                      Noise Air Buds Pro 4 Earbuds                            Air Buds Pro 4
                                                                                                                                                      Noise Air Buds Pro 6 Earbuds                            Air Buds Pro 6
                                                                                                                                                     Noise Air Buds Pro SE Earbuds                           Air Buds Pro SE
                                                                                                                                           Noise Air Buds - Truly Wireless Earbuds                                  Air Buds
                                                                                                                                          Noise Air Clips 2 OWS Open Ear Headphone                           Air Clips 2 OWS
                                                                                                                                            Noise Air Clips OWS Open Ear Headphone                             Air Clips OWS
                                                                                                                                        Noise Air Clips Pro OWS Open Ear Headphone                         Air Clips Pro OWS
                                                                                                      Noise Airwave Crest Bluetooth Wireless Neckband Earphones - ABHI Marketplace                             Airwave Crest
                                                                                                                                            Noise Airwave Max 2 Wireless Headphone                             Airwave Max 2
                                                                                                                                                     Noise Airwave Max 5 Headphone                             Airwave Max 5
                                                                                                                            Noise Airwave Max 5 Headphone - Limited Edition - Deal Airwave Max 5 Headphone - Limited Edition
                                                                                                                                           Noise Airwave Max 5 Headphone - Unidays                             Airwave Max 5
                                                                                                                                                     Noise Airwave Max 6 Headphone                             Airwave Max 6
                                                                                                                                                  Airwave Max 3 Wireless Headphone                             Airwave Max 3
                                                                                                                                           Noise Airwave Max XR Wireless Headphone                            Airwave Max XR
                                                                                                                                                  Noise Airwave Neckband Earphones                                   Airwave
                                                                                                                             Noise Airwave Neckband Earphones - Telegram Exclusive                                   Airwave
                                                                                                                                              Noise Airwave Pro Neckband Earphones                               Airwave Pro
                                                                                                                           Noise Airwave Pro Neckband Earphones - ABHI Marketplace                               Airwave Pro
                                                                                                                              Noise Alt Buds Open Truly Wireless Bluetooth Earbuds                             Alt Buds Open
                                                                                                                               Noise ALT Buds (S) Truly Wireless Bluetooth Earbuds                              ALT Buds (S)
                                                                                                                                                Noise ALT Buds (S) - Chosen Orange                              ALT Buds (S)
                                                                                                                 Noise ALT Buds (S) Truly Wireless Bluetooth Earbuds - Super Saver                              ALT Buds (S)
                                                                                                                                   Noise ALT Buds Truly Wireless Bluetooth Earbuds                                  ALT Buds
                                                                                                                                                       Noise ALT Clip OWS Earclips                     ALT Clip OWS Earclips
                                                                                                                                            Noise Aura Buds Truly Wireless Earbuds                                 Aura Buds
Noise Aura Buds in-Ear Truly Wireless Earbuds with 60H of Playtime, Quad Mic with ENC, Dual Device Pairing, Instacharge (10 min = 150 min), 12mm Polymer Composite Driver, BT v5.3                                 Aura Buds
                                                                                                                                                Noise Beads Truly Wireless Earbuds                                     Beads
                                                                                                                    Noise Blaze Bluetooth Wireless Neckband Earphones with Mic- OS                                     Blaze
                                                                                                                                                                    Bravo Neckband                            Bravo Neckband
                                                                                                                      Noise Bravo Neckband Earphones with Mic - Partner Deal Store                                     Bravo
                                                                                                                       Noise Bravo Neckband Earphones with Mic - Partner Exclusive                                     Bravo
                                                                                                                                             Noise Buds Ace Truly Wireless Earbuds                                  Buds Ace
                                                                                                                                            Noise Buds Aero Truly Wireless Earbuds                                 Buds Aero
                                                                                                                                  Noise Buds Apex Truly Wireless Bluetooth Earbuds                                 Buds Apex
                                                                                                                     Noise Buds Apex Truly Wireless Bluetooth Earbuds - Blue Tokai                                 Buds Apex
                                                                                                                     Noise Buds Apex Truly Wireless Bluetooth Earbuds - Cloud Grey                                 Buds Apex
                                                                                                                                                Noise Buds Combat Wireless Earbuds                               Buds Combat
                                                                                                                                        Noise Buds Combat X Truly Wireless Earbuds                             Buds Combat X
                                                                                                                                              Noise Buds Combat Z Wireless Earbuds                             Buds Combat Z
                                    Buds Combat Z In-Ear Truly Wireless Gaming Earbuds with 35ms Low Latency, 50H of Playtime, Instacharge (10 min = 120 min), 10mm Driver,BT v5.3                             Buds Combat Z
                                                                                                                                       Noise Buds Connect 2 Truly Wireless Earbuds                            Buds Connect 2
                                                                                                                                       Noise Buds Connect 3 Truly Wireless Earbuds                            Buds Connect 3
                                                                                                                                         Noise Buds Connect Truly Wireless Earbuds                              Buds Connect
                                                                                                                                              Noise Buds E1 Truly Wireless Earbuds                                   Buds E1
                                                                                                                                           Noise Buds Evoke Truly Wireless Earbuds                                Buds Evoke
                                                                                                                                         Noise Buds Explore Truly Wireless Earbuds                              Buds Explore
                                                                                                                                    Noise Buds F1 Truly Wireless Bluetooth Earbuds                                   Buds F1
                                                                                                                                Noise Buds Marine Truly Wireless Bluetooth Earbuds                               Buds Marine
                                                                                                                                            Noise Buds Mini Truly Wireless Earbuds                                 Buds Mini
                                                                                                                                          Noise Buds MVP102 Truly Wireless Earbuds                               Buds MVP102
                                                                                                                                          Noise Buds N1 Pro Truly Wireless Earbuds                               Buds N1 Pro
                                                                                                                           Noise Buds N1 Pro Truly Wireless Earbuds - Chrome Black                               Buds N1 Pro
                                                                                                                            Noise Buds N1 Pro Truly Wireless Earbuds - Super Saver                               Buds N1 Pro
                                                                                                                                Noise Buds N1 Pro Truly Wireless Earbuds - Unidays                               Buds N1 Pro
                                                                                                                                              Noise Buds N1 Truly Wireless Earbuds                                   Buds N1
                                                                                                                               Noise Buds N1 Truly Wireless Earbuds - Carbon Black                                   Buds N1
                                                                                                                                 Noise Buds N1 Truly Wireless Earbuds - Calm Beige                                   Buds N1
                                                                                                                               Noise Buds N1 Truly Wireless Earbuds - Forest Green                                   Buds N1
                                                                                                                      Noise Buds N1 Truly Wireless Earbuds - Healthifyme Exclusive                                   Buds N1
                                                                                                                                   Noise Buds N1 Truly Wireless Earbuds - Ice Blue                                   Buds N1
                                                                                                                                Noise Buds N2 Pro Truly Wireless Bluetooth Earbuds                               Buds N2 Pro
                                                                                                                                             Noise Buds NEO Truly Wireless Earbuds                                  Buds NEO
                                                                                                                                     Noise Buds NEO Truly Wireless Earbuds - Black                                  Buds NEO
                                                                                                                                     Noise Buds NEO Truly Wireless Earbuds - Green                                  Buds NEO
                                                                                                                                      Noise Buds NEO Truly Wireless Earbuds - Grey                                  Buds NEO
                                                                                                                                      Noise Buds NEO Truly Wireless Earbuds - Wine                                  Buds NEO
                                                                                                                                            Noise Buds Nero Truly Wireless Earbuds                                 Buds Nero
                                                                                                                                            Noise Buds Play Truly Wireless Earbuds                                 Buds Play
                                                                                                                                              Noise Buds R1 Truly Wireless Earbuds                                   Buds R1
                                                                                                                                              Noise Buds Trance 2 Wireless Earbuds                             Buds Trance 2
                                                                                                                                                Noise Buds Trance Wireless Earbuds                               Buds Trance

In [178]:
df_clean.drop(columns='product_id',inplace=True)

In [182]:
print(
    df_clean.loc[
        df_clean["brand"].str.lower().eq("boat"),
        ["product_name", "model_series"]
    ].to_string(index=False)
)

                                                                                                                                                                                          product_name                                model_series
                                         boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press Airdopes 131 Captain America Marvel Edition
                                                        boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity    Rockerz 450 Black Panther Marvel Edition
                                                      boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity  Rockerz 450 Captain America Marvel Edition
                                                                                                boAt Airdopes 100 | TWS Wireless Earbuds with 50 Hours Playback Time, Quad Microphone, IWP™ technology                                Airdopes 100
                                                                               boAt Airdopes 101 | In-Ear Earbuds with 13mm drivers, Music Up To 15 Hours, Type-C Interface, One Touch Voice Assistant                                Airdopes 101
                                                                                                                boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech                              Airdopes 101v2
                                                                                               boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers                              Airdopes 111v2
                                                                                                                boAt Airdopes 115 | Earbuds with 13mm drivers, BEAST™ Mode for Gamers, ENx™ Technology                                Airdopes 115
                                                                                                     boAt Airdopes 120 | Wireless Earbuds with 40 Hours Playback, BEAST™ Mode, ASAP™ Charge, IWP™ Tech                                Airdopes 120
                                                                                       boAt Airdopes 121 Pro Plus | Wireless Earbuds with 100 Hours Playback, 4 Mics with ENx™ Technology, BEAST™ Mode                       Airdopes 121 Pro Plus
                                                                            boAt Airdopes 121 v2 | In-Ear Earbuds v2 with 8mm driver, LED Case Battery Indicator, 380mAh Pocket Friendly Charging Case                             Airdopes 121 v2
                                                                                     boAt Airdopes 121v2 Plus | Wireless Earbuds with 50 Hours Playback, BEAST™ Mode, ENx™ Technology, IPX4 Resistance                         Airdopes 121v2 Plus
                                                                                             boAt Airdopes 125 | Wireless Earbuds with 50 Hours Playback, BEAST™ Mode, Bluetooth v5.3, ENx™ Technology                                Airdopes 125
                                                                                  boAt Airdopes 131 | Wireless Earbuds with upto 60 Hours Playback, 13mm Drivers, IWP Technology, 650mAh Charging Case                                Airdopes 131
                                                                       boAt Airdopes 131 Batman DC Edition | Wireless Earbuds with 13 mm Drivers, Bluetooth v5.0, 650mAh pocket friendly Charging Case              Airdopes 131 Batman DC Edition
                                                                                                                    Airdopes 131 DC Edition | 13 mm Drivers, Type-C Carry Case, 12 hours Nonstop Music                     Airdopes 131 DC Edition
                                                                             boAt Airdopes 131 Elite ANC | Wireless Earbuds with ANC up to 32dB, Transparency Mode, 60 Hours Playback, ENx™ Technology                      Airdopes 131 Elite ANC
                                                                                                       boAt Airdopes 131 Gen 2 | True Wireless Earbuds with 70 Hours Playback, ENx™ Tech & BEAST™ Mode                          Airdopes 131 Gen 2
                                                                                                                                                                         boAt Airdopes 131 KKR Edition                    Airdopes 131 KKR Edition
                                                                                   boAt Airdopes 131 Pro Buds | Wireless Earbuds with 40 Hours Playback, ENx™ Tech, BT v5.3, BEAST™ Mode, ASAP™ Charge                       Airdopes 131 Pro Buds
                                                                                    boAt Airdopes 131 RCB Edition | Wireless Earbuds with 13mm drivers, 12 Hours Playback, IWP Feature, Bluetooth V5.0                    Airdopes 131 RCB Edition
                                                boAt Airdopes 131 | Wireless Earbuds Superman DC Edition Earbuds with 13 mm Drivers, Upto 12 hours Nonstop Music, 650mAh Pocket Friendly Charging Case                                Airdopes 131
                                                                         boAt Airdopes 131 | Wireless Earbuds Wonder Woman DC Edition Earbuds With 13 mm Drivers, 650mAh Pocket Friendly Charging Case                                Airdopes 131
                                                                                                                    Airdopes 138 DC Edition | 13 mm Drivers, Type-C Carry Case, 12 Hours Nonstop Music                     Airdopes 138 DC Edition
                                                                                     boAt Airdopes 138 PRO | Wireless Earbuds with 11mm Drivers, ENx™ Technology, BEAST mode, 45 Hours of battery life                            Airdopes 138 PRO
                                                                                                            boAt Airdopes 141 | Wireless Earbuds with 42 Hours Playback, ENx™ Technology, BEAST™️ Mode                                Airdopes 141
                                                                                   boAt Airdopes 141 ANC | Wireless Earbuds with Active Noise Cancellation up to 32dB, 42 Hours Playback, BEAST™️ Mode                            Airdopes 141 ANC
                                                                               boAt Airdopes 141 Elite ANC | Wireless Earbuds with 42 Hours Playback, Up to 35dB ANC, BEAST™ Mode, Dual EQs, ENx™ Tech                      Airdopes 141 Elite ANC
                                                                                                   boAt Airdopes 141 Gen 2 | Wireless Earbuds with 48 Hours Playback, BEAST™ Mode, Dual EQs, ENx™ Tech                          Airdopes 141 Gen 2
                                                           boAt Airdopes 141 Neo | Wireless Earbuds with 50 Hours Playback, ENx™ Technology for clear calls, ASAP™ Charge, BEAST™ Mode, Bluetooth v5.3                            Airdopes 141 Neo
                                                                               boAt Airdopes 141 Pro Buds | Wireless Earbuds with 60H Playback, ENx™ Technology, Sleek Metallic Finish, Bluetooth v5.3                       Airdopes 141 Pro Buds
                                                                                                      boAt Airdopes 155 | Wireless Earbuds with 40 Hours Playback, ENx™ with Quad Mics, Bluetooth v5.3                                Airdopes 155
                                                          boAt Airdopes 161 | Wireless Earbuds with Massive Playback of upto 40 Hours, IPX5 Water & Sweat Resistance, IWP Technology, Type C Interface                                Airdopes 161
                                                                                                      boAt Airdopes 161 ANC Elite | Wireless Earbuds with ANC up to 32dB, ENx™ Technology, BEAST™ Mode                      Airdopes 161 ANC Elite
                                                                                     boAt Airdopes 161 ANC | Wireless Earbuds with Active Noise Cancellation up to 32dB, ENx™ Technology, ASAP™ Charge                            Airdopes 161 ANC
                                                                      boAt Airdopes 161 Deadpool Edition | Wireless Earbuds with 40 Hours Playback, ASAP™ Charge, boAt Immersive Sound, Bluetooth v5.1               Airdopes 161 Deadpool Edition
                                                                                    boAt Airdopes 161 Pro Buds | Wireless Earbuds with 50 Hours Playback, Dual Pairing, Dual Mics with ENx™ Technology                       Airdopes 161 Pro Buds
                                                                                      boAt Airdopes 161 Pro | Bluetooth Wireless Earbuds with BEAST™ Mode, ASAP™ Charge, ENx™ Technology, 10mm Drivers                            Airdopes 161 Pro
                                                                          boAt Airdopes 161 Thor Edition | Wireless Earbuds with 40 Hours Playback, ASAP™ Charge, boAt Immersive Sound, Bluetooth v5.1                   Airdopes 161 Thor Edition
                                                                                         boAt Airdopes 171 | In-Ear Earbuds with 6mm drivers, Bluetooth v5.0, Up to 13 Hours Playback, Voice Assistant                                Airdopes 171
                                                                               boAt Airdopes 172 | Wireless Earphones with 42 Hours playback with boAt’s Signature Audio Experience, ASAP™ Fast charge                                Airdopes 172
                                                                                        boAt Airdopes 173 | Wireless Earbuds with Powerful 6mm drivers, Nonstop Music Up to 13 hours, Type-C Interface                                Airdopes 173
                                                                                      boAt Airdopes 181 Pro | Wireless Earbuds with 100 Hours Playback, Quad Mics with ENx™, BEAST™ Mode, ASAP™ Charge                            Airdopes 181 Pro
                                                                                boAt Airdopes 181 Pro SS Edition | TWS Earbuds with 100 Hours Playback, Quad Mics with ENx™, BEAST™ Mode, ASAP™ Charge                 Airdopes 181 Pro SS Edition
                                                                                            boAt Airdopes 190 | Wireless Earbuds with 40 Hours of Playtime, Beast Mode, RGB Lights Featuring ENx™ tech                                Airdopes 190
                                                                                boAt Airdopes 200 Plus | Wireless Earbuds with 100 Hours Large Playback, BEAST™ Mode, ENx™ Technology, IPX5 Resistance                           Airdopes 200 Plus
                                                                                     boAt Airdopes 201 | TWS Wireless Earbuds for Sports & Workout, 10mm Drivers, Voice Assistant with Google and Siri                                Airdopes 201
                                                                                boAt Airdopes 207 | Wireless Earbuds with 50 Hours Playback, Quad Mics with ENx™ Technology, 13mm Drivers, BEAST™ Mode                                Airdopes 207
                                                                                                               boAt Airdopes 213 | Wireless Earbuds with 50 Hours Playback, BEAST™ Mode & ENx™ Calling                                Airdopes 213
                                                                                                               boAt Airdopes 219 | Wireless Earbuds with 40 Hours Playback, BEAST™ Mode & ENx™ Calling                                Airdopes 219
                                                                                                  boAt Airdopes 280 ANC | Wireless Earbuds with ANC up to 32dB, Quad Mics ENx™ Tech, 60 Hours Playback                            Airdopes 280 ANC
                                                                               boAt Airdopes 281 | TWS Wireless Earbuds with 6mm Drivers, Bluetooth V5.0, 14 Hours Nonstop Music, 420mAh Charging Case                                Airdopes 281
                                                                        boAt Airdopes 281 Pro | Wireless Earbuds with 4 Mics, ASAP™ Charge, 6mm Drivers, 32 Hours Nonstop Audio Bliss, ENx™ Technology                            Airdopes 281 Pro
                                                                                      boAt Airdopes 300 | Wireless Earbuds with 50 Hours Playback, Quad Mics AI ENx™ Tech, ASAP™ Charge, Spatial Audio                                Airdopes 300
                                                                              boAt Airdopes 301 | Wireless Earbuds with 75 Hours Playback, ENx™ Technology, 10mm Drivers, BEAST™ Mode, IWP™ Technology                                Airdopes 301
                                                                            boAt Airdopes 311 PRO | Wireless Earbuds with 50 Hours Playback, Dual Mics with ENx™ Technology, BEAST™ Mode, ASAP™ Charge                            Airdopes 311 PRO
                                                                                       boAt Airdopes 313 | Wireless Earbuds with 75 Hours Playback, Quad Mics ENx™, BEAST™ Mode & boAt Signature Sound                                Airdopes 313
                                                                                  boAt Airdopes 381 | Bluetooth In-Ear Wireless Earbuds with 7mm Rhythmic Dynamic Drivers, Nonstop Music UpTo 20 Hours                                Airdopes 381
                                                                                           boAt Airdopes 381 MKI | Bluetooth Wireless Earbuds with 7mm Driver, Upto 20 Hours Playback, IPX5 Technology                            Airdopes 381 MKI
                                                                                 boAt Airdopes 383 | Wireless Earbuds with 7mm Rhythmic Dynamic Drivers, Up to 20 hours Playback, 500mAh Charging Case                                Airdopes 383
                                                                                    boAt Airdopes 391 | Wireless Earbuds with 6mm Drivers, Qualcomm® cVc™ Call Noise Isolation, aptX™ Audio Technology                                Airdopes 391
                                                                                                      boAt Airdopes 393 ANC | Bluetooth Earbuds with 30 Hours of Playtime, Beast Mode, ENx™ technology                            Airdopes 393 ANC
                                                                              boAt Airdopes 402 | Wireless Earbuds with Powerful 10mm Drivers, ENx™️ Technology, ASAP Charge, 30Hours of Playback Time                                Airdopes 402
                                                     boAt Airdopes 411 ANC | Noise-Cancelling Earbuds with 10mm Drivers, ASAP™ Charge Technology, Up to 25dB ANC, ENx™ Technology, 17.5 Hours Playback                            Airdopes 411 ANC
                                                                        boAt Airdopes 418 ANC | Wireless Earbuds with 10mm Drivers, Up to 25dB ANC, ENx™ Technology, 17.5 Hours Playback, ASAP™ Charge                            Airdopes 418 ANC
                                                                                  boAt Airdopes 431 | Wireless Earbuds 7mm Drivers, IPX4 Sweat & Water Resistance, Bluetooth 5.0, 500mAh Charging Case                                Airdopes 431
                                                                                      boAt Airdopes 441 | Wireless Earbuds with 6mm Driver, Nonstop Music Upto 20 Hours, IPX7 Water & Sweat Resistance                                Airdopes 441
                                                                    boAt Airdopes 441 KKR Edition | Wireless Earbuds with 6mm Drivers & boAt Signature Sound, 20 Hours Playback, IPX7 Water Resistance                    Airdopes 441 KKR Edition
                                                               boAt Airdopes 441 | Wireless Earbuds with 6mm Drivers, IPX7 Water & Sweat Resistance, 500mAh Charging Case, Nonstop Music Upto 20 Hours                                Airdopes 441
                                                                          boAt Airdopes 441 Pro | Wireless Earbuds with 6mm drivers, IWP technology, Bluetooth 5.0, 2600mAh carry case,Voice Assistant                            Airdopes 441 Pro
                                     boAt Airdopes 441 Pro Special Batman Edition | Wireless Earbuds with 2600 mAh Carry Case, 6mm Drivers, Upto 20 Hours nonstop Music, IPX7 Sweat & Water Resistance     Airdopes 441 Pro Special Batman Edition
                                                                                   boAt Airdopes 443 | Wireless Earbuds with 6mm drivers, IWP Technology, Upto 20 Hours Playback, 500mAh Charging Case                                Airdopes 443
                                                                           boAt Airdopes 451v2 | Wireless Earbuds with 10mm drivers, Dual mic with ENx Technology, 25 Hours Playback, Type-C Interface                              Airdopes 451v2
                                                                          boAt Airdopes 452 | TWS Earbuds with 6mm Drivers, 380mAh Charging Case, ENx™ Technology, BEAST Mode for Gamers, ASAP™ Charge                                Airdopes 452
                                                                                               boAt Airdopes 458 | Wireless Earbuds with 30 Hours Playback, BEAST™ Mode, ENx™ Technology, ASAP™ Charge                                Airdopes 458
                                                                                  boAt Airdopes 461 | True Wireless Bluetooth Earbuds, Upto 46 Hours Playback, ASAP™ Fast Charge, 600mAh Charging Case                                Airdopes 461
                                                                                             boAt Airdopes 491 | Wireless Earbuds with 6mm Drivers, 50 Hours Playback, Bluetooth v5.0, 1800mAh battery                                Airdopes 491
                                                        boAt Airdopes 500 ANC | Wireless Earbuds with 35dB Hybrid Active Noise Cancellation, 8mm Drivers, Quad Mics with ENx™ Technology, ASAP™ Charge                            Airdopes 500 ANC
                                                                                  boAt Airdopes 501 ANC | ANC wireless Earbuds with Dual Mics with ENx Technology, BEAST™ for Low Latency, 8mm Drivers                            Airdopes 501 ANC
                                                                              boAt Airdopes 511 V2 | TWS Earbuds with 6mm Drivers, boAt Signature Sound, Upto 30 hours Playback, 500 mAh Charging Case                             Airdopes 511 V2
                                                                                      Airdopes 601 ANC | Wireless Earbuds with 10mm Drivers, Hybrid Active Noise Cancelling, Type C charging Interface                            Airdopes 601 ANC

In [191]:
df_clean = df_clean.drop(index=357)

In [192]:
df_clean = df_clean.reset_index(drop=True)

In [193]:
df_clean.head(1)

  brand                                                                                                                                                   product_name               category product_type  sale_price_min_inr  sale_price_max_inr  mrp_inr  discount_percent  num_variants         colors           skus  in_stock_variants                                                                                                                                                                                                                                                                                                                                                       tags_raw                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       features_raw specs_raw_json                                                                                                                                                                                                                                                                                                                                description_raw                 created_at                 updated_at               published_at         base_product    edition_type                                 model_series
0  boAt  boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press  True Wireless Earbuds          TWS              1599.0              1599.0   2990.0              46.5             1  Captains Blue  8904130881640                  0  Airdopes | all prods | All products | allprod | Audio-Category | Collectibles | Country Code: CN | flash-sale | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Limited Edition Earbuds | Marvel | meta-label-exclusive | Super Savers | SuperHero | Superrr | TWS  Airdopes | all prods | All products | allprod | Audio-Category | Collectibles | Country Code: CN | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Limited Edition Earbuds | Marvel | Super Savers | SuperHero | Superrr | TWS | Dope Dead Gorgeous! | Airdopes 131 | boAt Signature Sound | 13mm Audio Drivers | 60 Hours Total | Playback | 3 Hours Per Charge | 60 Hours With Case | IWP Technology | With Bluetooth v5.0 | Lightweight Build | With Type C Charging | Voice Assistant | On Single Press | Multifunctional Controls            NaN  Dope Dead Gorgeous! | Airdopes 131 | ©Marvel | boAt Signature Sound | 13mm Audio Drivers | ©Marvel | Upto | 60 Hours Total | Playback | 3 Hours Per Charge | 60 Hours With Case | IWP Technology | With Bluetooth v5.0 | ©Marvel | Lightweight Build | With Type C Charging | Voice Assistant | On Single Press | Multifunctional Controls |   2021-12-17T12:51:55+05:30  2026-09-23T22:08:12+05:30  2021-12-20T15:26:49+05:30  131-captain-america  Marvel Edition  Airdopes 131 Captain America Marvel Edition

In [201]:
df_clean['base_product'].to_string()

'0                                                                                                                         131-captain-america\n1                                                                                                                           450-black-panther\n2                                                                                                                         450-captain-america\n3                                                                                                               airdopes-100-wireless-earbuds\n4                                                                                                                  airdopes-101-made-in-india\n5                                                                                                             airdopes-101v2-wireless-earbuds\n6                                                                                                             airdopes-111v2-wireless-earbuds\n7                                                                                                     airdopes-115-wireless-bluetooth-earbuds\n8                                                                                                               airdopes-120-wireless-earbuds\n9                                                                                                               airdopes-121-pro-plus-earbuds\n10                                                                                                                            airdopes-121-v2\n11                                                                                                                airdopes-121v2-plus-earbuds\n12                                                                                                              airdopes-125-wireless-earbuds\n13                                                                                                                               airdopes-131\n14                                                                                                             airdopes-131-batman-dc-edition\n15                                                                                                     airdopes-131-dc-edition-earbuds-online\n16                                                                                                             airdopes-131-elite-anc-earbuds\n17                                                                                                   airdopes-131-gen-2-true-wireless-earbuds\n18                                                                                                                   airdopes-131-kkr-edition\n19                                                                                                                      airdopes-131-pro-buds\n20                                                                                                                   airdopes-131-rcb-edition\n21                                                                                                              airdopes-131-superman-edition\n22                                                                                                       airdopes-131-wonder-woman-dc-edition\n23                                                                                                   airdopes-138-dc-edition-wireless-earbuds\n24                                                                                                         airdopes-138-pro-bluetooth-earbuds\n25                                                                                                                               airdopes-141\n26                                                                                                                   airdopes-141-anc-earbuds\n27                                                                                                    airdopes-141-elite-anc-wireless-earbuds\n28                                                                                                         airdopes-141-gen2-wireless-earbuds\n29                                                                                                          airdopes-141-neo-wireless-earbuds\n30                                                                                                                      airdopes-141-pro-buds\n31                                                                                                         airdopes-155-long-playback-earbuds\n32                                                                                                                               airdopes-161\n33                                                                                                             airdopes-161-anc-elite-earbuds\n34                                                                                                          airdopes-161-anc-wireless-earbuds\n35                                                                                                              airdopes-161-deadpool-edition\n36                                                                                                                      airdopes-161-pro-buds\n37                                                                                                airdopes-161-pro-wireless-bluetooth-earbuds\n38                                                                                                                  airdopes-161-thor-edition\n39                                                                                                                               airdopes-171\n40                                                                                                              airdopes-172-wireless-earbuds\n41                                                                                                                               airdopes-173\n42                                                                                                         airdopes-181-pro-bluetooth-earbuds\n43                                                                                                          airdopes-181-pro-wireless-earbuds\n44                                                                                                              airdopes-190-wireless-earbuds\n45                                                                                                   airdopes-200-plus-large-playback-earbuds\n46                                                                                                                               airdopes-201\n47                                                                                                              airdopes-207-wireless-earbuds\n48                                                                                                              airdopes-213-wireless-earbuds\n49                                                                                                              airdopes-219-wireless-earbuds\n50                                                                                                          airdopes-280-anc-wireless-earbuds\n51                                                                                                                               airdopes-281\n52                                                                                                                           airdopes-281-pro\n53                                                                                                        airdopes-300-large-playback-earbuds\n54                                                                                                                               airdopes-301\n55                                                                                                          airdopes-311-pro-wireless-earbuds\n56                                                                                                              airdopes-313-wireless-earbuds\n57                                                                                                                               airdopes-381\n58                                                                                                          airdopes-381-mki-wireless-earbuds\n59                                                                                                                               airdopes-383\n60                                                                                                                               airdopes-391\n61                                                                                                         airdopes-393-anc-bluetooth-earbuds\n62                                                                                                                               airdopes-402\n63                                                                                                                           airdopes-411-anc\n64     airdopes-418-anc-noise-cancelling-earbuds-with-10mm-drivers-asaptm-charge-technology-up-to-25db-anc-enx-technology-17-5-hours-playback\n65                                                                                                                               airdopes-431\n66                                                                                                                               airdopes-441\n67                                                                                                                   airdopes-441-kkr-edition\n68                                                                                                                 airdopes-441-made-in-india\n69                                                                                                                           airdopes-441-pro\n70                                                                                                                airdopes-441-pro-dc-edition\n71                                                                                                                               airdopes-443\n72                                                                                                                             airdopes-451v2\n73                                                                                                                               airdopes-452\n74                                                                                                                               airdopes-458\n75                                                                                                                               airdopes-461\n76                                                                                                                               airdopes-491\n77                                                                                                                           airdopes-500-anc\n78                                                                                                                           airdopes-501-anc\n79                                                                                                                            airdopes-511-v2\n80                                                                                                                           airdopes-601-anc\n81                                                                                                                               airdopes-621\n82                                                                                                                               airdopes-641\n83                                                                                                          airdopes-71-long-playback-earbuds\n84                                                                                                                               airdopes-711\n85                                                                                                                        airdopes-800-hi-def\n86                                                                                                          airdopes-91-long-playback-earbuds\n87                                                                                                    airdopes-91-prime-long-playback-earbuds\n88                                                                                                                               airdopes-ace\n89                                                                                                   airdopes-ace-gen-2-true-wireless-earbuds\n90                                                                                                            airdopes-alpha-deadpool-edition\n91                                                                                                       airdopes-alpha-true-wireless-earbuds\n92                                                                                                     airdopes-atom-81-long-playback-earbuds\n93                                                                                                 airdopes-atom-81-pro-long-playback-earbuds\n94                                                                                                             airdopes-beat-wireless-earbuds\n95                                                                                                        airdopes-bliss-wireless-anc-earbuds\n96                                                                                                            airdopes-crude-wireless-earbuds\n97                                                                                                            airdopes-drift-wireless-earbuds\n98                                                                                                  airdopes-flex-454-noise-cancelling-earbud\n99                                                                                                     airdopes-fuel-premium-wireless-earbuds\n100                                                                                                   airdopes-genesis-large-playback-earbuds\n101                                                                                                       airdopes-hype-long-playback-earbuds\n102                                                                                                      airdopes-immortal-141-gaming-earbuds\n103                                                                                                                           airdopes-joy-v2\n104                                                                                                             airdopes-joy-wireless-earbuds\n105                                                                                                       airdopes-kick-long-playback-earbuds\n106                                                                                                                             airdopes-loop\n107                                                                                                             airdopes-max-wireless-earbuds\n108                                                                                              airdopes-plus-318-bluetooth-wireless-earbuds\n109                                                                                                       airdopes-prime-412-wireless-earbuds\n110                                                                                                       airdopes-prime-511-wireless-earbuds\n111                                                                                                   airdopes-prime-513-anc-wireless-earbuds\n112                                                                                                   airdopes-prime-700-anc-wireless-earbuds\n113                                                                                                   airdopes-prime-701-anc-wireless-earbuds\n114                                                                                                                          airdopes-proclip\n115                                                                                                      airdopes-sonik-long-playback-earbuds\n116                                                                                                    airdopes-supreme-long-playback-earbuds\n117                                                                                                airdopes-ultra-plus-large-playback-earbuds\n118                                                                                                  airdopes-ultra-pro-long-playback-earbuds\n119                                                                                                      airdopes-unity-anc-bluetooth-earbuds\n120                                                                                                       airdopes-zing-long-playback-earbuds\n121                                                                                                          airwave-max-3-wireless-headphone\n122                                                                                                          airwave-max-4-wireless-headphone\n123                                                                                                                             bassheads-100\n124                                                                                                            bassheads-100-c-wired-earphone\n125                                                                                                               bassheads-100-make-in-india\n126                                                                                                                 bassheads-100-rcb-edition\n127                                                                                                                             bassheads-102\n128                                                                                                                             bassheads-103\n129                                                                                                                             bassheads-104\n130                                                                                                                             bassheads-105\n131                                                                                                                             bassheads-110\n132                                                                                                                             bassheads-122\n133                                                                                                          bassheads-122-anc-wired-earphone\n134                                                                                                                             bassheads-132\n135                                                                                                                             bassheads-152\n136                                                                                                                 bassheads-152-kkr-edition\n137                                                                                                                             bassheads-162\n138                                                                                                                          bassheads-162-v2\n139                                                                                                                       

In [210]:
df_clean['category'].value_counts(dropna=False)

category
True Wireless Earbuds    334
Neckband                 114
Headphones                76
Wired Earphones           43
Name: count, dtype: int64

In [215]:
df_clean[df_clean['brand']=='boAt']['category'].value_counts()

category
True Wireless Earbuds    209
Neckband                  83
Headphones                65
Wired Earphones           40
Name: count, dtype: int64

In [219]:
df_clean['product_type'].value_counts(dropna=False)

product_type
TWS                    203
Wireless Earbuds       120
Rockerz In-Ear          78
Rockerz                 63
Bassheads               44
Wireless Earphones      31
Wireless Headphones     16
BH-onear                 8
Wired Earphones          3
VAS                      1
Name: count, dtype: int64

In [220]:
df_clean.drop(columns=["product_type"],inplace=True)

In [222]:
print(df_clean['sale_price_max_inr'].isna().sum())
print(df_clean['sale_price_min_inr'].isna().sum())
print(df_clean['mrp_inr'].isna().sum())

0
0
0

In [224]:
df_clean[['sale_price_max_inr','sale_price_min_inr']]

     sale_price_max_inr  sale_price_min_inr
0                1599.0              1599.0
1                1799.0              1799.0
2                1799.0              1799.0
3                1099.0              1099.0
4                1199.0              1199.0
..                  ...                 ...
562              1499.0              1499.0
563              1499.0              1499.0
564              1099.0              1099.0
565               399.0               399.0
566              1099.0              1099.0

[567 rows x 2 columns]

In [238]:
df_clean.loc[[221, 565], ["product_name", "colors", "num_variants", "skus"]]

                                                                                                                                                 product_name     colors  num_variants        skus
221  boAt Standalone Crest AI Pack | Voice-First AI Companion Built with Google Gemini (Your Crest AI Subscription will be activated shortly after purchase.)  12 Months             1  S000000006
565                                                                                                                                      boAt Crest AI (Test)  12 Months             1         NaN

In [236]:
pd.set_option('display.max_rows', None)

In [240]:
import numpy as np
df_clean.loc[[221, 565], "colors"] = np.nan

In [244]:
(
    (df_clean["mrp_inr"] - df_clean["sale_price_min_inr"])
    / df_clean["mrp_inr"] * 100
).round(1).eq(df_clean["discount_percent"]).value_counts()

True    567
Name: count, dtype: int64

In [248]:
df_clean.drop(columns='in_stock_variants',inplace=True)

In [253]:
(df_clean['published_at']==df_clean['created_at']).value_counts()

False    560
True       7
Name: count, dtype: int64

In [254]:
df_clean.drop(columns=['created_at','updated_at'],inplace=True)

In [255]:
df_clean.columns

Index(['brand', 'product_name', 'category', 'sale_price_min_inr', 'sale_price_max_inr', 'mrp_inr', 'discount_percent', 'num_variants', 'colors', 'skus', 'tags_raw', 'features_raw', 'specs_raw_json', 'description_raw', 'published_at', 'base_product', 'edition_type', 'model_series'], dtype='str')

In [257]:
df_clean.to_csv("boat_noise_cleaned_v1.csv", index=False)

In [259]:
df_clean["published_at"].dtype

In [261]:
df_clean["published_at"]=pd.to_datetime(
    df_clean["published_at"].str[:10]
)

In [263]:
df_clean["published_at"].isna().sum()

np.int64(3)

In [264]:
df_clean["published_at"].dtype

dtype('<M8[us]')

In [267]:
df_clean["published_year"] = df_clean["published_at"].dt.year.astype("Int64")
df_clean["published_month"] = df_clean["published_at"].dt.month.astype("Int64")

In [269]:
df_clean["colors"] = df_clean["colors"].str.strip()

In [271]:
df_clean["color_count"] = (
    df_clean["colors"]
    .str.split("|")
    .str.len()
)

In [275]:
df_clean[~(df_clean['num_variants']==df_clean['color_count'])].shape

(3, 21)

In [276]:
df_clean.loc[
    df_clean["num_variants"] != df_clean['color_count'],
    ["product_name", "num_variants", "colors", "skus"]
]

                                                                                                                                                 product_name  num_variants colors                           skus
221  boAt Standalone Crest AI Pack | Voice-First AI Companion Built with Google Gemini (Your Crest AI Subscription will be activated shortly after purchase.)             1    NaN                     S000000006
310                                            boAt Nirvanaa Uno | Wired Earphone with Mic, 8mm Drivers, Superior Coated Cable, 3.5mm Angled Jack, Secure Fit             2  Black  8904130845307 | 8904130841446
565                                                                                                                                      boAt Crest AI (Test)             1    NaN                            NaN

In [277]:
df_clean.drop(index=565,inplace=True)

In [316]:
df_clean['edition_type'].value_counts(dropna=False)

edition_type
NaN               521
DC                 10
Sunburn             8
Marvel              6
KKR                 6
SS                  3
Limited             3
RCB                 2
Special             2
Dhruv Kapoor        2
Wrogn               1
Netflix Stream      1
Naruto              1
Name: count, dtype: int64

In [311]:
df_clean[df_clean['product_name'].str.contains('Edition')]['product_name']

0          boAt Airdopes 131 Captain America Marvel Edition | Wireless Earbuds with 13mm Audio Drivers, IWP Technology, Type C Charging, Voice Assistant On Single Press
1                         boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
2                       boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity
14                                       boAt Airdopes 131 Batman DC Edition | Wireless Earbuds with 13 mm Drivers, Bluetooth v5.0, 650mAh pocket friendly Charging Case
15                                                                                    Airdopes 131 DC Edition | 13 mm Drivers, Type-C Carry Case, 12 hours Nonstop Music
18                                                                                                                                         boAt Airdopes 131 KKR Edition
20                                                    boAt Airdopes 131 RCB Edition | Wireless Earbuds with 13mm drivers, 12 Hours Playback, IWP Feature, Bluetooth V5.0
21                boAt Airdopes 131 | Wireless Earbuds Superman DC Edition Earbuds with 13 mm Drivers, Upto 12 hours Nonstop Music, 650mAh Pocket Friendly Charging Case
22                                         boAt Airdopes 131 | Wireless Earbuds Wonder Woman DC Edition Earbuds With 13 mm Drivers, 650mAh Pocket Friendly Charging Case
23                                                                                    Airdopes 138 DC Edition | 13 mm Drivers, Type-C Carry Case, 12 Hours Nonstop Music
35                                      boAt Airdopes 161 Deadpool Edition | Wireless Earbuds with 40 Hours Playback, ASAP™ Charge, boAt Immersive Sound, Bluetooth v5.1
38                                          boAt Airdopes 161 Thor Edition | Wireless Earbuds with 40 Hours Playback, ASAP™ Charge, boAt Immersive Sound, Bluetooth v5.1
43                                                boAt Airdopes 181 Pro SS Edition | TWS Earbuds with 100 Hours Playback, Quad Mics with ENx™, BEAST™ Mode, ASAP™ Charge
67                                    boAt Airdopes 441 KKR Edition | Wireless Earbuds with 6mm Drivers & boAt Signature Sound, 20 Hours Playback, IPX7 Water Resistance
70     boAt Airdopes 441 Pro Special Batman Edition | Wireless Earbuds with 2600 mAh Carry Case, 6mm Drivers, Upto 20 Hours nonstop Music, IPX7 Sweat & Water Resistance
90                                   boAt Airdopes Alpha Deadpool Edition | Wireless Earbuds with boAt Signature Sound, 35 Hours Playback, ASAP™ Charge, ENx™ Technology
126                                                boAt Bassheads 100 RCB Edition | Limited Edition RCB Design Wired Earphones, 10mm Dynamic Drivers, In-line Microphone
136                                                                                                                                       boAt Bassheads 152 KKR Edition
140                                                                                                                                       boAt Bassheads 172 KKR Edition
166                                                                  boAt Airdopes 118 Wrogn Edition| Earbuds with 10mm drivers, BEAST™ Mode for Gamers, ENx™ Technology
186                                                                                                                                    boAt Airdopes 381 Sunburn Edition
187                                                                                                                                    boAt Airdopes 383 Sunburn Edition
189                                                boAt Airdopes 411 ANC | Netflix Stream Edition Earbuds, Active Noise Cancellation, ENx™️ Technology, Gesture Controls
192                                                                                                                                    boAt Airdopes 441 Sunburn Edition
208                                                                     boAt Airdopes ProClip SS Edition | Open-Ear Earbuds with 52 Hours Playback & Air Conduction Tech
212                                                                                                                                   boAt Bassheads 152 Sunburn Edition
213                                                                                                                                   boAt Bassheads 172 Sunburn Edition
225                                                Nirvana Eutopia - Dhruv Kapoor Edition | Wireless Headphone with 20H Playback, Dual Mics with ENx™ Tech, ASAP™ Charge
226                             boAt Nirvana Ion ANC Limited Edition | Wireless Earbuds with Active Noise Cancellation, ENx™ Technology, 120 Hours Playback, BEAST™ Mode
227                                                             Nirvana Ivy - Dhruv Kapoor Edition | Wireless Earbuds, 50 Hours Playback, 50dB ANC, boAt Signature Sound
230                       boAt Nirvana Zenith Pro SS Edition | TWS Earbuds with Spatial Audio, 80H Playback & 50dB Hybrid Adaptive ANC "Awarded Best TWS by Gadgets 360"
251                                                           boAt Rockerz 460 Naruto Edition | Naruto Series – Wireless Headphones with 30 Hours Playback & BEAST™ Mode
253                                   boAt Rockerz 550 Sunburn Edition | Wireless Headphone with Bluetooth v5.0, 20 Hours Playback, 500mAh battery, 50mm dynamic drivers
254                                             boAt Rockerz 650 DC Edition | Bluetooth Headphone with 40mm Dynamic Drivers, 60HRS Playback, ASAP™ Charge, Dual EQ Modes
255                                            boAt Rockerz 650 Sunburn Edition | Wireless Headphone with 40mm dynamic drivers, 60H Playback, ASAP Charge, Dual EQ Modes
304                            boAt Nirvana ION ANC Limited Edition | Bluetooth Earbuds with Active Noise Cancellation, ENx™ Technology, 120 Hours Playback, BEAST™ Mode
335                                                                                                               Noise Airwave Max 5 Headphone - Limited Edition - Deal
460                                                                                                           Noise Master Buds Truly Wireless Earbuds - Special Edition
500                                           boAt Rockerz 255 KKR Edition | Equipped with 10mm Drivers, Limited Edition KKR Design, 6H Nonstop Playback, 110mAh Battery
532                                          boAt Rockerz 450 Batman DC Edition | Bluetooth Wireless Headphone with 40 mm Drivers HD Immersive Audio, Power Up For 15HRS
533                                      boAt Rockerz 450 DC Edition | Wireless Bluetooth Headphone with 40mm Dynamic Drivers, Upto 15 Hours Playback, Adaptive Headband
536                             boAt Rockerz 450 Superman DC Edition | Wireless Bluetooth Headphone with 40mm Dynamic Drivers, Upto 15 Hours Playback, Adaptive Headband
537                         boAt Rockerz 450 Wonder Woman DC Edition | Wireless Bluetooth Headphone with 40mm Dynamic Drivers, Upto 15 Hours Playback, Adaptive Headband
545                                         boAt Rockerz 558 Sunburn Edition | Wireless Headphone with 20 Hours Playback, 50mm Dynamic Drivers, Physical Noise Isolation
549                                                     boAt Rockerz 600 KKR Edition | Wireless Headphone with Bluetooth v4.1, 8H Playback, 40mm drivers, 300mAh battery
Name: product_name, dtype: str

In [287]:
df_clean["edition_type"] = (
    df_clean["product_name"]
    .str.extract(
        r"(?i)(Marvel|DC|RCB|KKR|Sunburn|Naruto|Wrogn|Dhruv Kapoor|Netflix Stream)"
    )[0]
)

In [310]:
df_clean['edition_type'].value_counts(dropna=False)

edition_type
NaN               525
DC                 10
Sunburn             8
KKR                 6
Marvel              5
Limited             3
RCB                 2
Special             2
Dhruv Kapoor        2
Wrogn               1
Netflix Stream      1
Naruto              1
Name: count, dtype: int64

In [ ]:
df_clean.loc[[226, 304], "edition_type"] = "Limited"
df_clean.loc[[460, 70], "edition_type"] = "Special"

In [297]:
df_clean.loc[[335], "edition_type"] = "Limited"

In [301]:
df_clean.loc[355,'edition_type']=np.nan

In [309]:
df_clean.loc[[35,90],'edition_type']='Marvel'

In [314]:
df_clean[df_clean["product_name"].str.contains("Edition", case=False, na=False) & df_clean["edition_type"].isna()]

    brand                                                                                                                                    product_name               category  sale_price_min_inr  sale_price_max_inr  mrp_inr  discount_percent  num_variants                                                        colors                                                           skus                                                                                                                                                                                                                                                                                                                                    tags_raw                                                                                                                                                                                                                                                                                                                          features_raw                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      specs_raw_json    description_raw published_at                        base_product edition_type                   model_series  published_year  published_month  color_count
38   boAt                    boAt Airdopes 161 Thor Edition | Wireless Earbuds with 40 Hours Playback, ASAP™ Charge, boAt Immersive Sound, Bluetooth v5.1  True Wireless Earbuds               899.0               899.0   2490.0              63.9             1                                                 Electric Blue                                                  8905650053326  Audio-Category | best-seller-sec | Bluetooth Earphones | Country Code: CN | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Large Playback Earbuds | Marvel 2.0 | meta-label-exclusive | Snapmint | SuperHero | TopPicks | Travel Earbuds | TWS  Audio-Category | best-seller-sec | Bluetooth Earphones | Country Code: CN | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Large Playback Earbuds | Marvel 2.0 | Snapmint | SuperHero | TopPicks | Travel Earbuds | TWS | specifications  {"Category": "`+ cat_name + `", "Net Content": "`+ content_spec +`", "For Consumer Complaints": "022-6918-1920 info@imaginemarketingindia.com Imagine Marketing Limited Address: Unit No. 204&205, D-wing & E-wing, Corporate Avenue, Andheri Ghatkopar Link Road, Andheri East, Mumbai-400093", "Net Quantity": "1 Unit", "${appended_text}Marketed By": "Imagine Marketing Limited", "Address": "Unit No. 204&205, D-wing & E-wing, Corporate Avenue, Andheri Ghatkopar Link Road, Andheri East, Mumbai-400093"}  specifications |    2023-09-25           airdopes-161-thor-edition          NaN      Airdopes 161 Thor Edition            2023                9          1.0
43   boAt                          boAt Airdopes 181 Pro SS Edition | TWS Earbuds with 100 Hours Playback, Quad Mics with ENx™, BEAST™ Mode, ASAP™ Charge  True Wireless Earbuds              1399.0              1459.0   4990.0              72.0             4  Lilac Serenity | Coral Bloom | Mocha Elegance | Frosted Mint  8905650077391 | 8905650077414 | 8905650077384 | 8905650077407                                                                                                                                                                                                                                                                                       Coupon-300|BIG300 | nofollow | st-hide | Super Savers                                                                                                                                                                                                                                                                                    nofollow | st-hide | Super Savers | specifications  {"Category": "`+ cat_name + `", "Net Content": "`+ content_spec +`", "For Consumer Complaints": "022-6918-1920 info@imaginemarketingindia.com Imagine Marketing Limited Address: Unit No. 204&205, D-wing & E-wing, Corporate Avenue, Andheri Ghatkopar Link Road, Andheri East, Mumbai-400093", "Net Quantity": "1 Unit", "${appended_text}Marketed By": "Imagine Marketing Limited", "Address": "Unit No. 204&205, D-wing & E-wing, Corporate Avenue, Andheri Ghatkopar Link Road, Andheri East, Mumbai-400093"}  specifications |    2025-05-16   airdopes-181-pro-wireless-earbuds          NaN    Airdopes 181 Pro SS Edition            2025                5          4.0
208  boAt                                                boAt Airdopes ProClip SS Edition | Open-Ear Earbuds with 52 Hours Playback & Air Conduction Tech  True Wireless Earbuds              2199.0              2299.0   4999.0              56.0             3                         Velvet Wine | Silk Grey | Satin White                  8905650133530 | 8905650132427 | 8905650132434                                                                                                                                                                                                                                                                                      nofollow | Recently-Restocked | st-hide | Super Savers                                                                                                                                                                                                                                                                                nofollow | Recently-Restocked | st-hide | Super Savers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 NaN                NaN   2026-09-01    boat-airdopes-proclip-ss-edition          NaN    Airdopes ProClip SS Edition            2026                9          3.0
230  boAt  boAt Nirvana Zenith Pro SS Edition | TWS Earbuds with Spatial Audio, 80H Playback & 50dB Hybrid Adaptive ANC "Awarded Best TWS by Gadgets 360"  True Wireless Earbuds              3599.0              3599.0  14990.0              76.0             3                     Velvet Grey | Platinum Gold | Crimson Red                  8905650102741 | 8905650102758 | 8905650102765                                                                                                                                                                                                                                                                                                           nofollow | st-hide | Super Savers                                                                                                                                                                                                                                                                                    nofollow | st-hide | Super Savers | specifications  {"Category": "`+ cat_name + `", "Net Content": "`+ content_spec +`", "For Consumer Complaints": "022-6918-1920 info@imaginemarketingindia.com Imagine Marketing Limited Address: Unit No. 204&205, D-wing & E-wing, Corporate Avenue, Andheri Ghatkopar Link Road, Andheri East, Mumbai-400093", "Net Quantity": "1 Unit", "${appended_text}Marketed By": "Imagine Marketing Limited", "Address": "Unit No. 204&205, D-wing & E-wing, Corporate Avenue, Andheri Ghatkopar Link Road, Andheri East, Mumbai-400093"}  specifications |    2026-07-30  boat-nirvana-zenith-pro-ss-edition          NaN  Nirvana Zenith Pro SS Edition            2026                7          3.0

In [315]:
df_clean.loc[[43,208,230],'edition_type']='SS'
df_clean.loc[38,'edition_type']='Marvel'

In [317]:
df_clean['edition_type'].value_counts()

edition_type
DC                10
Sunburn            8
Marvel             6
KKR                6
SS                 3
Limited            3
RCB                2
Special            2
Dhruv Kapoor       2
Wrogn              1
Netflix Stream     1
Naruto             1
Name: count, dtype: int64

In [318]:
df_clean["edition_type"] = df_clean["edition_type"].replace({
    "Marvel": "Franchise",
    "DC": "Franchise",
    "Naruto": "Franchise",

    "RCB": "Sports",
    "KKR": "Sports",

    "Sunburn": "Collaboration",
    "Dhruv Kapoor": "Collaboration",
    "Wrogn": "Collaboration",
    "Netflix Stream": "Collaboration",

    "SS": "Super Saver",
    "Limited": "Limited",
    "Special": "Special"
})

df_clean["edition_type"] = df_clean["edition_type"].fillna("Standard")

In [319]:
df_clean['edition_type'].value_counts()

edition_type
Standard         521
Franchise         17
Collaboration     12
Sports             8
Super Saver        3
Limited            3
Special            2
Name: count, dtype: int64

In [320]:
df_clean[df_clean['brand']=='Noise']['edition_type'].value_counts()

edition_type
Standard    168
Limited       1
Special       1
Name: count, dtype: int64

In [322]:
df_clean.drop(columns=["skus"],inplace=True)

In [332]:
mask = df_clean["model_series"].str.contains("Airdopes", case=False, na=False)

df_clean.loc[mask, "model_series"] = "Airdopes"

In [328]:
df_clean.drop(index=564,inplace=True)

In [337]:
df_clean['model_series'].value_counts()

model_series
Airdopes                    166
Rockerz                     125
Buds                        123
Bassheads                    47
Nirvana                      28
Immortal                     24
Airwave                      16
Air Clips                     4
Tune                          4
Wireless Series               3
Bravo                         3
Chord                         3
Nerve                         3
Flair                         2
Pure Pods                     2
Standalone Crest AI Pack      1
Sailor Play                   1
Beads                         1
Blaze                         1
Clutch HP-P01                 1
Combat                        1
X KableOne                    1
Powr                          1
Sense                         1
TWO                           1
Xtreme                        1
Rockid Rush                   1
Name: count, dtype: int64

In [334]:
families = {
    "Rockerz": "Rockerz",
    "Bassheads": "Bassheads",
    "Immortal": "Immortal",
    "Nirvana": "Nirvana",
    "Nirvanaa": "Nirvana",
    "Air Buds": "Air Buds",
    "Air Clips": "Air Clips",
    "Airwave": "Airwave",
    "ALT Buds": "ALT Buds",
    "Buds": "Buds",
    "Chord": "Chord",
    "Master Buds": "Master Buds",
    "Pure Pods": "Pure Pods"
}

for name, family in families.items():
    mask = df_clean["model_series"].str.contains(
        name, case=False, na=False
    )
    df_clean.loc[mask, "model_series"] = family

In [336]:
mapping = {
    'Tune': ['Tune Active Pro', 'Tune Elite Sport', 'Tune LITE', 'Tune Sport 2'],
    'Flair': ['Flair Touch', 'Flair XL'],
    'Bravo': ['Bravo', 'Bravo Neckband'],
    'Nerve': ['Nerve', 'Nerve Pro'],
    'Air Clips': ['Air Clips', 'ALT Clip OWS Earclips'],
    'Wireless Series': ['100 Wireless', '102 Wireless', '103 Wireless']
}
for correct_name, wrong_names in mapping.items():
    df_clean['model_series'] = df_clean['model_series'].replace(wrong_names, correct_name)

In [338]:
df_clean.to_csv('boat_noise_cleaned_v2.csv')

In [350]:
df_clean[df_clean['description_raw'].str.contains('drivers',case=False)].shape

(239, 20)

In [356]:
df_clean["driver_size_mm"] = pd.to_numeric(
    df_clean["description_raw"].str.extract(
        r"(?i)\bDriver\s*Size\b\s*[:|]?\s*(\d+(?:\.\d+)?)\s*mm"
    )[0],
    errors="coerce"
)

In [361]:
df_clean['driver_size_mm'].isna().sum()

np.int64(282)

In [360]:
mask = df_clean["driver_size_mm"].isna()

df_clean.loc[mask, "driver_size_mm"] = pd.to_numeric(
    df_clean.loc[mask, "description_raw"].str.extract(
        r"(?i)\b(\d+(?:\.\d+)?)\s*mm\s+(?:audio\s+)?drivers?\b"
    )[0],
    errors="coerce"
)

In [362]:
df_clean.loc[
    df_clean["driver_size_mm"].isna(),
    ["product_name", "description_raw"]
].head(50).to_string()

"                                                                                                                                            product_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            description_raw\n1         boAt Rockerz 450 Black Panther Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | \n2       boAt Rockerz 450 Captain America Marvel Edition | Bluetooth Headphones with 40mm Audio Drivers, 15H Playback, Voice Assistant, Dual Connectivity                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         | \n5                                                                 boAt Airdopes 101v2 | Wireless Earbuds with 35 Hours Playback, BEAST™ Mode & ENx™ Tech                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          specifications | \n6                                                boAt Airdopes 111v2 | Wireless Earbuds with 50H Playback, Bluetooth v5.4, IWP™ Technology, 13mm Drivers                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   

In [368]:
mask = df_clean["driver_size_mm"].isna()

df_clean.loc[mask, "driver_size_mm"] = pd.to_numeric(
    df_clean.loc[mask, "product_name"].str.extract(
        r"(?i)\b(\d+(?:\.\d+)?)\s*mm\s+(?:audio\s+)?drivers?\b"
    )[0],
    errors="coerce"
)

In [374]:
df_clean["driver_size_mm"].value_counts(dropna=False)

driver_size_mm
NaN     216
10.0    148
13.0     57
40.0     45
11.0     33
6.0      26
50.0     13
8.0       7
7.0       7
12.0      7
14.2      2
12.4      1
16.0      1
14.8      1
30.0      1
Name: count, dtype: int64

In [371]:
mask = df_clean["driver_size_mm"].isna()

specs_driver_mask = (
    df_clean.loc[mask, "specs_raw_json"]
    .astype("string")
    .str.contains(r"(?i)driver", na=False)
)

print(specs_driver_mask.sum())

30

In [372]:
df_clean.loc[
    mask & specs_driver_mask,
    ["product_name", "specs_raw_json"]
].to_string()

'                                                         product_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      specs_raw_json\n269                            Buds Uno Truly Wireless Earbuds - Deal                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {"Playtime": "Up to 40 hours", "Charging Time": "Up to 60 minutes", "Fast Charging": "Yes", "BT": "v5.3", "Wireless range": "10m", "Auto pairing": "Yes, it connects with the last paired device", "Speaker driver": "10mm Titanium Drivers", "Dual device pairing": "Yes", "Hands-free calling": "Yes", "Voice assistant": "Siri, Google Assistant", "In-ear detection": "No", "Country of Origin": "China", "Package Contents": "1 device, 1 charging cable, 1 user manual, warranty card", "Marketed & Imported By": "Nexxbase Marketing Pvt. Ltd, Khasra No-146/25/2/1, Jail Road Badshahpur, Gurugram Haryana-122101", "BT supported profile": "A2DP, AVRCP, HFP, HSP", "Compatibility": "Android & iOS", "Charging Port": "C-type", "Charging Indicator": "Yes", "Weight": "37.9 grams", "Dimensions": "6.1 x 5.2 x 2.5 cm", "Water resistance rating": "IPX4", "Instacharge™": "10 minutes of charge = 150 minutes of playtime", "Low latency": "Up to 50ms"}\n329                          Noise Air Clips 2 OWS Open Ear Headphone                                                                                                                                                                                                                                                                                                                                                                                                                                                        {"Playtime": "Up to 40 hours", "Charging Time": "Up to 90 minutes", "Fast Charging": "Yes", "BT": "v5.3", "Wireless range": "10m", "Auto pairing": "Yes, it connects with the last paired device", "Speaker driver": "12mm", "AirWave™ technology": "Yes", "Dual device pairing": "Yes", "Responsive touch controls": "Yes", "Hands-free calling": "Yes", "Voice assistant": "Siri, Google Assistant", "In-ear detection": "No", "Country of Origin": "P.R.C.", "Package Contents": "1 device, 1 charging cable, 1 user manual, warranty card", "Marketed & Imported By": "Nexxbase Marketing Pvt. Ltd.15th floor, DLF City Phase 5, Two Horizon Centre, Golf Course Road, Sector 43, Gurugram, Haryana - 122002 (INDIA)", "BT supported profile": "A2DP, HFP, AVRCP", "Compatibility": "Android & iOS", "Charging Port": "C-type", "Charging Indicator": "Yes", "Weight": "6 grams", "Dimensions": "5.8 x 5.4 x 3 cm", "Water resistance rating": "IPX5", "Instacharge™": "10 minutes of charge = 120 minutes of playtime"}\n330                            Noise Air Clips OWS Open Ear Headphone                                                                                                                                                                                                                                                                                                                                  {"Playtime": "Up to 40 hours", "Charging Time": "Up to 120 minutes", "Fast Charging": "Yes", "BT": "V5.4", "Wireless range": "10m", "Auto pairing": "Yes, connects with the last paired device", "Speaker driver": "12mm", "AirWave™ technology": "Yes", "Dual device pairing": "Yes", "Responsive touch controls": "Yes", "Hands-free calling": "Yes", "Voice assistant": "Siri, Google Assistant", "In-ear detection": "No", "Country of Origin": "China", "Package Contents": "1 device, 1 charging cable, 1 user manual, warranty card", "Marketed & Imported By": "Nexxbase Marketing Pvt. Ltd, Khasra No-146/25/2/1, Jail Road Badshahpur, Gurugram Haryana-122101", "BT supported profile": "A2DP, HFP, AVRCP", "Compatibility": "Android & iOS", "Charging Port": "C-type", "Charging Indicator": "Yes", "Weight": "5.4 grams", "Dimensions": "4.6 x 5.4 x 2.8cm", "Water resistance rating": "IPX5", "Instacharge™": "10 minutes of charge = 150 minutes of playtime", "Form Factor": "In-Ear", "Controls": "On-ear touch control (Volume, Music, Call control feature on both earbuds, ANC, Siri and Google Assistant from one earbud)"}\n360     Noise Buds Apex Truly Wireless Bluetooth Earbuds - Blue Tokai                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {"Country of Origin": "China", "Package Contents": "1 device, 1 charging cable, 1 user manual, warranty card", "Marketed & Imported By": "15TH FLOOR, DLF CITY PHASE 5, TWO HORIZON CENTRE, GOLF COURSE ROAD, SECTOR 43, GURUGRAM, HARYANA - 122102, INDIA.", "Speaker driver": "10mm", "HD Calling": "Yes", "BT": "v5.3", "Wireless range": "10m", "Auto pairing": "Yes, connects with the last paired device", "BT supported profile": "A2DP, AVRCP, HFP, SPP, AVDTP", "Compatibility": "Android & iOS", "Dual Pairing": "Yes", "Hyper Sync": "Yes", "Playtime": "Up to 50 hours", "Charging time": "90 minutes", "Fast Charging": "Yes", "Charging Port": "Type-C", "Charging Indicator": "Yes", "Water resistance rating": "IPX5", "Quad mic with ENC | Hands-free calling | Voice assistant support": "Siri, Google Assistant"}\n366                       Noise Buds Connect 2 Truly Wireless Earbuds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         {"Country of Origin": "China", "Package Contents": "1 device, 1 charging cable, 1 user manual, warranty card", "Marketed & Imported By": "Nexxbase Marketing Pvt. Ltd, Khasra No-146/25/2/1, Jail Road Badshahpur, Gurugram Haryana-122101", "Speaker driver": "10mm", "BT": "v5.3", "Wireless range": "10m", "Auto pairing": "Yes, it connects with the last paired device", "BT supported profile": "A2DP, AVCTP, AVDTP, AVRCP, HFP", "Compatibility": "Android & iOS", "Playtime": "Up to 50 hours", "Charging Time": "Up to 90 minutes", "Fast Charging": "Yes", "Charging Port": "C-type", "Charging Indicator": "Yes", "Weight": "43 grams", "Dimensions": "6.3 x 4.7 x 2.8 cm", "Water resistance rating": "IPX5", "Instacharge™": "10 minutes of charge = 120 minutes of playtime", "Low latency": "Up to 40ms", "Hands-free calling": "Yes", "Voice assistant": "Siri, Google Assistant", "Dual device pairing": "Yes", "In-ear detection": "Yes"}\n368                         Noise Buds Connect Truly Wireless Earbuds                                                                                                                                                                                                                                                                                                                                                                                                                                              {"Country of Origin": "India", "Package Contents": "1 device, 1 charging cable, 1 user manual, warranty card", "Marketed & Imported By": "Nexxbase Marketing Pvt. Ltd, Khasra No-146/25/2/1, Jail Road Badshahpur, Gurugram Haryana-122101", "Speaker Driver": "13mm", "BT": "5.2", "Wireless Range": "10m", "BT Supported Profile": "A2DP, HFP, HSP, AVRCP", "Compatibility": "Android & iOS", "Playtime": "Up to 8 hours on a single charge and an additional 50 hours with the charging case", "Instacharge™": "Yes, (10-min charge = 120-min playtime)", "Earbud Charging Time": "Up to 60 minutes", "Charging Case Charge time": "Up to 90 minutes", "Charging Indicator": "Yes", "Earbuds Weight": "8.2g gram each", "Charging case dimension": "61.6*25.6*44.5mm", "Charging case weight": "35.2 grams", "Water Resistance Rating": "IPX5 water-resistant", "Environmental Noise Cancellation": "Yes", "Hyper Sync™": "Yes", "Hands free Calling": "Yes", "Voice Assistant": "Siri, Google Assistant", "Form Factor": "In-ear"}\n373                Noise Buds Marine Truly Wireless Bluetooth Earbuds                                                                                                                                                                                                                                                                                                                           {"Playtime": "Up to 35 hours", "Charging Time": "Up to 90 minutes", "Fast Charging": "Yes", "BT": "V5.3", "Wireless range": "10m", "Auto pairing": "Yes, connects with the last paired device", "Speaker driver": "13mm", "Dual device pairing": "Yes", "Hands-free calling": "Yes", "Voice assistant": "Siri, Google Assistant", "Case": "Metal alloy with chain", "Water resistance rating": "IPX4", "Country of Origin": "P.R.C.", "Package Contents": "1 pair of BT earbuds, 1 statement chain, 1 charging cable, user manual, warranty card", "Marketed & Imported By": "Nexxbase Marketing Pvt. Ltd.15th floor, DLF City Phase 5, Two Horizon Centre, Golf Course Road, Sector 43, Gurugram, Haryana - 122002 (INDIA)", "BT v5.3 Wireless range": "10m", "BT supported profile": "A2DP, AVRCP, HFP,HSP", "Compatibility": "Android & iOS", "Charging time": "Up to 90 mins", "Fast charging": "Yes (Instacharge™)", "Charging port": "Type-C", "Charging indicator": "Yes", "Instacharge™": "10 minutes of charge = 120 minutes of playtime", "Low latency mode for gaming | Hands-free calling": "Yes", "Voice assistant support": "Siri, Google"}\n376                          Noise Buds N1 Pro Truly Wireless Earbuds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {"Playtime": "Up to 60 hours", "Charging Time": "Up to 90mins", "Fast Charging": "Yes", "BT": "v5.3", "Wireless range": "10m", "Auto pairing": "Yes, connects with the last paired device", "Speaker driver": "11mm", "Hands-free calling": "Yes", "Voice assistant": "Siri, Google Assistant", "Water resistance rating": "IPX5", "Country of Origin": "China", "Package Contents": "1 device, 1 charging cable, 1 user manual, warranty card", "Marketed & Imported By": "Nexxbase Marketing Pvt. Ltd, Khasra No-146/25/2/1, Jail Road Badshahpur, Gurugram Haryana-122101", "BT supported profile": "A2DP, AVRCP, HFP, SPP, AVDTP", "Compatibility": "Android & iOS", "Charging Port": "C-type", "Charging Indicator": "Yes", "Weight": "39 grams", "Dimensions": "4.3 x 5.6 x 2.8 cm", "Instacharge™": "10 minutes of charge = 200 minutes of playtime", "Low latency": "Up to 40ms", "Dual device pairing": "No"}\n377           Noise Buds N1 Pro Truly Wireless Earbuds - Chrome Black                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {"Playtime": "Up to 60 hours", "Charging Time": "Up to 90mins", "Fast Charging": "Yes", "BT": "v5.3", "Wireless range": "10m", "Auto pairing": "Yes, connects with the last paired device", "Speaker driver": "11mm", "Hands-free calling": "Yes", "Voice assistant": "Siri, Google Assistant", "Water resistance rating": "IPX5", "Country of Origin": "China", "Package Contents": "1 device, 1 charging cable, 1 user manual, warranty card", "Marketed & Imported By": "Nexxbase Marketing Pvt. Ltd, Khasra No-146/25/2/1, Jail Road Badshahpur, Gurugram Haryana-122101", "BT supported profile": "A2DP, AVRCP, HFP, SPP, AVDTP", "Compatibility": "Android & iOS", "Charging Port": "C-type", "Charging Indicator": "Yes", "Weight": "39 grams", "Dimensions": "4.3 x 5.6 x 2.8 cm", "Instacharge™": "10 minutes of charge = 200 minutes of playtime", "Low latency": "Up to 40ms", "Dual device pairing": "No"}\n380                              Noise Buds N1 Truly Wireless Earbuds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {"Playtime": "Up to 40 hours", "Charging Time": "Up to 90 mins", "Fast Charging": "Yes", "BT": "V5.3", "Wireless range": "10m", "Auto pairing": "Yes, connects with the last paired device", "Speaker driver": "11mm", "Hands-free calling": "Yes", "Voice assistant": "Siri, Google Assistant", "Country of Origin": "China", "Package Contents": "1 device, 1 charging cable, 1 user manual, warranty card", "Marketed & Imported By": "Nexxbase Marketing Pvt. Ltd, Khasra No-146/25/2/1, Jail Road Badshahpur, Gurugram Haryana-122101", "BT supported profile": "A2DP, AVRCP, HFP, SPP, AVDTP", "Compatibility": "Android & iOS", "Charging Port": "C-type", "Charging Indicator": "Yes", "Weight": "37 grams", "Dimensions": "5.2 x 4.3 x 2.6 cm length", "Water resistance rating": "IPX5", "Instacharge™": "10 minutes of charge = 120 minutes of playtime", "Low latency": "Up to 40ms", "HyperSync™ | Hands-free calling": "Yes", "Dual device pairing": "NO"}\n384      Noise Buds N1 Truly Wireless Earbuds - Healthifyme Exclusive                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {"Playtime": "Up to 40 hours", "Charging Time": "Up to 90 mins", "Fast Charging": "Yes", "BT": "V5.3", "Wireless range": "10m", "Auto pairing": "Yes, connects with the last paired device", "Speaker driver": "11mm", "Hands-free calling": "Yes", "Voice assistant": "Siri, Google Assistant", "Country of Origin": "China", "Package Contents": "1 device, 1 charging cable, 1 user manual, warranty card", "Marketed & Imported By": "Nexxbase Marketing Pvt. Ltd, Khasra No-146/25/2/1, Jail Road Badshahpur, Gurugram Haryana-122101", "BT supported profile": "A2DP, AVRCP, HFP, SPP, AVDTP", "Compatibility": "Android & iOS", "Charging Port": "C-type", "Charging Indicator": "Yes", "Weight": "37 grams", "Dimensions": "5.2 x 4.3 x 2.6 cm length", "Water resistance rating": "IPX5", "Instacharge™": "10 minutes of charge = 120 minutes of playtime", "Low latency": "Up to 40ms", "HyperSync™ | Hands-free calling": "Yes", "Dual device pairing": "NO"}\n393                            Noise Buds Play Truly Wireless Earbuds                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           {"Playtime": "Up to 40 hours", "BT": "v6.0", "Wireless range": "10m", "Auto pairing": "Yes", "Speaker driver": "13mm", "Water resistance rating": "IPX4"}\n398                         Noise Buds Trooper Truly Wireless Earbuds                                                                                                                                                                                                                                                                                                                                                                                                                                                           

In [373]:
mask = df_clean["driver_size_mm"].isna()

spec_driver = (
    df_clean.loc[mask, "specs_raw_json"]
    .str.extract(
        r'(?i)"(?:Speaker\s+)?Driver"\s*:\s*"(\d+(?:\.\d+)?)\s*mm'
    )[0]
)

df_clean.loc[mask, "driver_size_mm"] = pd.to_numeric(
    spec_driver,
    errors="coerce"
)

In [375]:
df_clean.columns

Index(['brand', 'product_name', 'category', 'sale_price_min_inr', 'sale_price_max_inr', 'mrp_inr', 'discount_percent', 'num_variants', 'colors', 'tags_raw', 'features_raw', 'specs_raw_json', 'description_raw', 'published_at', 'base_product', 'edition_type', 'model_series', 'published_year', 'published_month', 'color_count', 'driver_size_mm'], dtype='str')

In [376]:
ocrdf=pd.read_csv('boat_noise_earphones_ocr.csv')

In [381]:
ocrdf.shape

(601, 38)

In [380]:
ocrdf= ocrdf.drop_duplicates(subset="product_name", keep="first")

In [383]:
merged = pd.merge(
    df_clean,
    ocrdf,
    on="product_name",
    how="inner",           # keeps only the 565 that match in both
    suffixes=("_specs", "_ocr")
)

print(merged.shape)

(565, 58)

In [ ]:
len(df_clean) == len(merged) and df_clean["product_name"].equals(merged["product_name"])

True

In [387]:
set(df_clean["product_name"]) == set(merged["product_name"])

True

In [388]:
merged.to_csv('merged.csv')

In [389]:
merged.columns

Index(['brand_specs', 'product_name', 'category_specs', 'sale_price_min_inr_specs', 'sale_price_max_inr_specs', 'mrp_inr_specs', 'discount_percent_specs', 'num_variants_specs', 'colors_specs', 'tags_raw_specs', 'features_raw_specs', 'specs_raw_json_specs', 'description_raw_specs', 'published_at_specs', 'base_product', 'edition_type', 'model_series', 'published_year', 'published_month', 'color_count', 'driver_size_mm', 'brand_ocr', 'handle', 'product_url', 'category_ocr', 'product_type', 'collection_source', 'vendor', 'sale_price_min_inr_ocr', 'sale_price_max_inr_ocr', 'mrp_inr_ocr', 'discount_percent_ocr', 'num_variants_ocr', 'colors_ocr', 'skus', 'in_stock_variants', 'tags_raw_ocr', 'features_raw_ocr', 'specs_raw_json_ocr', 'description_raw_ocr', 'image_url', 'created_at', 'updated_at', 'published_at_ocr', 'product_id', 'ocr_images_used', 'ocr_text_raw', 'ocr_playtime_hours', 'ocr_playback_per_charge_hours', 'ocr_driver_mm', 'ocr_bluetooth', 'ocr_ip_rating', 'ocr_anc_db', 'ocr_latency_ms', 'ocr_fast_charge_note', 'ocr_has_anc', 'ocr_has_enc', 'ocr_water_resistance'], dtype='str')

In [392]:
merged.loc[
    merged["driver_size_mm"].isna(),
    "ocr_driver_mm"
].notna().sum()

np.int64(26)

In [394]:
mask = merged["driver_size_mm"].isna()

merged.loc[mask, "driver_size_mm"] = merged.loc[
    mask, "ocr_driver_mm"
]

In [396]:
merged["driver_size_mm"].isna().sum()

np.int64(190)

In [398]:
merged["driver_size_mm"].value_counts(dropna=False).sort_index()

driver_size_mm
6.0      26
7.0       7
8.0       7
10.0    156
11.0     33
12.0      7
12.4      2
13.0     65
14.2      3
14.8      1
15.0      1
16.0      1
18.0      1
30.0      1
35.0      1
40.0     50
50.0     13
NaN     190
Name: count, dtype: int64

In [400]:
merged['ocr_playtime_hours'].value_counts(dropna=False)

ocr_playtime_hours
NaN      111
50.0      81
40.0      53
60.0      35
30.0      31
20.0      27
45.0      26
15.0      20
10.0      16
8.0       16
35.0      15
100.0     14
70.0      14
80.0      11
120.0     10
24.0       7
12.0       7
42.0       6
150.0      6
25.0       6
16.0       5
6.0        5
14.0       4
75.0       4
28.0       4
4.0        4
55.0       3
48.0       2
32.0       2
22.0       2
65.0       2
52.0       2
5.0        2
3.0        1
13.0       1
23.0       1
46.0       1
54.0       1
7.0        1
17.0       1
33.0       1
18.0       1
140.0      1
1.0        1
72.0       1
Name: count, dtype: int64

In [421]:
merged[merged['ocr_playtime_hours'].isna()]['category_specs'].value_counts()

category_specs
Wired Earphones          43
True Wireless Earbuds    22
Headphones               13
Neckband                 13
Name: count, dtype: int64

In [408]:
mask = merged["ocr_playtime_hours"].isna()

name_playtime = merged.loc[mask, "product_name"].str.extract(
    r"(?i)\b(\d+(?:\.\d+)?)\s*H(?:ours?)?\s*(?:Playback|Playtime)\b"
)[0]

print(name_playtime.notna().sum())

20

In [410]:
mask = merged["ocr_playtime_hours"].isna()

name_playtime = merged.loc[mask, "product_name"].str.extract(
    r"(?i)\b(\d+(?:\.\d+)?)\s*H(?:ours?)?\s*(?:Playback|Playtime)\b"
)[0]

merged.loc[mask, "ocr_playtime_hours"] = pd.to_numeric(
    name_playtime,
    errors="coerce"
)

In [411]:
merged['ocr_playtime_hours'].isna().sum()

np.int64(91)

In [412]:
merged['category_specs'].value_counts()

category_specs
True Wireless Earbuds    333
Neckband                 113
Headphones                76
Wired Earphones           43
Name: count, dtype: int64

In [416]:
mask = (
    merged["ocr_playtime_hours"].isna()
    & merged["category_specs"].ne("Wired Earphones")
)

print(
    merged.loc[
        mask, "features_raw_specs"
    ]
    .astype("string")
    .str.contains(
        r"(?i)(playback|playtime|hours?|hrs?)",
        regex=True,
        na=False
    )
    .sum()
)

18

C:\Users\SUMIT\AppData\Local\Temp\ipykernel_32720\3408650590.py:11: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  .str.contains(

In [418]:
mask = (
    merged["ocr_playtime_hours"].isna()
    & merged["category_specs"].ne("Wired Earphones")
)

merged.loc[
    mask
    & merged["features_raw_specs"].astype("string").str.contains(
        r"(?i)(playback|playtime|hours?|hrs?)",
        regex=True,
        na=False
    ),
    ["product_name", "features_raw_specs"]
].to_string()

C:\Users\SUMIT\AppData\Local\Temp\ipykernel_32720\3763757580.py:8: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  & merged["features_raw_specs"].astype("string").str.contains(

'                                                                                                                                                 product_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  features_raw_specs\n33                                                           boAt Airdopes 161 ANC Elite | Wireless Earbuds with ANC up to 32dB, ENx™ Technology, BEAST™ Mode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Audio-Category | Bluetooth Earphones | Gaming Earbuds | Large Playback Earbuds | Noise Cancellation Earbuds | Recently-Restocked | Travel Earbuds | TWS | Work Earbuds | specifications\n119                                    boAt Airdopes Unity ANC | Bluetooth Earbuds with Active Noise Cancellation, ENx™ Technology, BEAST™ Mode, ASAP™ Charge                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           Audio-Category | best-seller-sec | Bluetooth Earphones | Country Code: CN | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Large Playback Earbuds | Noise Cancellation Earbuds | Recently-Restocked | Snapmint | Summer 400 | Super Savers | TopPicks | Travel Earbuds | TWS | specifications\n153                                                boAt Bassheads 900 | Wired Earphones with 40mm Drivers, Compact & Foldable, In-line microphone, Super Bass                                                                                                                      15% | Affordable | All products | Audio-Category | BassHeads | BH-onear | Country Code: CN | Daily Deals | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Liquidation | Recently-Restocked | recommend-type-c-a350-cable-1-5-meter | Sail-with-boat-september | Wired | Wired Headphones for Music | Wired Headphones with Mic | boAt BassHeads 900 | Super extra bass | Snug Fit | The on-ear headphones with swivel ear cups offers flexible wearing and a comfortable fit for everyone. | Compact and foldable | Easy to carry, easy to store headphones are engineered for music on the go. | Specifications | Connect & Play | Headphone Type On-Ear | Super Extra Bass Yes | Driver Size 40 mm | Impedance 32Ω | Sensitivity (dB) 101db ±3db | Frequency Response 20Hz-20KHz | Noise Isolation Passive | Microphone Yes | Country Of Origin China | Rated Power 3mW | Compatibility All 3.5mm Jack Device | In-line microphone | The tangle-resistant cable with 3. 5mm audio jack comes with a built-in mic and control for calls and playback. | Q. Can I pause/play & change tracks with the earphones? | Q. Does it have an in-line microphone? | Yes, Bassheads 900 comes with an in-line microphone. The microphone also features in-built noise isolation technology.\n155                                                Bassheads 900 Pro | Wired Headphone with 40mm Drivers, 5W Power Output, 1.5m Cable Length, USB Plug & Play                                                                                                                                                                                                                                15% | Affordable | All products | Audio-Category | BassHeads | BH-onear | Country Code: CN | Daily Deals | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Liquidation | Recently-Restocked | recommend-type-c-a350-cable-1-5-meter | Sail-with-boat-september | Super Savers | Wired | Wired Headphones for Music | Wired Headphones with Mic | boAt BassHeads 900 | Super extra bass | Snug Fit | The on-ear headphones with swivel ear cups offers flexible wearing and a comfortable fit for everyone. | Compact and foldable | Easy to carry, easy to store headphones are engineered for music on the go. | Specifications | Connect & Play | Headphone Type On-Ear | Super Extra Bass Yes | Driver Size 40 mm | Impedance 32Ω | Sensitivity (dB) 101db ±3db | Frequency Response 20Hz-20KHz | Noise Isolation Passive | Microphone Yes | Country Of Origin China | Rated Power 3mW | Compatibility All 3.5mm Jack Device | In-line microphone | The tangle-resistant cable with 3. 5mm audio jack comes with a built-in mic and control for calls and playback. | Q. Can I pause/play & change tracks with the earphones? | Q. Does it have an in-line microphone?\n158                                                Bassheads 910 | Wired Headphone with 40mm Dynamic Drivers, Comfortable & Foldable Cups, In-line microphone  All products | allprod | Audio-Category | BassHeads | Country Code: CN | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | offline | Wired | Wired Headphones with Mic | BassHeads 910 | Super extra bass | Snug Fit | The on-ear headphones with swivel ear cups offers flexible wearing and a comfortable fit for everyone. | Compact and foldable | Easy to carry, easy to store headphones are engineered for music on the go. | Specifications | Connect & Play | Headphone Type On-Ear | Super Extra Bass Yes | Driver Size 40 mm | Impedance 32Ω | Sensitivity (dB) 101db ±3db | Frequency Response 20Hz-20KHz | Noise Isolation Passive | Microphone Yes | Country Of Origin China | Rated Power 3mW | Compatibility All 3.5mm Jack Device | In-line microphone | The tangle-resistant cable with 3. 5mm audio jack comes with a built-in mic and control for calls and playback. | Q. Can I pause/play & change tracks with the earphones? | Q. Does it have an in-line microphone? | Yes, BassHeads 910 comes with an in-line microphone. The microphone also features in-built noise isolation technology. | Q. Is it good for meetings and calls? | Q. Does it come with noise cancellation? | Yes, BassHeads 910 comes with passive noise cancellation. | Q. What is the length of the cable? | The cable is 1500mm long. | Q. Is there a warranty for the product? How do I claim warranty?\n160                                               boAt Bassheads 950v2 | Wired Headphone with 40mm drivers, Passive Noise Isolation & built-in mic, Deep Bass                                                All products | allprod | Audio-Category | BassHeads | BH-onear | Country Code: CN | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | price-match | Sail-with-boat-september | Wired | Bassheads 950v2 - Wired Earphones | Big Sound. Deep Bass. | Get ready to enjoy crystal clarity as you plug into your favorite tunes with its 40mm drivers and Super Extra Bass. | More Music. Less Noise. | Ergonomic Design. Cosy Cushions. | Built-in Mic. | Bring home your new work-from-home partner. Experience a hassle-free calling experience with its built-in mic. | Just A Click Away. | Specifications | Connect & Play | Driver Size 40mm | Deep Bass Yes | Controls On wire controls | Plug/Connectivity 3.5mm jack | Noise Isolation Passive Noise Isolation | Built-in Mic Yes | Mic Type On wire | Compatibility All devices with 3.5mm jack | Country Of Origin China | Bold, Warm, and Raging. | Bassheads 950v2 comes in three striking colours | Bold Blue, Warm Grey, Raging Black. | #WiredIsBack | Q. Can I pause/play & change tracks with the earphones? | Q. Does it have a microphone? | Yes, Bassheads 950v2 comes with an on cable microphone. | Q. Is it good for meetings and calls? | Yes, with its on cable microphone, Bassheads 950v2 is perfect for meetings and working from home. | Q. Does it come with noise cancellation?\n180                                                          boAt Airdopes 191 ANC | Wireless Earbuds with ANC up to 32dB,Quad Mics ENx™ Tech, Bluetooth v5.3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       Audio-Category | Bluetooth Earphones | BOGO | Large Playback Earbuds | Noise Cancellation Earbuds | Recently-Restocked | Travel Earbuds | TWS\n221  boAt Standalone Crest AI Pack | Voice-First AI Companion Built with Google Gemini (Your Crest AI Subscription will be activated shortly after purchase.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     AI_Subscr | App_webview | Audio-Category | Bluetooth Earphones | Large Playback Earbuds | newlaunch | no-COD | Premium | Recently-Restocked | ship@0 | Travel Earbuds | TWS | view_product_cta | specifications\n228                                  boAt Nirvana Lucid | Wireless Earbuds with Active Noise Cancellation up to 32dB, BEAST™ Mode, 10mm Drivers, ASAP™ Charge                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Audio-Category | best-seller-sec | Bluetooth Earphones | Country Code: CN | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Large Playback Earbuds | Noise Cancellation Earbuds | Recently-Restocked | TopPicks | Travel Earbuds | TWS | specifications\n229                                                             boAt Nirvana Space | TWS Earbuds with boAt 360º Spatial Audio, 32dB Active Noise Cancellation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Audio-Category | Bluetooth Earphones | Category-E | Large Playback Earbuds | Noise Cancellation Earbuds | Premium | Recently-Restocked | SCORE:999 | Super Savers | Travel Earbuds | TWS | Work Earbuds\n274                                                                                                                                       boAt Immortal 1000D                                                                                                                                                                                                                                                                                https://www.boat-lifestyle.com/products/im-1000d | Immortal 1000D - 7.1 channel headphones | Dolby Atmos | Unlock your full potential and get the most thrilling gaming experience with Dolby Atmos with 7.1 channel headphones . | 7.1 Channel Surround Sound | Enjoy gaming as it’s supposed to be with a high-fidelity sound optimized by experts. | via boAt Plugin Labz | 50mm Drivers | Get an advantage over your rivals with 3D spatial sound that provides pinpoint positional accuracy. | Breathing RGB LEDs | Complement your gaming setup with the iconic RGB aesthetics. | Easy Audio & Mic Driver Customisation | Play by your own rules with seamless driver customisations. | Lightweight Ergonomic Design | Feels like a feather, performs like a beast. | Specifications | Connect & Play | Speaker Driver 50 * 5mm | Speaker Sensitivity 98±3dB | Speaker Impedance 32Ω± 15% | Plug/Connectivity USB | LED Type Breathing LED (RGB) | Mic Sensitivity -40±3dB | Mic Frequency 100-10KHz | Mic Type Omni-Directional | Cord Length 1.8m | Control On-Cable Remote | 7.1 Application 7.1 Virtual Surround Sound (boAt Plugin Labz) | Sound Isolation Yes | Country Of Origin China | Detachable Mic\n277                                     boAt Immortal 111 | Bluetooth Gaming Wireless Earbuds with BEAST™️Mode, ENx™ Technology, ASAP™ Charge, Bluetooth v5.3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              

In [420]:
mask = (
    merged["ocr_playtime_hours"].isna()
    & merged["category_specs"].ne("Wired Earphones")
)

merged.loc[mask, "ocr_playtime_hours"] = pd.to_numeric(
    merged.loc[mask, "features_raw_specs"].str.extract(
        r"(?i)\b(\d+(?:\.\d+)?)\s*H(?:ours?)?\s*(?:Playback|Playtime)\b"
    )[0],
    errors="coerce"
)

In [430]:
merged["ocr_playtime_hours"].isna().sum()

np.int64(88)

In [424]:
mask = (
    merged["ocr_playtime_hours"].isna()
    & merged["category_specs"].ne("Wired Earphones")
)

print(
    merged.loc[
        mask, "tags_raw_specs"
    ]
    .astype("string")
    .str.contains(
        r"(?i)(?:playback|playtime)",
        regex=True,
        na=False
    )
    .sum()
)

19

In [425]:
mask = (
    merged["ocr_playtime_hours"].isna()
    & merged["category_specs"].ne("Wired Earphones")
)

merged.loc[
    mask
    & merged["tags_raw_specs"].str.contains(
        r"(?i)(?:playback|playtime)",
        regex=True,
        na=False
    ),
    ["product_name", "tags_raw_specs"]
].to_string()

'                                                                                                                                                 product_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   tags_raw_specs\n33                                                           boAt Airdopes 161 ANC Elite | Wireless Earbuds with ANC up to 32dB, ENx™ Technology, BEAST™ Mode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             Audio-Category | Bluetooth Earphones | Free-Spotify | Gaming Earbuds | Large Playback Earbuds | meta-label-just launched | no-product-banner | Noise Cancellation Earbuds | Recently-Restocked | Travel Earbuds | TWS | Work Earbuds\n119                                    boAt Airdopes Unity ANC | Bluetooth Earbuds with Active Noise Cancellation, ENx™ Technology, BEAST™ Mode, ASAP™ Charge                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Audio-Category | best-seller-sec | Bluetooth Earphones | Country Code: CN | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Large Playback Earbuds | Noise Cancellation Earbuds | Recently-Restocked | Snapmint | Summer 400 | Super Savers | TopPicks | Travel Earbuds | TWS\n180                                                          boAt Airdopes 191 ANC | Wireless Earbuds with ANC up to 32dB,Quad Mics ENx™ Tech, Bluetooth v5.3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Audio-Category | Bluetooth Earphones | BOGO | Large Playback Earbuds | meta-label-just launched | Noise Cancellation Earbuds | Recently-Restocked | Travel Earbuds | TWS\n221  boAt Standalone Crest AI Pack | Voice-First AI Companion Built with Google Gemini (Your Crest AI Subscription will be activated shortly after purchase.)                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               AI_Subscr | App_webview | Audio-Category | Bluetooth Earphones | Large Playback Earbuds | newlaunch | no-COD | no-product-banner | Premium | Recently-Restocked | ship@0 | Travel Earbuds | TWS | view_product_cta\n228                                  boAt Nirvana Lucid | Wireless Earbuds with Active Noise Cancellation up to 32dB, BEAST™ Mode, 10mm Drivers, ASAP™ Charge                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 Audio-Category | best-seller-sec | Bluetooth Earphones | Country Code: CN | Free-Spotify | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Large Playback Earbuds | Noise Cancellation Earbuds | Recently-Restocked | TopPicks | Travel Earbuds | TWS\n229                                                             boAt Nirvana Space | TWS Earbuds with boAt 360º Spatial Audio, 32dB Active Noise Cancellation                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            Audio-Category | Bluetooth Earphones | Category-E | Free-Spotify | Large Playback Earbuds | meta-label-just launched | no-product-banner | Noise Cancellation Earbuds | Premium | Recently-Restocked | SCORE:999 | Super Savers | Travel Earbuds | TWS | Work Earbuds\n277                                     boAt Immortal 111 | Bluetooth Gaming Wireless Earbuds with BEAST™️Mode, ENx™ Technology, ASAP™ Charge, Bluetooth v5.3                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  Audio-Category | best-seller-sec | Bluetooth Earphones | Country Code: CN | Gaming Earbuds | Gaming Headphones | Immortal | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Large Playback Earbuds | TopPicks | Travel Earbuds | TWS\n281                                                  boAt Immortal 158 | Bluetooth Gaming Wireless Earbuds with BEAST™Mode, ENx™ with Quad Mics, ASAP™ Charge                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              Audio-Category | best-seller-sec | Bluetooth Earphones | Country Code: CN | Gaming Earbuds | Gaming Headphones | Immortal | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Large Playback Earbuds | meta-label-just launched | Recently-Restocked | TWS\n287                                        boAt Immortal 201 | Bluetooth Gaming Wireless Earbuds with 40ms BEAST™ Mode, Real RGB Lights, boAt Signature Sound                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         Audio-Category | best-seller-sec | Bluetooth Earphones | BOGO | Country Code: CN | Coupon-300|BIG300 | Gaming Earbuds | Gaming Headphones | Immortal | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Large Playback Earbuds | meta-label-just launched | newlaunch | payTM | Super Savers | TopPicks | Travel Earbuds | TWS\n298                                                          boAt Nirvana Crown | Smart TWS Earbuds with Haptic Enabled Case, 50dB Hybrid ANC & Spatial Audio                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Audio-Category | Bluetooth Earphones | Free-Spotify | Large Playback Earbuds | meta-label-just launched | newlaunch | no-product-banner | Noise Cancellation Earbuds | Premium | Recently-Restocked | Travel Earbuds | TWS | Work Earbuds\n309                                                boAt Nirvana Nebula | Wireless Earbuds with ANC up to 35dB, Dolby Audio, boAt Signature Sound, BEAST™ Mode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Audio-Category | Bluetooth Earphones | Free-Spotify | Large Playback Earbuds | meta-label-just launched | no-product-banner | Noise Cancellation Earbuds | Premium | Recently-Restocked | TopPicks | Travel Earbuds | TWS\n321                                                                                                              Noise Air Buds Nano - Truly Wireless Earbuds                                                                  

In [429]:
mask = (
    merged["ocr_playtime_hours"].isna()
    & merged["category_specs"].ne("Wired Earphones")
)

merged.loc[mask, "ocr_playtime_hours"] = pd.to_numeric(
    merged.loc[mask, "tags_raw_specs"].str.extract(
        r"(?i)(\d+(?:\.\d+)?)\s*(?:H(?:ours?)?)\s*(?:Playtime|Playback)"
    )[0],
    errors="coerce"
)

In [431]:
mask = (
    merged["ocr_playtime_hours"].isna()
    & merged["category_specs"].ne("Wired Earphones")
)

print(
    merged.loc[
        mask, "product_name"
    ].str.contains(
        r"(?i)(?:\d+\s*(?:H|Hours?|Hrs?)|Playtime|Playback)",
        regex=True,
        na=False
    ).sum()
)

0

In [433]:
merged["playtime_hours"] = merged["ocr_playtime_hours"]

In [434]:
merged["playtime_hours"].isna().sum()

np.int64(88)

In [435]:
merged["playtime_hours"].value_counts(dropna=False)

playtime_hours
NaN      88
50.0     83
40.0     59
60.0     39
30.0     33
20.0     28
45.0     26
15.0     22
10.0     16
8.0      16
35.0     15
100.0    15
70.0     14
80.0     14
120.0    11
24.0      7
12.0      7
25.0      7
42.0      6
150.0     6
16.0      5
6.0       5
14.0      4
75.0      4
28.0      4
4.0       4
55.0      3
48.0      2
32.0      2
22.0      2
65.0      2
52.0      2
5.0       2
3.0       1
13.0      1
23.0      1
46.0      1
54.0      1
7.0       1
17.0      1
33.0      1
18.0      1
140.0     1
1.0       1
72.0      1
Name: count, dtype: int64

In [436]:
merged.to_csv('boat_noise_cleaned_v3.csv')

In [437]:
merged['ocr_ip_rating'].isna().sum()

np.int64(322)

In [438]:
merged["ip_rating"] = merged["ocr_ip_rating"]

In [439]:
merged["ocr_ip_rating"].value_counts(dropna=False)

ocr_ip_rating
NaN     322
IPX5    148
IPX4     77
IPX7     15
IPX6      2
IP67      1
Name: count, dtype: int64

In [443]:
mask = merged["ocr_ip_rating"].isna()

merged.loc[
    mask,
    "tags_raw_specs"
].str.contains(
    r"(?i)\bIP(?:X\d|\d{2})\b",
    regex=True,
    na=False
).sum()

np.int64(0)

In [446]:
merged["ocr_latency_ms"].value_counts(dropna=False)

ocr_latency_ms
NaN     426
40.0     54
50.0     34
65.0     16
60.0     15
45.0     11
35.0      2
55.0      2
85.0      2
80.0      1
30.0      1
24.0      1
Name: count, dtype: int64

In [447]:
mask = merged["ocr_latency_ms"].isna()

merged.loc[
    mask,
    "description_raw_specs"
].str.contains(
    r"(?i)(?:latency|ms\b)",
    regex=True,
    na=False
).sum()

np.int64(59)

In [450]:
mask = merged["ocr_latency_ms"].isna()

print(
    merged.loc[
        mask, "features_raw_specs"
    ].str.contains(
        r"(?i)\b\d+(?:\.\d+)?\s*ms\b",
        regex=True,
        na=False
    ).sum()
)

0

In [452]:
mask = merged["ocr_latency_ms"].isna()

print(
    merged.loc[
        mask, "tags_raw_specs"
    ].str.contains(
        r"(?i)\b\d+(?:\.\d+)?\s*ms\b",
        regex=True,
        na=False
    ).sum()
)

0

In [453]:
merged["latency_ms"] = merged["ocr_latency_ms"]

In [456]:
merged['ocr_has_anc'].isna().sum()

np.int64(461)

In [458]:
mask = merged["ocr_has_anc"].isna()

for col in [
    "product_name",
    "description_raw_specs",
    "features_raw_specs",
    "specs_raw_json_specs",
    "tags_raw_specs"
]:
    print(
        col,
        merged.loc[mask, col].str.contains(
            r"(?i)\b(?:ANC|active noise cancellation|active noise cancelling)\b",
            regex=True,
            na=False
        ).sum()
    )

product_name 0
description_raw_specs 0
features_raw_specs 0
specs_raw_json_specs 0
tags_raw_specs 2

In [460]:
mask = merged["ocr_has_anc"].isna()

print(
    merged.loc[
        mask
        & merged["tags_raw_specs"].str.contains(
            r"(?i)\b(?:ANC|active noise cancellation|active noise cancelling)\b",
            regex=True,
            na=False
        ),
        ["product_name", "tags_raw_specs"]
    ].to_string(index=False)
)

                                           product_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   tags_raw_specs
                   Noise Airwave Pro Neckband Earphones                                                                                                                                                        _ct-product-type-audio-device_ | _sms-ct-Airwave-Pro_ | _title-ct-Noise-Airwave-Pro-Neckband_ | above-999 | active tune neckband | airwave pro neckband | audio | Audiophiles | bass earphones | best neckband | bestseller-gadget | bestsellers-gadgets | black | codewithcod | codwithcode | Color_Black | ct_pname_Airwave Pro | EARBUDS | earphone | earphones | earphones wireless | enable-add-to-cart-btn | extra5withcode | festitveoffertext_Deal of the Day | festivesale | for-her | gameonsale | headphone | headphones | headphones wireless | hide-limited-offer | hide_fbt | iphone earbud | launchedbeforenov22 | mayart | neckband | neckband earphones | neckband headphones | neckband headset | neckband tun | neckband tune | neckband wireless  earphones | neckband wireless headphones | noise airwave pro | noise neck earphone | noise neckband | noise wireless earphones | Notifyme_stock10 | offline-product | oos-listing | pdpusp2_60 Hour Playtime | pdpusp3_Dual Pairing | pdpusp4_Magnetic on/off | pdpusp5_40ms Low Latency | pdpusp_32dB ANC | Price_Rs. 1000 - Rs. 1999 | rpwithcode | sense | sep24 | title_Airwave Pro | tune series | USP1_32dB ANC | USP2_60H playtime | wireless | wireless airpods | wireless earphone | wireless earphones | wireless neckband | wireless-audio | wireless-earphones-neckband | without-printed-cases | won24
Noise Airwave Pro Neckband Earphones - ABHI Marketplace _ct-product-type-audio-device_ | _sms-ct-Airwave-Pro_ | _title-ct-Noise-Airwave-Pro-Neckband_ | above-999 | active tune neckband | airwave pro neckband | audio | Audiophiles | bass earphones | best neckband | bestseller-gadget | bestseller-gadgets | bestsellers-gadgets | black | codewithcod | codwithcode | Color_Black | ct_pname_Airwave Pro | EARBUDS | earphone | earphones | earphones wireless | enable-add-to-cart-btn | extra5withcode | festitveoffertext_Deal of the Day | festivesale | for-her | gameonsale | headphone | headphones | headphones wireless | hide-limited-offer | hide-share-icon | hide-symbo-insurance | hide_fbt | hide_recently_viewed | iphone earbud | launchedbeforenov22 | mayart | neckband | neckband earphones | neckband headphones | neckband headset | neckband tun | neckband tune | neckband wireless  earphones | neckband wireless headphones | new-offer-widget-hide | no-index | no-product-replace | noise airwave pro | noise neck earphone | noise neckband | noise wireless earphones | Notifyme_stock10 | offline-product | oos-listing | pdpusp2_60 Hour Playtime | pdpusp3_Dual Pairing | pdpusp4_Magnetic on/off | pdpusp5_40ms Low Latency | pdpusp_32dB ANC | Price_Rs. 1000 - Rs. 1999 | rpwithcode | sense | sep24 | st-hide | title_Airwave Pro | tune series | USP1_32dB ANC | USP2_60H playtime | wireless | wireless airpods | wireless earphone | wireless earphones | wireless neckband | wireless-audio | wireless-earphones-neckband | without-printed-cases | won24

In [461]:
merged.loc[
    merged["product_name"].eq("Noise Airwave Pro Neckband Earphones"),
    "has_anc"
] = True

In [469]:
merged['has_anc'].value_counts(dropna=True)

has_anc
True    64
Name: count, dtype: int64

In [464]:
mask = merged["has_anc"].isna()

for col in [
    "tags_raw_specs",
    "features_raw_specs",
    "specs_raw_json_specs",
    "description_raw_specs",
    "features_raw_ocr",
    "specs_raw_json_ocr"
]:
    print(
        col,
        merged.loc[
            mask, col
        ].str.contains(
            r"(?i)\b(?:ANC|active noise cancellation|active noise cancelling)\b",
            regex=True,
            na=False
        ).sum()
    )

tags_raw_specs 51
features_raw_specs 54
specs_raw_json_specs 6
description_raw_specs 55
features_raw_ocr 54
specs_raw_json_ocr 6

In [465]:
mask = (
    merged["has_anc"].isna()
    & merged["description_raw_specs"].str.contains(
        r"(?i)\b(?:ANC|active noise cancellation|active noise cancelling)\b",
        regex=True,
        na=False
    )
)

print(
    merged.loc[
        mask,
        ["product_name", "description_raw_specs"]
    ].to_string(index=False)
)

                                                                                                                                                               product_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    description_raw_specs
                                                        boAt Airdopes 141 ANC | Wireless Earbuds with Active Noise Cancellation up to 32dB, 42 Hours Playback, BEAST™️ Mode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           | Airdopes 141 ANC - Wireless Earbuds with Active Noise Cancellation | Meet Airdopes 141 ANC - the perfect blend of innovation and style. Experience sound like never before with Active Noise Cancellation (ANC) up to 32dB. Enjoy uninterrupted beats with an astounding 42 Hours playback. With Dual EQ Modes, discover the power of choice & embrace the future of sound. | Let Nothing Disturb Your Vibe | Immerse yourself in a world of tranquility with Airdopes 141 ANC's cutting-edge Active Noise Cancellation (ANC) technology, silencing distractions by up to 32dB. Enjoy every beat with great clarity, undisturbed by the outside world. | There’s No Stopping | Immerse in your playlists for every mood with Airdopes 141 ANC, providing an non-stop 42 Hours of uninterrupted playback. Stay tuned in without missing a beat, all day and all night. | Switch According To The Tracks | Airdopes 141 ANC offers Dual EQ Modes: Signature for deep bass and Balanced for crystal-clear tones. Customize your sound, elevate your experience. | The Game Is On | Plug into an expertly tuned lag-free audio experience with BEAST™️ Mode giving 50 ms of low latency, designed to level up all your streaming and gaming sessions. | You Can’t Be Clearer Than This | Seamless communication redefined - Airdopes 141 ANC wireless earbuds boasts Quad mics with ENx™️ Technology, ensuring crystal-clear calls for an enhanced talking experience. | FAQs | Q. How long does Airdopes 141ANC last on a single charge? | boAt Airdopes 141ANC wireless earbuds offer battery backup of up to 42 hours on a single charge. | Q. Does it support Active Noise Cancellation? | Yes, Airdopes 141ANC does support Active Noise Cancellation. With up to 32dB ANC, enjoy your playlist uninterrupted. | Q. Can I charge my earphones with a mobile charger? | Yes, Airdopes 141ANC supports Type-C charging. If your mobile charger comes with Type-C charging port, then you can use the same to charge your Airdopes. | Q. Is it good for longer calls? | Yes, these wireless earbuds come with Quad mics with ENx™️ Technology, ensuring crystal-clear calls for an enhanced talking experience. | Q. Is there a warranty for the product? How do I claim warranty? | Yes, all of our true wireless earbuds come with a 1 year warranty. To register your device, visit https://support.boat-lifestyle.com/. |
                                                                           boAt Airdopes 393 ANC | Bluetooth Earbuds with 30 Hours of Playtime, Beast Mode, ENx™ technology                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 | Airdopes 393 ANC - Bluetooth Earbuds with Noise Cancellation | Cut the noise out with Airdopes 393 ANC. Featuring hybrid active noise cancellation that actively and passively suppresses background noise. With ENx™ technology, calling could not have been better as the mic isolates your voice and simply cuts out the rest to enable the best calling experience. All that with ASAP™ fast charge and a monstrous battery life of 30 hours that can simply last all day without worry. Get a jump start with Airdopes 393 ANC. | No Space For Noise | With a hybrid active noise cancellation solution, background noise is actively and passively suppressed down to 32db+ which ensures only you only experience musical harmony without any hitch. | Bring Out the Beast | Packed with the latest tech in the business, ENx™ technology and BEAST™ mode effectively enable the best media experience when paired together. Only your voice is picked up by the mic whereas BEAST™ mode converts audio data super fast which ensures there is no audio lag in your experience. | Lasts All Day | You heard it right, Airdopes 393 ANC comes with a massive battery that can last up to 30 hours on a single charge and 26 hours with ANC mode turned on. It also feature ASAP™ fast charging that gives a playtime of 45 mins with only 5 mins of charge which means you never run out of juice. | Quality And Durability | Airdopes 393 ANC is not only the best when it comes to sound but also the best when it comes to reliability. It features an IPX5 water resistance rating which ensures that all the good bits are protected and you can take it everywhere without worry. | Seamlessly Connected | With BlueTooth 5.2, Airdopes 393 ANC gets seamless connectivity whenever you want but also features IWP™ technology that instantly pairs the moment the lid comes on. You no longer need to go into your settings to connect to your Airdopes 393 ANC, it does it for you!! | FAQs | Q. How can we pause and play tracks? | Single tap the capacitive touch control on either earbud to play a song or to pause one. Airdopes 393 ANC comes with a host of intuitive features that allow one to seamlessly control music. Please refer to the instruction manual to learn about the different ways one can take advantage of its features. | Q. Can we accept calls on boAt Airdopes 393 ANC? | Yes, Airdopes 393 ANC comes with BEAST mode and ENx™ noise cancellation technology that suppresses background noise when speaking into the mic and low latency audio which allows for an unrivalled calling and media experience. | Q. Can I use any adapter to charge my device? | Yes, you can use any Type-C compatible adapter to charge your Airdopes 393 ANC Charging case. | Q. Are Airdopes 393 ANC waterproof and sweat resistant? | Yes, Airdopes 393 ANC is IPX5 Water and Sweat resistant. You can use it for your workouts or carry them along on long trips. | Q. How long does boAt Airdopes 393 ANC last on a single charge? | Airdopes 393 ANC wireless earbuds offer a total battery backup of up to 30 hours. It also supports ASAP fast charge that yields a playtime of 45 mins with only 5 minutes of charging time. | Q. Can I charge my earphones with a mobile charger? | Yes, Airdopes 393 ANC supports Type-C charging. If your mobile charger comes with Type-C charging support then you can easily use the same to charge your device. | Q. Is it good for longer gym workouts and sweating over 2+ hours? | Yes, Airdopes 393 ANC comes with IPX5 water resistance along with a huge battery capacity making it perfect for gym workouts that last more than 2 hours. | Q. Can I charge my earphones while the case is being charged? | Yes, one can simultaneously charge the carrying case and the Bluetooth earbuds at the same time. | Q. What is the use of the charging case? | The charging case is ergonomically designed to be portable. You can carry your in-ear earbuds around while they are being charged in the case. | Q. What Bluetooth version does boAt Airdopes 393 ANC support? | Airdopes 393 ANC earbuds come with Bluetooth v5.2 technology. These in-ear earbuds also support all previous versions of Bluetooth. ;;;; | Q. Is there a warranty for the product? How do I claim warranty? | Yes, all of our true wireless earphones come with a 1 year warranty. To register your device, visit https://support.boat-lifestyle.com/. |

In [472]:
mask = (
    merged["ocr_has_anc"].isna()
    & merged["description_raw_specs"].str.contains(
        r"(?i)\b(?:ANC|active noise cancellation|active noise cancelling)\b",
        regex=True,
        na=False
    )
)

merged.loc[mask, "ocr_has_anc"] = True

In [467]:
mask = (
    merged["has_anc"].isna()
    & merged["features_raw_specs"].str.contains(
        r"(?i)\b(?:ANC|active noise cancellation|active noise cancelling)\b",
        regex=True,
        na=False
    )
)

merged.loc[
    mask,
    ["product_name", "features_raw_specs"]
]

                                                                                                               product_name                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       features_raw_specs
225   Nirvana Eutopia - Dhruv Kapoor Edition | Wireless Headphone with 20H Playback, Dual Mics with ENx™ Tech, ASAP™ Charge                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         ANC | https://www.boat-lifestyle.com/products/nirvana-751-anc-headphone | Manual_live | Noise Cancelling Headphones | Premium | Summer 400 | Super Savers | wireless headphones | specifications
244  boAt Rockerz 370 Pro | Wireless Headphones with 40 Hours Playback, Voice Assistant, boAt Signature Sound, BEAST™️ Mode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                   https://www.boat-lifestyle.com/products/nirvana-751-anc-headphone | Recently-Restocked | Snapmint | Super Savers | wireless headphones
301                     boAt Nirvana Eutopia | Wireless Headphone with 20H Playback, Dual Mics with ENx™ Tech, ASAP™ Charge                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        ANC | https://www.boat-lifestyle.com/products/nirvana-751-anc-headphone | Premium
329                                                                                Noise Air Clips 2 OWS Open Ear Headphone  _ct-product-type-audio-device_ | _sms-ct-Air Clips 2 | _title-ct-Air Clips 2 | _title-ct-Air-Clips-2_ | above-999 | Air Clips 2 | anc-collection | audio | bestsellers-gadgets | categoryid_Earphone | CL_1_best wireless earbuds under 3000 | CL_2_best earbuds under 5000 | CL_3_best wireless earphones under 3000 | CL_4_best wireless earbuds | earphones wireless | Eligible | enable-add-to-cart-btn | fb-feed-product | for-him | Gaming | hide-limited-offer | latest wireless earphones | light weight earbuds | noise Air Clips 2 | noise earbuds | noise wireless earphones | pdpusp2_Open Beam Design | pdpusp_40H Playtime with Touch Controls | show_product_compare | sweatproof earbuds | sweatproof earphones | title_Air Clips 2 | touch-controlled earphones | tru_bass_technology_yes | truly wireless earbuds | udpusp_Airwave™ Technology | usp1_OWS with Airwave™ Technology | usp_40H Playtime with Touch Controls | vdgiftbox | waterproof wireless earphones
331                                                                              Noise Air Clips Pro OWS Open Ear Headphone                                  _ct-product-type-audio-device_ | _sms-ct-Air Clips 2 | _title-ct-Air Clips 2 | _title-ct-Air-Clips-2_ | above-999 | Air Clips 2 | anc-collection | audio | bestseller-gadgets | bestsellers-gadgets | categoryid_Earphone | CL_1_best wireless earbuds under 3000 | CL_2_best earbuds under 5000 | CL_3_best wireless earphones under 3000 | CL_4_best wireless earbuds | disable-notifications-peppyduck | earphones wireless | Eligible | enable-add-to-cart-btn | fb-feed-product | for-him | Gaming | hide-limited-offer | insurance-popup-enabled | latest wireless earphones | light weight earbuds | new-offer-timer | noise Air Clips 2 | noise earbuds | noise wireless earphones | Notifyme_stock20 | Notifyme_stock50 | pdptext_Use your pass code to get ₹1499 off | show_product_compare | sweatproof earbuds | sweatproof earphones | title_Air Clips Pro | touch-controlled earphones | tru_bass_technology_yes | truly wireless earbuds
460                                                              Noise Master Buds Truly Wireless Earbuds - Special Edition                                                                                                                                                                                                                                                                          anc-collection | bestseller-gadget | bestseller-gadgets-notifyme | bestsellers-gadgets | bt_v5.1 | codewithcod | codwithcode | Eligible | emi-snapmint-store | enable-add-to-cart-btn | fb-feed-product | hide-limited-offer | latest wireless earphones | light weight earbuds | Master Buds | master-buds-le-pass | new-offer-timer | noise buds | noise Master Buds | Notifyme_stock20 | pdpusp2_LHDC 5.0 | pdpusp3_Spatial Audio | pdpusp_Adaptive ANC 49dB | product-video-margin | ShippingText | show-full-title | show_product_compare | snapmint | title_Master Buds - Special Edition | usp1_Adaptive ANC 49dB | usp2_LHDC 5.0 | whatsapp-bot | wireless-audio | wireless-earbuds | WIRELESS-EARPHONE
526    boAt Rockerz 400 Pro | Wireless Earphone with 30 Hours Playback, Voice Assistant, boAt Signature Sound, BEAST™️ Mode                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                       https://www.boat-lifestyle.com/products/nirvana-751-anc-headphone | specifications
530   boAt Rockerz 430 | Wireless Headphone with ENx™ Tech, 40 HRS Playback,  BEAST™ Mode, Type-C Interface, Bluetooth v5.4                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            https://www.boat-lifestyle.com/products/nirvana-751-anc-headphone | Long Playback Headphones | specifications

In [470]:
mask = (
    merged["ocr_has_anc"].isna()
    & merged["features_raw_specs"].str.contains(
        r"(?i)\bANC\b|anc-collection",
        regex=True,
        na=False
    )
)

merged.loc[mask, "ocr_has_anc"] = True

In [473]:
merged['ocr_has_anc'].value_counts()

ocr_has_anc
True    104
Name: count, dtype: int64

In [474]:
for col in [
    "product_name",
    "description_raw_specs",
    "features_raw_specs",
    "specs_raw_json_specs",
    "tags_raw_specs",
    "features_raw_ocr",
    "specs_raw_json_ocr"
]:
    mask = (
        merged["ocr_has_anc"].isna()
        & merged[col].str.contains(
            r"(?i)\bANC\b|active noise cancellation|active noise cancelling|anc-collection",
            regex=True,
            na=False
        )
    )
    print(col, mask.sum())

product_name 0
description_raw_specs 0
features_raw_specs 0
specs_raw_json_specs 0
tags_raw_specs 2
features_raw_ocr 0
specs_raw_json_ocr 0

In [477]:
mask = (
    merged["ocr_has_anc"].isna()
    & merged["tags_raw_specs"].str.contains(
        r"(?i)\bANC\b|active noise cancellation|active noise cancelling|anc-collection",
        regex=True,
        na=False
    )
)

merged.loc[mask, "ocr_has_anc"] = True

In [481]:
merged['ocr_has_anc'].value_counts(dropna=False)

ocr_has_anc
False    459
True     106
Name: count, dtype: int64

In [480]:
merged["ocr_has_anc"] = merged["ocr_has_anc"].fillna(False)

In [483]:
merged['ocr_has_enc'].value_counts(dropna=False)

ocr_has_enc
True    301
NaN     264
Name: count, dtype: int64

In [485]:
for col in [
    "product_name",
    "description_raw_specs",
    "features_raw_specs",
    "specs_raw_json_specs",
    "tags_raw_specs",
    "features_raw_ocr",
    "specs_raw_json_ocr"
]:
    mask = (
        merged["ocr_has_enc"].isna()
        & merged[col].str.contains(
            r"(?i)\bENC\b|\bENx\b|environmental noise cancellation|environmental noise cancelling",
            regex=True,
            na=False
        )
    )
    print(col, mask.sum())

product_name 0
description_raw_specs 0
features_raw_specs 0
specs_raw_json_specs 0
tags_raw_specs 4
features_raw_ocr 0
specs_raw_json_ocr 0

In [490]:
mask = (
    merged["ocr_has_enc"].isna()
    & merged["tags_raw_specs"].str.contains(
        r"(?i)\bENC\b|\bENx\b|environmental noise cancellation|environmental noise cancelling",
        regex=True,
        na=False
    )
)

merged.loc[
    mask,
    ["ocr_has_enc"]
]=True

In [491]:
for col in [
    "product_name",
    "description_raw_specs",
    "features_raw_specs",
    "specs_raw_json_specs",
    "features_raw_ocr",
    "specs_raw_json_ocr"
]:
    mask = (
        merged["ocr_has_enc"].isna()
        & merged[col].str.contains(
            r"(?i)\bENC\b|\bENx\b|environmental noise cancellation|environmental noise cancelling",
            regex=True,
            na=False
        )
    )
    print(col, mask.sum())

product_name 0
description_raw_specs 0
features_raw_specs 0
specs_raw_json_specs 0
features_raw_ocr 0
specs_raw_json_ocr 0

In [492]:
mask = (
    merged["ocr_has_enc"].isna()
    & merged["tags_raw_specs"].str.contains(
        r"(?i)\bENC\b|\bENx\b|environmental_noise_cancellation_yes",
        regex=True,
        na=False
    )
)

merged.loc[mask, "ocr_has_enc"] = True

In [493]:
merged['ocr_has_enc'].value_counts()

ocr_has_enc
True    306
Name: count, dtype: int64

In [494]:
merged["ocr_has_enc"] = merged["ocr_has_enc"].fillna(False)

In [496]:
for col in [
    "product_name",
    "description_raw_specs",
    "features_raw_specs",
    "specs_raw_json_specs",
    "tags_raw_specs",
    "features_raw_ocr",
    "specs_raw_json_ocr"
]:
    mask = (
        merged["ocr_has_anc"].eq(True)
        & merged[col].str.contains(
            r"(?i)(?:anc|active_noise_cancellation|noise_cancellation)[_-]no\b",
            regex=True,
            na=False
        )
    )
    print(col, mask.sum())

product_name 0
description_raw_specs 0
features_raw_specs 19
specs_raw_json_specs 0
tags_raw_specs 19
features_raw_ocr 19
specs_raw_json_ocr 0

In [500]:
mask = (
    merged["ocr_has_anc"].eq(True)
    & merged["features_raw_specs"].str.contains(
        r"(?i)(?:anc|active_noise_cancellation|noise_cancellation)[_-]no\b",
        regex=True,
        na=False
    )
)

merged.loc[
    mask,
    "ocr_has_anc"
]

271    True
323    True
324    True
325    True
326    True
327    True
334    True
335    True
337    True
339    True
352    True
376    True
377    True
401    True
409    True
417    True
419    True
440    True
444    True
Name: ocr_has_anc, dtype: object

In [501]:
merged.to_csv('boat_noise_cleaned_v4.csv')

In [502]:
merged['ocr_water_resistance'].value_counts(dropna=False)

ocr_water_resistance
NaN     322
IPX5    148
IPX4     77
IPX7     15
IPX6      2
IP67      1
Name: count, dtype: int64

In [503]:
for col in [
    "product_name",
    "description_raw_specs",
    "features_raw_specs",
    "specs_raw_json_specs",
    "features_raw_ocr",
    "specs_raw_json_ocr"
]:
    mask = (
        merged["ocr_water_resistance"].isna()
        & merged[col].str.contains(
            r"(?i)\bIP\d{2}\b|\bIPX\d\b|water\s*resistan|waterproof|water\s*proof|splash\s*proof|sweat\s*proof",
            regex=True,
            na=False
        )
    )
    print(col, mask.sum())

product_name 0
description_raw_specs 7
features_raw_specs 9
specs_raw_json_specs 0
features_raw_ocr 9
specs_raw_json_ocr 0

In [506]:
mask = (
    merged["ocr_water_resistance"].isna()
    & merged["features_raw_specs"].str.contains(
        r"(?i)\bIP\d{2}\b|\bIPX\d\b|water\s*resistan|waterproof|water\s*proof|splash\s*proof|sweat\s*proof",
        regex=True,
        na=False
))

merged.loc[
    mask,
    ["product_name", "features_raw_specs"]
]

,product_name,features_raw_specs
14,"boAt Airdopes 131 Batman DC Edition | Wireless Earbuds with 13 mm Drivers, Bluetooth v5.0, 650mAh pocket friendly Charging Case","Airdopes | All products | Audio-Category | boAt|DC | Collectibles | Country Code: CN | DC | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Limited Edition Earbuds | Recently-Restocked | SuperHero | Superrr | Airdopes 131 Wireless Earbuds - Batman DC Edition | Listen to music that packs a real punch like the the Dark Knight on the all-new Airdopes 131 boAt | Super Connectivity | 13 mm Drivers | Feels Like You Can Fly | Q. How can we pause and play tracks? | Q. Can we accept calls on boAt Airdopes 131? | Q. Can I use any adapter to charge my device? | Yes, you can use any adapter to charge your Airdopes 131 Charging case. | Q. Are Airdopes 131 waterproof and sweat resistant? | NO, Airdopes 131 does not come with dust & water resistance. | Q. How long does Airdopes 131 last on a single charge? | Q. What is the battery capacity of Airdopes 131 and how long does it take to charge? | Q. Does it support fast charging? | No, Airdopes 131 supports only standard charging. | Q. Can I charge my earphones with a mobile charger? | Q. Can I charge my earphones while the case is being charged? | Yes, one can simultaneously charge the carrying case and the bluetooth earbuds at the same time. | Q. What is the use of the charging case? How long does it take the charging case to charge? | Q. What Bluetooth version do boAt Airdopes 131 support? | Q. Are they compatible with iPhones and Android phones? | Yes, Airdopes 131 are fully compatible with iPhones and Android devices. | Q. How do I reboot/restart my earbuds? | Q. How do I factory reset my earbud? | Step 1: Keep both the earbuds inside the case in their correct orientation | Step 2: Triple tap the MFB on both earbuds to perform the reset. Red LED blinks for 1 sec to indicate the same. | Step 3: After the reset, close the lid of the carry case | Please refer to the manual for further assistance."
15,"Airdopes 131 DC Edition | 13 mm Drivers, Type-C Carry Case, 12 hours Nonstop Music","Airdopes | All products | Audio-Category | boAt|DC | Collectibles | Country Code: CN | DC | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Limited Edition Earbuds | SuperHero | Superrr | Airdopes 131 DC Edition - True Wireless Earbuds | Super Connectivity | 13 mm Drivers | Feels Like You Can Fly | Q. How can we pause and play tracks? | Q. Can we accept calls on boAt Airdopes 131? | Q. Can I use any adapter to charge my device? | Yes, you can use any adapter to charge your Airdopes 131 Charging case. | Q. Are Airdopes 131 waterproof and sweat resistant? | NO, Airdopes 131 does not come with dust & water resistance. | Q. How long does Airdopes 131 last on a single charge? | Q. What is the battery capacity of Airdopes 131 and how long does it take to charge? | Q. Does it support fast charging? | No, Airdopes 131 supports only standard charging. | Q. Can I charge my earphones with a mobile charger? | Q. Can I charge my earphones while the case is being charged? | Yes, one can simultaneously charge the carrying case and the bluetooth earbuds at the same time. | Q. What is the use of the charging case? How long does it take the charging case to charge? | Q. What Bluetooth version do boAt Airdopes 131 support? | Q. Are they compatible with iPhones and Android phones? | Yes, Airdopes 131 are fully compatible with iPhones and Android devices. | Q. How do I reboot/restart my earbuds? | Q. How do I factory reset my earbud? | Step 1: Keep both the earbuds inside the case in their correct orientation | Step 2: Triple tap the MFB on both earbuds to perform the reset. Red LED blinks for 1 sec to indicate the same. | Step 3: After the reset, close the lid of the carry case | Please refer to the manual for further assistance. | Q. How can I connect with Google and Siri? | Q. Is there a warranty for the product? How do I claim warranty?"
21,"boAt Airdopes 131 | Wireless Earbuds Superman DC Edition Earbuds with 13 mm Drivers, Upto 12 hours Nonstop Music, 650mAh Pocket Friendly Charging Case","Airdopes | All products | Audio-Category | Best-boat-sale | boAt|DC | Collectibles | Country Code: CN | DC | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Limited Edition Earbuds | SuperHero | Superrr | boAt Airdopes 131 Superman DC Edition | If your every move drips of power, the powerful sound of Airdopes 131 boAt | Super Connectivity | 13 mm Drivers | Feels Like You Can Fly | Q. How can we pause and play tracks? | Q. Can we accept calls on boAt Airdopes 131? | Q. Can I use any adapter to charge my device? | Yes, you can use any adapter to charge your Airdopes 131 Charging case. | Q. Are Airdopes 131 waterproof and sweat resistant? | NO, Airdopes 131 does not come with dust & water resistance. | Q. How long does Airdopes 131 last on a single charge? | Q. What is the battery capacity of Airdopes 131 and how long does it take to charge? | Q. Does it support fast charging? | No, Airdopes 131 supports only standard charging. | Q. Can I charge my earphones with a mobile charger? | Q. Can I charge my earphones while the case is being charged? | Yes, one can simultaneously charge the carrying case and the bluetooth earbuds at the same time. | Q. What is the use of the charging case? How long does it take the charging case to charge? | Q. What Bluetooth version do boAt Airdopes 131 support? | Q. Are they compatible with iPhones and Android phones? | Yes, Airdopes 131 are fully compatible with iPhones and Android devices. | Q. How do I reboot/restart my earbuds? | Q. How do I factory reset my earbud? | Step 1: Keep both the earbuds inside the case in their correct orientation | Step 2: Triple tap the MFB on both earbuds to perform the reset. Red LED blinks for 1 sec to indicate the same. | Step 3: After the reset, close the lid of the carry case | Please refer to the manual for further assistance."
170,"boAt Airdopes 138 | Wireless Earbuds with 13mm Drivers, Bluetooth V5.0+EDR, IWP Technology, 650mAh Pocket friendly Charging Case, 60 Hours nonstop music","15% | All products | all-wireless | allprod | Audio-Category | Audiophiles | Audiophille | Country Code: CN | customized | FashionApp | holi | importer details Imagine Marketing Pvt Ltd. E Wing Unit 505 Wing 2 Corporate Avenue Atul Projects Andheri East Mumbai Maharashtra-411093 | Large Playback Earbuds | offline | Personalized Products | Prime-Days-Sale | Recently-Restocked | recommend-type-c-a350-cable-1-5-meter | Super Savers | TWS | Ultimate | Wireless | boAt Airdopes 138 - Wireless Earbuds | Connected every moment | boAt Signature Sound for music lovers | Featherweight for comfort all-day | Feel your music, never the weight of your earbuds. Wireless earbuds designed for ease and flexibility. | Upto 60 hours playback time | Q. How can we pause and play tracks? | Q. Can we accept calls on boAt Airdopes 138? | Q. Can I use any adapter to charge my device? | Yes, you can use any adapter to charge your Airdopes 138 Charging case. | Q. Are Airdopes 138 waterproof and sweat resistant? | NO, Airdopes 138 does not come with dust & water resistance. | Q. How long does Airdopes 138 last on a single charge? | Q. What is the battery capacity of Airdopes 138 and how long does it take to charge? | Q. Does it support fast charging? | No, Airdopes 138 supports only standard charging. | Q. Can I charge my earphones with a mobile charger? | Q. Can I charge my earphones while the case is being charged?"
321,Noise Air Buds Nano - Truly Wireless Earbuds,_ct-product-type-audio-device_ | _sms-ct-Air Buds Nano | _title-ct-Airbuds Nano | _title-ct-Airbuds-Nano_ | above-999 | Air Bud Nano | Air Buds Nano | Airbuds Nano | audio | ckoffline | CL_1_best wireless earbuds under 3000 | CL_2_best earbuds under 5000 | CL_3_best wireless earphones under 3000 | CL_4_best wireless earbuds | codwithcode | Color_White | earphones wireless | enable-add-to-cart-btn | extra5withcode | feather-weight earbuds | great-gadget-days | hide-limited-offer | hide_fbt | latest wireless earphones | launchedbeforenov22 | light weight earbuds | moise Airbuds nano | nav_new_tag | no-black-friday | no-cod | no-discount | noise Air buds nano | noise earbuds | noise wireless earphones | Notifyme_stock10 | offline-product | product_description | st_color: Jet Black | strap-description | sweatproof earbuds
333,Noise Airwave Max 2 Wireless Headphone,_ct-product-type-audio-device_ | _sms-ct-Noise TWO Wireless Headphone | _title-ct-Noise TWO Wireless Headphone | above-999 | active_noise_cancellation_no | bestseller-gadgets | bestseller-gadgets-notifyme | bestsellers-gadgets | black | charging_port_usb type-c | charging_time_upto 2 hours | codewithcod | codwithcode | driver_40mm | dual_pairing_yes | Eligible | enable-add-to-cart-btn | focusjuly24 | gonoise headphones | hands_free_calling_yes | headphone-collection | headphones | headphones-collection | hide-limited-offer | instacharge_yes | noise headphones | noise wireless headphones | Notifyme_stock20 | partner-fk | partners-feb22 | pdpusp_50 Hour Playtime | playtime_upto 25 hours | productivity-pros | rdsale | react-headphones | sweatproof headphones | title_Airwave Max 2 | tru_bass_technology_yes | USP_50H Playtime | 40mm Driver | water_resistance_ipx4
363,Noise Buds Combat X Truly Wireless Earbuds,_ct-product-type-audio-device_ | _sms-ct-Buds Combat X | _title-ct-Buds Combat X | _title-ct-Buds-Combat-X_ | above-999 | audio | bestsellers-gadgets | Buds Combat X | categoryid_Earphone | cl0_Gaming earbuds | cl1_AUDIO | codewithcod | codwithcode | Combat X | cupidsalesountrack | earphones wireless | enable-add-to-cart-btn | focusjuly24 | for-him | Gaming | gupshup-listing | hide-limited-offer | hide_fbt | latest wireless earphones | light weight earbuds | noise Buds Combat X | noise earbuds | noise wireless earphones | Notifyme_stock10 | ondc | pdpusp3_Gaming Mode | pdpusp_Up to 60 hours of Playtime | popular-noisefitapp | quiz_fitness | quiz_friends | quiz_music | quiz_parent | snapmint | st_color: Jet Black | sweatproof earbuds
465,Noise Powr Wireless Headphone,_ct-product-type-audio-device_ | _sms-ct-Noise Powr Wireless Headphone | _title-ct-Noise Powr Wireless Headphone | above-999 | active_noise_cancellation_no | black | charging_port_usb type-c | charging_time_upto 2 hours | driver_40mm | dual_pairing_yes | enable-add-to-cart-btn | gonoise headphones | hands_free_calling_yes | headphone-collection | headphones | headphones-collection | hide-limited-offer | hide_fbt | instacharge_yes | no-discount | no-index | noise headphones | noise powr | noise Powr headphone | noise wireless headphones | Notifyme_stock20 | partner-fk | partners-feb22 | playtime_upto 25 hours | powr | rdsale | react-headphones | st-hide | sweatproof headphones | title_Noise Powr | tru_bass_technology_yes | water_resistance_ipx4 | waterproof wireless headphones | wireless | wireless headphones
473,Noise TWO Wireless Headphone,_ct-product-type-audio-device_ | _sms-ct-Noise TWO Wireless Headphone | _title-ct-Noise TWO Wireless Headphone | above-999 | active_noise_cancellation_no | bestseller-gadgets-notifyme | bestsellers-gadgets | black | charging_port_usb type-c | charging_time_upto 2 hours | codewithcod | codwithcode | driver_40mm | dual_pairing_yes | Eligible | enable-add-to-cart-btn | focusjuly24 | gonoise headphones | hands_free_calling_yes | headphone-collection | headphones | headphones-collection | hide-limited-offer | instacharge_yes | noise headphones | noise TWO | noise TWO headphone | noise wireless headphones | Notifyme_stock20 | partner-fk | partners-feb22 | pdpusp5_BT v5.3 Dual Pairing | pdpusp_50 Hour Playtime | playtime_upto 25 hours | productivity-pros | rdsale | react-headphones | sweatproof headphones | title_Noise TWO | tru_bass_technology_yes

In [507]:
merged.to_csv('merged_pasted.csv')

In [508]:
merged.columns

Index(['brand_specs', 'product_name', 'category_specs', 'sale_price_min_inr_specs', 'sale_price_max_inr_specs', 'mrp_inr_specs', 'discount_percent_specs', 'num_variants_specs', 'colors_specs', 'tags_raw_specs', 'features_raw_specs', 'specs_raw_json_specs', 'description_raw_specs', 'published_at_specs', 'base_product', 'edition_type', 'model_series', 'published_year', 'published_month', 'color_count', 'driver_size_mm', 'brand_ocr', 'handle', 'product_url', 'category_ocr', 'product_type', 'collection_source', 'vendor', 'sale_price_min_inr_ocr', 'sale_price_max_inr_ocr', 'mrp_inr_ocr', 'discount_percent_ocr', 'num_variants_ocr', 'colors_ocr', 'skus', 'in_stock_variants', 'tags_raw_ocr', 'features_raw_ocr', 'specs_raw_json_ocr', 'description_raw_ocr', 'image_url', 'created_at', 'updated_at', 'published_at_ocr', 'product_id', 'ocr_images_used', 'ocr_text_raw', 'ocr_playtime_hours', 'ocr_playback_per_charge_hours', 'ocr_driver_mm', 'ocr_bluetooth', 'ocr_ip_rating', 'ocr_anc_db', 'ocr_latency_ms', 'ocr_fast_charge_note', 'ocr_has_anc', 'ocr_has_enc', 'ocr_water_resistance', 'playtime_hours', 'ip_rating', 'latency_ms', 'has_anc'], dtype='str')

In [509]:
merged.drop(columns=['has_anc'],inplace=True)

In [527]:
merged['ocr_water_resistance'].value_counts(dropna=False)

ocr_water_resistance
NaN     290
IPX5    168
IPX4     89
IPX7     15
IPX6      2
IP67      1
Name: count, dtype: int64

In [526]:
mask = merged["ocr_water_resistance"].isna()

features_ip = (
    merged.loc[mask, "features_raw_specs"]
    .str.extract(r"(?i)\bwater_resistance_(IPX\d|IP\d{2})\b")[0]
    .str.upper()
)

tags_ip = (
    merged.loc[mask, "tags_raw_specs"]
    .str.extract(r"(?i)\bwater_resistance_(IPX\d|IP\d{2})\b")[0]
    .str.upper()
)

ip = features_ip.combine_first(tags_ip)

merged.loc[mask, "ocr_water_resistance"] = ip

In [531]:
merged['ocr_has_anc'].value_counts()

ocr_has_anc
False    459
True     106
Name: count, dtype: int64

In [532]:
merged['ocr_has_enc'].value_counts()

ocr_has_enc
True     306
False    259
Name: count, dtype: int64

In [543]:
merged['latency_ms'].isna().sum()

np.int64(426)

In [550]:
merged.loc[
    merged["latency_ms"].isna() & merged["ocr_latency_ms"].notna(),
    ["product_name", "ocr_latency_ms", "latency_ms"]
]

Empty DataFrame
Columns: [product_name, ocr_latency_ms, latency_ms]
Index: []

In [552]:
merged['ocr_latency_ms'].isna().sum()

np.int64(426)

In [554]:
for col in merged.columns:
    count = merged.loc[
        merged["latency_ms"].isna(),
        col
    ].astype(str).str.contains(
        r"(?i)\blatency\b",
        na=False
    ).sum()

    if count > 0:
        print(col, count)

product_name 2
tags_raw_specs 6
features_raw_specs 10
specs_raw_json_specs 5
description_raw_specs 25
tags_raw_ocr 6
features_raw_ocr 10
specs_raw_json_ocr 5
description_raw_ocr 25
ocr_text_raw 16
ocr_fast_charge_note 2

In [556]:
merged.loc[449, "latency_ms"] = 45
merged.loc[5, "latency_ms"] = 500
merged.loc[494, "latency_ms"] = 400

In [577]:
merged['driver_size_mm'].value_counts(dropna=False)

driver_size_mm
10.0    175
NaN     143
13.0     71
40.0     58
11.0     38
6.0      30
50.0     14
12.0      8
8.0       7
7.0       7
14.2      7
12.4      2
16.0      1
15.0      1
18.0      1
14.8      1
30.0      1
Name: count, dtype: int64

In [561]:
merged.loc[
    merged["category_specs"].eq("Wired Earphones"),
    "latency_ms"
] = 0

In [564]:
merged.to_csv('boat_noise_cleaned_v5.csv')

In [568]:
merged['driver_size_mm'].isna().sum()*100/565

np.float64(33.6283185840708)

In [569]:
merged.columns

Index(['brand_specs', 'product_name', 'category_specs', 'sale_price_min_inr_specs', 'sale_price_max_inr_specs', 'mrp_inr_specs', 'discount_percent_specs', 'num_variants_specs', 'colors_specs', 'tags_raw_specs', 'features_raw_specs', 'specs_raw_json_specs', 'description_raw_specs', 'published_at_specs', 'base_product', 'edition_type', 'model_series', 'published_year', 'published_month', 'color_count', 'driver_size_mm', 'brand_ocr', 'handle', 'product_url', 'category_ocr', 'product_type', 'collection_source', 'vendor', 'sale_price_min_inr_ocr', 'sale_price_max_inr_ocr', 'mrp_inr_ocr', 'discount_percent_ocr', 'num_variants_ocr', 'colors_ocr', 'skus', 'in_stock_variants', 'tags_raw_ocr', 'features_raw_ocr', 'specs_raw_json_ocr', 'description_raw_ocr', 'image_url', 'created_at', 'updated_at', 'published_at_ocr', 'product_id', 'ocr_images_used', 'ocr_text_raw', 'ocr_playtime_hours', 'ocr_playback_per_charge_hours', 'ocr_driver_mm', 'ocr_bluetooth', 'ocr_ip_rating', 'ocr_anc_db', 'ocr_latency_ms', 'ocr_fast_charge_note', 'ocr_has_anc', 'ocr_has_enc', 'ocr_water_resistance', 'playtime_hours', 'ip_rating', 'latency_ms'], dtype='str')

In [571]:
merged.loc[
    merged["driver_size_mm"].eq(35),
    [
        "product_name",
        "description_raw_specs",
        "features_raw_specs",
        "specs_raw_json_specs",
        "tags_raw_specs",
        "ocr_text_raw",
        "ocr_driver_mm",
        "driver_size_mm"
    ]
]

                                                                    product_name description_raw_specs                                                                                                                         features_raw_specs specs_raw_json_specs                                                                                                                                                                tags_raw_specs                                                                                                                                                                                            ocr_text_raw  ocr_driver_mm  driver_size_mm
200  boAt Airdopes Plus 224 | TWS Earbuds with 60 Hours Playback & Spatial Audio                   NaN  Audio-Category | Bluetooth Earphones | Large Playback Earbuds | newlaunch | Premium | Recently-Restocked | Spotify | Travel Earbuds | TWS                  NaN  Audio-Category | Bluetooth Earphones | Free-Spotify | Large Playback Earbuds | newlaunch | no-product-banner | Premium | Recently-Restocked | Spotify | Travel Earbuds | TWS  Segment’s First Spatial Audio\n\nImmersive Surround Sound\n---\nTotal Playtime\n\nUp to 60 Hours\n\nAOMINS CHARCE = A450MINS PLAYTIME\n---\ny |\n\nmans?\n\nboAt Signature Sound\n\nwith 135mm Drivers           35.0            35.0

In [572]:
merged.loc[200, "driver_size_mm"] = 13

In [574]:
import re
import pandas as pd

# NOTE: assumes your working dataframe is called `merged`.
# If yours has a different name, rename it below or find-and-replace.

def safe(x):
    return "" if pd.isna(x) else str(x)

# Combine all text sources that might mention driver size
driver_text_blob = (
    merged['product_name'].apply(safe) + " " +
    merged['description_raw_specs'].apply(safe) + " " +
    merged['features_raw_specs'].apply(safe) + " " +
    merged['tags_raw_specs'].apply(safe) + " " +
    merged['ocr_text_raw'].apply(safe) + " " +
    merged['description_raw_ocr'].apply(safe) + " " +
    merged['features_raw_ocr'].apply(safe)
)

def extract_driver_strict(text):
    """
    Find all '<number>mm' mentions where the word 'driver' appears
    within ~25 characters of the number - this avoids false positives
    from unrelated mm mentions (cable length, case dimensions, etc).
    Returns a list of all matches found (a product can have dual drivers).
    """
    results = []
    for match in re.finditer(r'(\d+(?:\.\d+)?)\s*mm', text, re.IGNORECASE):
        start, end = match.span()
        context = text[max(0, start - 25):end + 25].lower()
        if 'driver' in context:
            results.append(float(match.group(1)))
    return results

merged['driver_extracted_list'] = driver_text_blob.apply(extract_driver_strict)
merged['driver_extracted_primary'] = merged['driver_extracted_list'].apply(
    lambda x: x[0] if x else None
)

# Keep the old column for comparison, then fill gaps in driver_size_mm
# with the newly extracted value (don't overwrite values that already exist)
merged['driver_size_mm_old'] = merged['driver_size_mm']
merged['driver_size_mm'] = merged['driver_size_mm'].fillna(merged['driver_extracted_primary'])

# ------------------------------------------------------------------
# Report results
# ------------------------------------------------------------------
old_found = merged['driver_size_mm_old'].notna().sum()
new_found = merged['driver_size_mm'].notna().sum()
total = len(merged)

print(f"Original driver_size_mm coverage: {old_found}/{total} = {old_found/total*100:.1f}%")
print(f"Coverage after text extraction:   {new_found}/{total} = {new_found/total*100:.1f}%")
print(f"Newly filled from text: {new_found - old_found} rows")
print()
print("Value counts after fill:")
print(merged['driver_size_mm'].value_counts(dropna=False).sort_index())

# Optional: inspect exactly which rows got newly filled, to spot-check
newly_filled = merged[merged['driver_size_mm_old'].isna() & merged['driver_size_mm'].notna()]
print(f"\n{len(newly_filled)} rows newly filled - spot check a few:")
print(newly_filled[['product_name', 'driver_size_mm']].head(10).to_string())

Original driver_size_mm coverage: 375/565 = 66.4%
Coverage after text extraction:   422/565 = 74.7%
Newly filled from text: 47 rows

Value counts after fill:
driver_size_mm
6.0      30
7.0       7
8.0       7
10.0    175
11.0     38
12.0      8
12.4      2
13.0     71
14.2      7
14.8      1
15.0      1
16.0      1
18.0      1
30.0      1
40.0     58
50.0     14
NaN     143
Name: count, dtype: int64

47 rows newly filled - spot check a few:
                                                                                                                                            product_name  driver_size_mm
97   boAt Airdopes Drift | Wireless Earbdus Gaming Earbuds with 2x6mm Dual Drivers, Quad Mics with ENx™ and IWP™ Technology, LED Lights on Charging Case             6.0
167                              boAt Airdopes 121 PRO | Wireless Earbuds with 10mm Dynamic Drivers, ASAP™️ Charge, ENx™️ Technology, Easy Touch Control            10.0
219                                                                    boAt Bassheads 300C | In-Ear Wired Earphones with Type-C Connector & Built-in Mic            10.0
257                                                    boAt Rockerz Plus 440 | Best-in-Segment Wireless Headphones with Dual Drivers & 60 Hours Playback            40.0
271                                                                                                 Buds X ANC Truly Wireless Earbuds - ABHI Marketplace            13.0
278                                     boAt Immortal 125 | Gaming Wireless Earbuds with BEAST™️Mode, 40 Hours Playback, ENx™ Technology, RGB LED lights            10.0
300                                                        Nirvana Eutopia 2 ANC | Wireless Headphones with 45dB Adaptive Hybrid ANC & 80 Hours Playback            10.0
315                                                                                                                     Airwave Max 4 Wireless Headphone            40.0
320                                                                                                         Noise Air Buds Mini - Truly Wireless Earbuds            14.2
322                                                                                                               Noise Air Buds+ Truly Wireless Earbuds             6.0

In [580]:
merged['driver_size_mm'].isna().mean()*100-100

np.float64(-74.69026548672566)

In [586]:
merged.loc[
    merged["driver_size_mm"].ne(merged["ocr_driver_mm"])
    & merged["driver_size_mm"].notna()
    & merged["ocr_driver_mm"].notna(),
    ["driver_size_mm", "ocr_driver_mm"]
]

     driver_size_mm  ocr_driver_mm
40              6.0           11.0
200            13.0           35.0
297            10.0            8.0

In [589]:
merged['driver_size_mm'].isna().sum()

np.int64(143)

In [607]:
merged.loc[
    merged["category_specs"].eq("Wired Earphones"),
    "playtime_hours"
] = -1

In [608]:
merged['playtime_hours'].isna().sum()

np.int64(45)

In [610]:
merged.loc[461, "playtime_hours"] = 25
merged.loc[462, "playtime_hours"] = 25
merged.loc[463, "playtime_hours"] = 35
merged.loc[468, "playtime_hours"] = 25

In [615]:
merged['ocr_bluetooth'].value_counts(dropna=False)

ocr_bluetooth
 NaN    310
 5.0     77
 5.3     51
-1.0     43
 5.2     37
 5.1     16
 5.4     15
 4.1      9
 4.2      7
Name: count, dtype: int64

In [614]:
merged.loc[
    merged["category_specs"].eq("Wired Earphones"),
    "ocr_bluetooth"
] = -1

In [618]:
merged.loc[448, "ocr_bluetooth"] = 6.0

In [620]:
merged.loc[193, "ocr_bluetooth"] = 6.0

In [622]:
merged.loc[[409, 410, 411], "ocr_bluetooth"] = 5.3

In [624]:
bt_map = {
    320: 5.0,
    322: 5.0,
    350: 5.1,
    352: 5.1,
    358: 5.1,
    426: 5.3
}

merged.loc[list(bt_map), "ocr_bluetooth"] = pd.Series(bt_map)

In [638]:
merged['ocr_bluetooth'].value_counts(dropna=False)

ocr_bluetooth
 NaN    269
 5.0     81
 5.3     77
-1.0     43
 5.2     39
 5.1     21
 5.4     17
 4.1      9
 4.2      7
 6.0      2
Name: count, dtype: int64

In [627]:
merged.loc[268, "ocr_bluetooth"] = 5.3
merged.loc[325, "ocr_bluetooth"] = 5.4
merged.loc[366, "ocr_bluetooth"] = 5.3
merged.loc[368, "ocr_bluetooth"] = 5.2
merged.loc[376, "ocr_bluetooth"] = 5.3
merged.loc[377, "ocr_bluetooth"] = 5.3
merged.loc[398, "ocr_bluetooth"] = 5.3
merged.loc[404, "ocr_bluetooth"] = 5.3
merged.loc[405, "ocr_bluetooth"] = 5.3
merged.loc[408, "ocr_bluetooth"] = 5.3
merged.loc[431, "ocr_bluetooth"] = 5.3

In [637]:
merged.loc[270, "ocr_bluetooth"] = 5.1
merged.loc[323, "ocr_bluetooth"] = 5.2
merged.loc[326, "ocr_bluetooth"] = 5.3
merged.loc[375, "ocr_bluetooth"] = 5.3
merged.loc[392, "ocr_bluetooth"] = 5.3
merged.loc[401, "ocr_bluetooth"] = 5.3
merged.loc[425, "ocr_bluetooth"] = 5.1
merged.loc[428, "ocr_bluetooth"] = 5.0
merged.loc[434, "ocr_bluetooth"] = 5.3
merged.loc[444, "ocr_bluetooth"] = 5.3
merged.loc[270, "ocr_bluetooth"] = 5.3
merged.loc[323, "ocr_bluetooth"] = 5.2
merged.loc[324, "ocr_bluetooth"] = 5.3
merged.loc[326, "ocr_bluetooth"] = 5.3
merged.loc[327, "ocr_bluetooth"] = 5.3
merged.loc[367, "ocr_bluetooth"] = 5.4
merged.loc[375, "ocr_bluetooth"] = 5.3
merged.loc[392, "ocr_bluetooth"] = 5.3
merged.loc[394, "ocr_bluetooth"] = 5.1
merged.loc[401, "ocr_bluetooth"] = 5.3
merged.loc[403, "ocr_bluetooth"] = 5.0
merged.loc[425, "ocr_bluetooth"] = 5.1
merged.loc[428, "ocr_bluetooth"] = 5.0
merged.loc[434, "ocr_bluetooth"] = 5.3
merged.loc[444, "ocr_bluetooth"] = 5.3
merged.loc[459, "ocr_bluetooth"] = 5.3
merged.loc[460, "ocr_bluetooth"] = 5.3
merged.loc[464, "ocr_bluetooth"] = 5.3
merged.loc[474, "ocr_bluetooth"] = 5.3

In [640]:
merged['ocr_bluetooth'].isna().sum()*100/565

np.float64(47.610619469026545)

In [642]:
merged.loc[1, "ocr_bluetooth"] = 4.2
merged.loc[2, "ocr_bluetooth"] = 4.2
merged.loc[3, "ocr_bluetooth"] = 5.3
merged.loc[5, "ocr_bluetooth"] = 5.3
merged.loc[8, "ocr_bluetooth"] = 5.3
merged.loc[9, "ocr_bluetooth"] = 5.3
merged.loc[16, "ocr_bluetooth"] = 5.3
merged.loc[24, "ocr_bluetooth"] = 5.3
merged.loc[25, "ocr_bluetooth"] = 5.1
merged.loc[26, "ocr_bluetooth"] = 5.3
merged.loc[27, "ocr_bluetooth"] = 5.3
merged.loc[28, "ocr_bluetooth"] = 5.4
merged.loc[33, "ocr_bluetooth"] = 5.3
merged.loc[34, "ocr_bluetooth"] = 5.3
merged.loc[36, "ocr_bluetooth"] = 5.3
merged.loc[40, "ocr_bluetooth"] = 5.2
merged.loc[42, "ocr_bluetooth"] = 5.3
merged.loc[43, "ocr_bluetooth"] = 5.3
merged.loc[44, "ocr_bluetooth"] = 5.3
merged.loc[47, "ocr_bluetooth"] = 5.3
merged.loc[48, "ocr_bluetooth"] = 5.4
merged.loc[50, "ocr_bluetooth"] = 5.3
merged.loc[52, "ocr_bluetooth"] = 5.1
merged.loc[53, "ocr_bluetooth"] = 5.3
merged.loc[54, "ocr_bluetooth"] = 5.3
merged.loc[55, "ocr_bluetooth"] = 5.3
merged.loc[56, "ocr_bluetooth"] = 5.4
merged.loc[60, "ocr_bluetooth"] = 5.0
merged.loc[83, "ocr_bluetooth"] = 5.3
merged.loc[85, "ocr_bluetooth"] = 5.3
merged.loc[86, "ocr_bluetooth"] = 5.3
merged.loc[87, "ocr_bluetooth"] = 5.3
merged.loc[88, "ocr_bluetooth"] = 5.3
merged.loc[90, "ocr_bluetooth"] = 5.3
merged.loc[91, "ocr_bluetooth"] = 5.3
merged.loc[93, "ocr_bluetooth"] = 5.3
merged.loc[97, "ocr_bluetooth"] = 5.4
merged.loc[98, "ocr_bluetooth"] = 5.2
merged.loc[99, "ocr_bluetooth"] = 5.3
merged.loc[101, "ocr_bluetooth"] = 5.3
merged.loc[103, "ocr_bluetooth"] = 5.3
merged.loc[104, "ocr_bluetooth"] = 5.3

In [643]:
merged['ocr_bluetooth'].isna().sum()

np.int64(227)